// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: butterbox/pi/v1/pi.proto

package piv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/orvice/butter-box/pkg/proto/butterbox/pi/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PiServiceName is the fully-qualified name of the PiService service.
	PiServiceName = "butterbox.pi.v1.PiService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PiServiceCreateSessionProcedure is the fully-qualified name of the PiService's CreateSession RPC.
	PiServiceCreateSessionProcedure = "/butterbox.pi.v1.PiService/CreateSession"
	// PiServiceListSessionsProcedure is the fully-qualified name of the PiService's ListSessions RPC.
	PiServiceListSessionsProcedure = "/butterbox.pi.v1.PiService/ListSessions"
	// PiServiceGetSessionProcedure is the fully-qualified name of the PiService's GetSession RPC.
	PiServiceGetSessionProcedure = "/butterbox.pi.v1.PiService/GetSession"
	// PiServiceSendMessageProcedure is the fully-qualified name of the PiService's SendMessage RPC.
	PiServiceSendMessageProcedure = "/butterbox.pi.v1.PiService/SendMessage"
	// PiServiceStreamMessageProcedure is the fully-qualified name of the PiService's StreamMessage RPC.
	PiServiceStreamMessageProcedure = "/butterbox.pi.v1.PiService/StreamMessage"
	// PiServiceAbortSessionProcedure is the fully-qualified name of the PiService's AbortSession RPC.
	PiServiceAbortSessionProcedure = "/butterbox.pi.v1.PiService/AbortSession"
	// PiServiceDeleteSessionProcedure is the fully-qualified name of the PiService's DeleteSession RPC.
	PiServiceDeleteSessionProcedure = "/butterbox.pi.v1.PiService/DeleteSession"
)

// PiServiceClient is a client for the butterbox.pi.v1.PiService service.
type PiServiceClient interface {
	// CreateSession spawns a new pi session process.
	CreateSession(context.Context, *connect.Request[v1.CreateSessionRequest]) (*connect.Response[v1.CreateSessionResponse], error)
	// ListSessions reports sessions currently held by this server (active
	// processes only; historical sessions live in pi's session directory).
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	// GetSession reports state and usage statistics for one session,
	// re-attaching it if it is not currently active.
	GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error)
	// SendMessage sends one prompt and returns after the run fully settles
	// (pi's agent_settled: no pending retry, compaction, or queued follow-up).
	SendMessage(context.Context, *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.SendMessageResponse], error)
	// StreamMessage sends one prompt and streams raw pi events until the run
	// settles. The final message has type "agent_settled".
	StreamMessage(context.Context, *connect.Request[v1.StreamMessageRequest]) (*connect.ServerStreamForClient[v1.StreamMessageResponse], error)
	// AbortSession aborts the in-flight run, if any.
	AbortSession(context.Context, *connect.Request[v1.AbortSessionRequest]) (*connect.Response[v1.AbortSessionResponse], error)
	// DeleteSession stops the session process. The session file on disk is
	// kept unless purge is set.
	DeleteSession(context.Context, *connect.Request[v1.DeleteSessionRequest]) (*connect.Response[v1.DeleteSessionResponse], error)
}

// NewPiServiceClient constructs a client for the butterbox.pi.v1.PiService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPiServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PiServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	piServiceMethods := v1.File_butterbox_pi_v1_pi_proto.Services().ByName("PiService").Methods()
	return &piServiceClient{
		createSession: connect.NewClient[v1.CreateSessionRequest, v1.CreateSessionResponse](
			httpClient,
			baseURL+PiServiceCreateSessionProcedure,
			connect.WithSchema(piServiceMethods.ByName("CreateSession")),
			connect.WithClientOptions(opts...),
		),
		listSessions: connect.NewClient[v1.ListSessionsRequest, v1.ListSessionsResponse](
			httpClient,
			baseURL+PiServiceListSessionsProcedure,
			connect.WithSchema(piServiceMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		getSession: connect.NewClient[v1.GetSessionRequest, v1.GetSessionResponse](
			httpClient,
			baseURL+PiServiceGetSessionProcedure,
			connect.WithSchema(piServiceMethods.ByName("GetSession")),
			connect.WithClientOptions(opts...),
		),
		sendMessage: connect.NewClient[v1.SendMessageRequest, v1.SendMessageResponse](
			httpClient,
			baseURL+PiServiceSendMessageProcedure,
			connect.WithSchema(piServiceMethods.ByName("SendMessage")),
			connect.WithClientOptions(opts...),
		),
		streamMessage: connect.NewClient[v1.StreamMessageRequest, v1.StreamMessageResponse](
			httpClient,
			baseURL+PiServiceStreamMessageProcedure,
			connect.WithSchema(piServiceMethods.ByName("StreamMessage")),
			connect.WithClientOptions(opts...),
		),
		abortSession: connect.NewClient[v1.AbortSessionRequest, v1.AbortSessionResponse](
			httpClient,
			baseURL+PiServiceAbortSessionProcedure,
			connect.WithSchema(piServiceMethods.ByName("AbortSession")),
			connect.WithClientOptions(opts...),
		),
		deleteSession: connect.NewClient[v1.DeleteSessionRequest, v1.DeleteSessionResponse](
			httpClient,
			baseURL+PiServiceDeleteSessionProcedure,
			connect.WithSchema(piServiceMethods.ByName("DeleteSession")),
			connect.WithClientOptions(opts...),
		),
	}
}

// piServiceClient implements PiServiceClient.
type piServiceClient struct {
	createSession *connect.Client[v1.CreateSessionRequest, v1.CreateSessionResponse]
	listSessions  *connect.Client[v1.ListSessionsRequest, v1.ListSessionsResponse]
	getSession    *connect.Client[v1.GetSessionRequest, v1.GetSessionResponse]
	sendMessage   *connect.Client[v1.SendMessageRequest, v1.SendMessageResponse]
	streamMessage *connect.Client[v1.StreamMessageRequest, v1.StreamMessageResponse]
	abortSession  *connect.Client[v1.AbortSessionRequest, v1.AbortSessionResponse]
	deleteSession *connect.Client[v1.DeleteSessionRequest, v1.DeleteSessionResponse]
}

// CreateSession calls butterbox.pi.v1.PiService.CreateSession.
func (c *piServiceClient) CreateSession(ctx context.Context, req *connect.Request[v1.CreateSessionRequest]) (*connect.Response[v1.CreateSessionResponse], error) {
	return c.createSession.CallUnary(ctx, req)
}

// ListSessions calls butterbox.pi.v1.PiService.ListSessions.
func (c *piServiceClient) ListSessions(ctx context.Context, req *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// GetSession calls butterbox.pi.v1.PiService.GetSession.
func (c *piServiceClient) GetSession(ctx context.Context, req *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error) {
	return c.getSession.CallUnary(ctx, req)
}

// SendMessage calls butterbox.pi.v1.PiService.SendMessage.
func (c *piServiceClient) SendMessage(ctx context.Context, req *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.SendMessageResponse], error) {
	return c.sendMessage.CallUnary(ctx, req)
}

// StreamMessage calls butterbox.pi.v1.PiService.StreamMessage.
func (c *piServiceClient) StreamMessage(ctx context.Context, req *connect.Request[v1.StreamMessageRequest]) (*connect.ServerStreamForClient[v1.StreamMessageResponse], error) {
	return c.streamMessage.CallServerStream(ctx, req)
}

// AbortSession calls butterbox.pi.v1.PiService.AbortSession.
func (c *piServiceClient) AbortSession(ctx context.Context, req *connect.Request[v1.AbortSessionRequest]) (*connect.Response[v1.AbortSessionResponse], error) {
	return c.abortSession.CallUnary(ctx, req)
}

// DeleteSession calls butterbox.pi.v1.PiService.DeleteSession.
func (c *piServiceClient) DeleteSession(ctx context.Context, req *connect.Request[v1.DeleteSessionRequest]) (*connect.Response[v1.DeleteSessionResponse], error) {
	return c.deleteSession.CallUnary(ctx, req)
}

// PiServiceHandler is an implementation of the butterbox.pi.v1.PiService service.
type PiServiceHandler interface {
	// CreateSession spawns a new pi session process.
	CreateSession(context.Context, *connect.Request[v1.CreateSessionRequest]) (*connect.Response[v1.CreateSessionResponse], error)
	// ListSessions reports sessions currently held by this server (active
	// processes only; historical sessions live in pi's session directory).
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	// GetSession reports state and usage statistics for one session,
	// re-attaching it if it is not currently active.
	GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error)
	// SendMessage sends one prompt and returns after the run fully settles
	// (pi's agent_settled: no pending retry, compaction, or queued follow-up).
	SendMessage(context.Context, *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.SendMessageResponse], error)
	// StreamMessage sends one prompt and streams raw pi events until the run
	// settles. The final message has type "agent_settled".
	StreamMessage(context.Context, *connect.Request[v1.StreamMessageRequest], *connect.ServerStream[v1.StreamMessageResponse]) error
	// AbortSession aborts the in-flight run, if any.
	AbortSession(context.Context, *connect.Request[v1.AbortSessionRequest]) (*connect.Response[v1.AbortSessionResponse], error)
	// DeleteSession stops the session process. The session file on disk is
	// kept unless purge is set.
	DeleteSession(context.Context, *connect.Request[v1.DeleteSessionRequest]) (*connect.Response[v1.DeleteSessionResponse], error)
}

// NewPiServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPiServiceHandler(svc PiServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	piServiceMethods := v1.File_butterbox_pi_v1_pi_proto.Services().ByName("PiService").Methods()
	piServiceCreateSessionHandler := connect.NewUnaryHandler(
		PiServiceCreateSessionProcedure,
		svc.CreateSession,
		connect.WithSchema(piServiceMethods.ByName("CreateSession")),
		connect.WithHandlerOptions(opts...),
	)
	piServiceListSessionsHandler := connect.NewUnaryHandler(
		PiServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(piServiceMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	piServiceGetSessionHandler := connect.NewUnaryHandler(
		PiServiceGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(piServiceMethods.ByName("GetSession")),
		connect.WithHandlerOptions(opts...),
	)
	piServiceSendMessageHandler := connect.NewUnaryHandler(
		PiServiceSendMessageProcedure,
		svc.SendMessage,
		connect.WithSchema(piServiceMethods.ByName("SendMessage")),
		connect.WithHandlerOptions(opts...),
	)
	piServiceStreamMessageHandler := connect.NewServerStreamHandler(
		PiServiceStreamMessageProcedure,
		svc.StreamMessage,
		connect.WithSchema(piServiceMethods.ByName("StreamMessage")),
		connect.WithHandlerOptions(opts...),
	)
	piServiceAbortSessionHandler := connect.NewUnaryHandler(
		PiServiceAbortSessionProcedure,
		svc.AbortSession,
		connect.WithSchema(piServiceMethods.ByName("AbortSession")),
		connect.WithHandlerOptions(opts...),
	)
	piServiceDeleteSessionHandler := connect.NewUnaryHandler(
		PiServiceDeleteSessionProcedure,
		svc.DeleteSession,
		connect.WithSchema(piServiceMethods.ByName("DeleteSession")),
		connect.WithHandlerOptions(opts...),
	)
	return "/butterbox.pi.v1.PiService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PiServiceCreateSessionProcedure:
			piServiceCreateSessionHandler.ServeHTTP(w, r)
		case PiServiceListSessionsProcedure:
			piServiceListSessionsHandler.ServeHTTP(w, r)
		case PiServiceGetSessionProcedure:
			piServiceGetSessionHandler.ServeHTTP(w, r)
		case PiServiceSendMessageProcedure:
			piServiceSendMessageHandler.ServeHTTP(w, r)
		case PiServiceStreamMessageProcedure:
			piServiceStreamMessageHandler.ServeHTTP(w, r)
		case PiServiceAbortSessionProcedure:
			piServiceAbortSessionHandler.ServeHTTP(w, r)
		case PiServiceDeleteSessionProcedure:
			piServiceDeleteSessionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPiServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPiServiceHandler struct{}

func (UnimplementedPiServiceHandler) CreateSession(context.Context, *connect.Request[v1.CreateSessionRequest]) (*connect.Response[v1.CreateSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("butterbox.pi.v1.PiService.CreateSession is not implemented"))
}

func (UnimplementedPiServiceHandler) ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("butterbox.pi.v1.PiService.ListSessions is not implemented"))
}

func (UnimplementedPiServiceHandler) GetSession(context.Context, *connect.Request[v1.GetSessionRequest]) (*connect.Response[v1.GetSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("butterbox.pi.v1.PiService.GetSession is not implemented"))
}

func (UnimplementedPiServiceHandler) SendMessage(context.Context, *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.SendMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("butterbox.pi.v1.PiService.SendMessage is not implemented"))
}

func (UnimplementedPiServiceHandler) StreamMessage(context.Context, *connect.Request[v1.StreamMessageRequest], *connect.ServerStream[v1.StreamMessageResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("butterbox.pi.v1.PiService.StreamMessage is not implemented"))
}

func (UnimplementedPiServiceHandler) AbortSession(context.Context, *connect.Request[v1.AbortSessionRequest]) (*connect.Response[v1.AbortSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("butterbox.pi.v1.PiService.AbortSession is not implemented"))
}

func (UnimplementedPiServiceHandler) DeleteSession(context.Context, *connect.Request[v1.DeleteSessionRequest]) (*connect.Response[v1.DeleteSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("butterbox.pi.v1.PiService.DeleteSession is not implemented"))
}
