// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: butterbox/cursor/v1/cursor.proto

// The ButterBox CursorService contract. Keep field names and numbers stable;
// the Butter client consumes this surface over ConnectRPC.

package cursorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional display name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional model ID. Empty uses the bridge default.
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// Agent mode: "agent" (default) or "plan".
	Mode string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	// Working directory, absolute or relative to the box sandbox root.
	Cwd           string `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_butterbox_cursor_v1_cursor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_cursor_v1_cursor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_butterbox_cursor_v1_cursor_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSessionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateSessionRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CreateSessionRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

type CreateSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque session ID on the box (the bridge's agent ID).
	SessionId     string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_butterbox_cursor_v1_cursor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_cursor_v1_cursor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_butterbox_cursor_v1_cursor_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Images        []*ImageContent        `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_butterbox_cursor_v1_cursor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_cursor_v1_cursor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_butterbox_cursor_v1_cursor_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendMessageRequest) GetImages() []*ImageContent {
	if x != nil {
		return x.Images
	}
	return nil
}

type SendMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The agent's final text output after the turn ended.
	Text          string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_butterbox_cursor_v1_cursor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_cursor_v1_cursor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_butterbox_cursor_v1_cursor_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AbortSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortSessionRequest) Reset() {
	*x = AbortSessionRequest{}
	mi := &file_butterbox_cursor_v1_cursor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortSessionRequest) ProtoMessage() {}

func (x *AbortSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_cursor_v1_cursor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortSessionRequest.ProtoReflect.Descriptor instead.
func (*AbortSessionRequest) Descriptor() ([]byte, []int) {
	return file_butterbox_cursor_v1_cursor_proto_rawDescGZIP(), []int{4}
}

func (x *AbortSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AbortSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortSessionResponse) Reset() {
	*x = AbortSessionResponse{}
	mi := &file_butterbox_cursor_v1_cursor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortSessionResponse) ProtoMessage() {}

func (x *AbortSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_cursor_v1_cursor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortSessionResponse.ProtoReflect.Descriptor instead.
func (*AbortSessionResponse) Descriptor() ([]byte, []int) {
	return file_butterbox_cursor_v1_cursor_proto_rawDescGZIP(), []int{5}
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_butterbox_cursor_v1_cursor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_cursor_v1_cursor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_butterbox_cursor_v1_cursor_proto_rawDescGZIP(), []int{6}
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_butterbox_cursor_v1_cursor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_cursor_v1_cursor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_butterbox_cursor_v1_cursor_proto_rawDescGZIP(), []int{7}
}

func (x *ListModelsResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_butterbox_cursor_v1_cursor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_cursor_v1_cursor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_butterbox_cursor_v1_cursor_proto_rawDescGZIP(), []int{8}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ImageContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g. "image/png".
	MimeType string `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Raw image bytes.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageContent) Reset() {
	*x = ImageContent{}
	mi := &file_butterbox_cursor_v1_cursor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageContent) ProtoMessage() {}

func (x *ImageContent) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_cursor_v1_cursor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageContent.ProtoReflect.Descriptor instead.
func (*ImageContent) Descriptor() ([]byte, []int) {
	return file_butterbox_cursor_v1_cursor_proto_rawDescGZIP(), []int{9}
}

func (x *ImageContent) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ImageContent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_butterbox_cursor_v1_cursor_proto protoreflect.FileDescriptor

const file_butterbox_cursor_v1_cursor_proto_rawDesc = "" +
	"\n" +
	" butterbox/cursor/v1/cursor.proto\x12\x13butterbox.cursor.v1\"f\n" +
	"\x14CreateSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\"6\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x88\x01\n" +
	"\x12SendMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\x06images\x18\x03 \x03(\v2!.butterbox.cursor.v1.ImageContentR\x06images\")\n" +
	"\x13SendMessageResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"4\n" +
	"\x13AbortSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x16\n" +
	"\x14AbortSessionResponse\"\x13\n" +
	"\x11ListModelsRequest\"H\n" +
	"\x12ListModelsResponse\x122\n" +
	"\x06models\x18\x01 \x03(\v2\x1a.butterbox.cursor.v1.ModelR\x06models\"+\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"?\n" +
	"\fImageContent\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data2\x9d\x03\n" +
	"\rCursorService\x12f\n" +
	"\rCreateSession\x12).butterbox.cursor.v1.CreateSessionRequest\x1a*.butterbox.cursor.v1.CreateSessionResponse\x12`\n" +
	"\vSendMessage\x12'.butterbox.cursor.v1.SendMessageRequest\x1a(.butterbox.cursor.v1.SendMessageResponse\x12c\n" +
	"\fAbortSession\x12(.butterbox.cursor.v1.AbortSessionRequest\x1a).butterbox.cursor.v1.AbortSessionResponse\x12]\n" +
	"\n" +
	"ListModels\x12&.butterbox.cursor.v1.ListModelsRequest\x1a'.butterbox.cursor.v1.ListModelsResponseBEZCgithub.com/orvice/butter-box/pkg/proto/butterbox/cursor/v1;cursorv1b\x06proto3"

var (
	file_butterbox_cursor_v1_cursor_proto_rawDescOnce sync.Once
	file_butterbox_cursor_v1_cursor_proto_rawDescData []byte
)

func file_butterbox_cursor_v1_cursor_proto_rawDescGZIP() []byte {
	file_butterbox_cursor_v1_cursor_proto_rawDescOnce.Do(func() {
		file_butterbox_cursor_v1_cursor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_butterbox_cursor_v1_cursor_proto_rawDesc), len(file_butterbox_cursor_v1_cursor_proto_rawDesc)))
	})
	return file_butterbox_cursor_v1_cursor_proto_rawDescData
}

var file_butterbox_cursor_v1_cursor_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_butterbox_cursor_v1_cursor_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),  // 0: butterbox.cursor.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil), // 1: butterbox.cursor.v1.CreateSessionResponse
	(*SendMessageRequest)(nil),    // 2: butterbox.cursor.v1.SendMessageRequest
	(*SendMessageResponse)(nil),   // 3: butterbox.cursor.v1.SendMessageResponse
	(*AbortSessionRequest)(nil),   // 4: butterbox.cursor.v1.AbortSessionRequest
	(*AbortSessionResponse)(nil),  // 5: butterbox.cursor.v1.AbortSessionResponse
	(*ListModelsRequest)(nil),     // 6: butterbox.cursor.v1.ListModelsRequest
	(*ListModelsResponse)(nil),    // 7: butterbox.cursor.v1.ListModelsResponse
	(*Model)(nil),                 // 8: butterbox.cursor.v1.Model
	(*ImageContent)(nil),          // 9: butterbox.cursor.v1.ImageContent
}
var file_butterbox_cursor_v1_cursor_proto_depIdxs = []int32{
	9, // 0: butterbox.cursor.v1.SendMessageRequest.images:type_name -> butterbox.cursor.v1.ImageContent
	8, // 1: butterbox.cursor.v1.ListModelsResponse.models:type_name -> butterbox.cursor.v1.Model
	0, // 2: butterbox.cursor.v1.CursorService.CreateSession:input_type -> butterbox.cursor.v1.CreateSessionRequest
	2, // 3: butterbox.cursor.v1.CursorService.SendMessage:input_type -> butterbox.cursor.v1.SendMessageRequest
	4, // 4: butterbox.cursor.v1.CursorService.AbortSession:input_type -> butterbox.cursor.v1.AbortSessionRequest
	6, // 5: butterbox.cursor.v1.CursorService.ListModels:input_type -> butterbox.cursor.v1.ListModelsRequest
	1, // 6: butterbox.cursor.v1.CursorService.CreateSession:output_type -> butterbox.cursor.v1.CreateSessionResponse
	3, // 7: butterbox.cursor.v1.CursorService.SendMessage:output_type -> butterbox.cursor.v1.SendMessageResponse
	5, // 8: butterbox.cursor.v1.CursorService.AbortSession:output_type -> butterbox.cursor.v1.AbortSessionResponse
	7, // 9: butterbox.cursor.v1.CursorService.ListModels:output_type -> butterbox.cursor.v1.ListModelsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_butterbox_cursor_v1_cursor_proto_init() }
func file_butterbox_cursor_v1_cursor_proto_init() {
	if File_butterbox_cursor_v1_cursor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_butterbox_cursor_v1_cursor_proto_rawDesc), len(file_butterbox_cursor_v1_cursor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_butterbox_cursor_v1_cursor_proto_goTypes,
		DependencyIndexes: file_butterbox_cursor_v1_cursor_proto_depIdxs,
		MessageInfos:      file_butterbox_cursor_v1_cursor_proto_msgTypes,
	}.Build()
	File_butterbox_cursor_v1_cursor_proto = out.File
	file_butterbox_cursor_v1_cursor_proto_goTypes = nil
	file_butterbox_cursor_v1_cursor_proto_depIdxs = nil
}
