// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sdk/v1/sdk_bridge_control_service.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/orvice/butter-box/pkg/proto/sdk/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SdkBridgeControlServiceName is the fully-qualified name of the SdkBridgeControlService service.
	SdkBridgeControlServiceName = "sdk.v1.SdkBridgeControlService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SdkBridgeControlServicePingProcedure is the fully-qualified name of the SdkBridgeControlService's
	// Ping RPC.
	SdkBridgeControlServicePingProcedure = "/sdk.v1.SdkBridgeControlService/Ping"
	// SdkBridgeControlServiceShutdownProcedure is the fully-qualified name of the
	// SdkBridgeControlService's Shutdown RPC.
	SdkBridgeControlServiceShutdownProcedure = "/sdk.v1.SdkBridgeControlService/Shutdown"
	// SdkBridgeControlServiceGetVersionProcedure is the fully-qualified name of the
	// SdkBridgeControlService's GetVersion RPC.
	SdkBridgeControlServiceGetVersionProcedure = "/sdk.v1.SdkBridgeControlService/GetVersion"
	// SdkBridgeControlServiceSetToolCallbackProcedure is the fully-qualified name of the
	// SdkBridgeControlService's SetToolCallback RPC.
	SdkBridgeControlServiceSetToolCallbackProcedure = "/sdk.v1.SdkBridgeControlService/SetToolCallback"
)

// SdkBridgeControlServiceClient is a client for the sdk.v1.SdkBridgeControlService service.
type SdkBridgeControlServiceClient interface {
	// Liveness check. Returns a fixed message when the bridge is accepting RPCs.
	Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error)
	// Request a graceful shutdown of the bridge process.
	Shutdown(context.Context, *connect.Request[v1.ShutdownRequest]) (*connect.Response[v1.ShutdownResponse], error)
	// Bridge build version, protocol version, and advertised capabilities.
	GetVersion(context.Context, *connect.Request[v1.GetVersionRequest]) (*connect.Response[v1.GetVersionResponse], error)
	// Point the bridge at a host-process custom-tool callback server after
	// startup. Lets clients that attach to an already-running bridge register
	// host execute handlers. Same-host (loopback) only.
	SetToolCallback(context.Context, *connect.Request[v1.SetToolCallbackRequest]) (*connect.Response[v1.SetToolCallbackResponse], error)
}

// NewSdkBridgeControlServiceClient constructs a client for the sdk.v1.SdkBridgeControlService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSdkBridgeControlServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SdkBridgeControlServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sdkBridgeControlServiceMethods := v1.File_sdk_v1_sdk_bridge_control_service_proto.Services().ByName("SdkBridgeControlService").Methods()
	return &sdkBridgeControlServiceClient{
		ping: connect.NewClient[v1.PingRequest, v1.PingResponse](
			httpClient,
			baseURL+SdkBridgeControlServicePingProcedure,
			connect.WithSchema(sdkBridgeControlServiceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
		shutdown: connect.NewClient[v1.ShutdownRequest, v1.ShutdownResponse](
			httpClient,
			baseURL+SdkBridgeControlServiceShutdownProcedure,
			connect.WithSchema(sdkBridgeControlServiceMethods.ByName("Shutdown")),
			connect.WithClientOptions(opts...),
		),
		getVersion: connect.NewClient[v1.GetVersionRequest, v1.GetVersionResponse](
			httpClient,
			baseURL+SdkBridgeControlServiceGetVersionProcedure,
			connect.WithSchema(sdkBridgeControlServiceMethods.ByName("GetVersion")),
			connect.WithClientOptions(opts...),
		),
		setToolCallback: connect.NewClient[v1.SetToolCallbackRequest, v1.SetToolCallbackResponse](
			httpClient,
			baseURL+SdkBridgeControlServiceSetToolCallbackProcedure,
			connect.WithSchema(sdkBridgeControlServiceMethods.ByName("SetToolCallback")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sdkBridgeControlServiceClient implements SdkBridgeControlServiceClient.
type sdkBridgeControlServiceClient struct {
	ping            *connect.Client[v1.PingRequest, v1.PingResponse]
	shutdown        *connect.Client[v1.ShutdownRequest, v1.ShutdownResponse]
	getVersion      *connect.Client[v1.GetVersionRequest, v1.GetVersionResponse]
	setToolCallback *connect.Client[v1.SetToolCallbackRequest, v1.SetToolCallbackResponse]
}

// Ping calls sdk.v1.SdkBridgeControlService.Ping.
func (c *sdkBridgeControlServiceClient) Ping(ctx context.Context, req *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// Shutdown calls sdk.v1.SdkBridgeControlService.Shutdown.
func (c *sdkBridgeControlServiceClient) Shutdown(ctx context.Context, req *connect.Request[v1.ShutdownRequest]) (*connect.Response[v1.ShutdownResponse], error) {
	return c.shutdown.CallUnary(ctx, req)
}

// GetVersion calls sdk.v1.SdkBridgeControlService.GetVersion.
func (c *sdkBridgeControlServiceClient) GetVersion(ctx context.Context, req *connect.Request[v1.GetVersionRequest]) (*connect.Response[v1.GetVersionResponse], error) {
	return c.getVersion.CallUnary(ctx, req)
}

// SetToolCallback calls sdk.v1.SdkBridgeControlService.SetToolCallback.
func (c *sdkBridgeControlServiceClient) SetToolCallback(ctx context.Context, req *connect.Request[v1.SetToolCallbackRequest]) (*connect.Response[v1.SetToolCallbackResponse], error) {
	return c.setToolCallback.CallUnary(ctx, req)
}

// SdkBridgeControlServiceHandler is an implementation of the sdk.v1.SdkBridgeControlService
// service.
type SdkBridgeControlServiceHandler interface {
	// Liveness check. Returns a fixed message when the bridge is accepting RPCs.
	Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error)
	// Request a graceful shutdown of the bridge process.
	Shutdown(context.Context, *connect.Request[v1.ShutdownRequest]) (*connect.Response[v1.ShutdownResponse], error)
	// Bridge build version, protocol version, and advertised capabilities.
	GetVersion(context.Context, *connect.Request[v1.GetVersionRequest]) (*connect.Response[v1.GetVersionResponse], error)
	// Point the bridge at a host-process custom-tool callback server after
	// startup. Lets clients that attach to an already-running bridge register
	// host execute handlers. Same-host (loopback) only.
	SetToolCallback(context.Context, *connect.Request[v1.SetToolCallbackRequest]) (*connect.Response[v1.SetToolCallbackResponse], error)
}

// NewSdkBridgeControlServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSdkBridgeControlServiceHandler(svc SdkBridgeControlServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sdkBridgeControlServiceMethods := v1.File_sdk_v1_sdk_bridge_control_service_proto.Services().ByName("SdkBridgeControlService").Methods()
	sdkBridgeControlServicePingHandler := connect.NewUnaryHandler(
		SdkBridgeControlServicePingProcedure,
		svc.Ping,
		connect.WithSchema(sdkBridgeControlServiceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	sdkBridgeControlServiceShutdownHandler := connect.NewUnaryHandler(
		SdkBridgeControlServiceShutdownProcedure,
		svc.Shutdown,
		connect.WithSchema(sdkBridgeControlServiceMethods.ByName("Shutdown")),
		connect.WithHandlerOptions(opts...),
	)
	sdkBridgeControlServiceGetVersionHandler := connect.NewUnaryHandler(
		SdkBridgeControlServiceGetVersionProcedure,
		svc.GetVersion,
		connect.WithSchema(sdkBridgeControlServiceMethods.ByName("GetVersion")),
		connect.WithHandlerOptions(opts...),
	)
	sdkBridgeControlServiceSetToolCallbackHandler := connect.NewUnaryHandler(
		SdkBridgeControlServiceSetToolCallbackProcedure,
		svc.SetToolCallback,
		connect.WithSchema(sdkBridgeControlServiceMethods.ByName("SetToolCallback")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sdk.v1.SdkBridgeControlService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SdkBridgeControlServicePingProcedure:
			sdkBridgeControlServicePingHandler.ServeHTTP(w, r)
		case SdkBridgeControlServiceShutdownProcedure:
			sdkBridgeControlServiceShutdownHandler.ServeHTTP(w, r)
		case SdkBridgeControlServiceGetVersionProcedure:
			sdkBridgeControlServiceGetVersionHandler.ServeHTTP(w, r)
		case SdkBridgeControlServiceSetToolCallbackProcedure:
			sdkBridgeControlServiceSetToolCallbackHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSdkBridgeControlServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSdkBridgeControlServiceHandler struct{}

func (UnimplementedSdkBridgeControlServiceHandler) Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkBridgeControlService.Ping is not implemented"))
}

func (UnimplementedSdkBridgeControlServiceHandler) Shutdown(context.Context, *connect.Request[v1.ShutdownRequest]) (*connect.Response[v1.ShutdownResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkBridgeControlService.Shutdown is not implemented"))
}

func (UnimplementedSdkBridgeControlServiceHandler) GetVersion(context.Context, *connect.Request[v1.GetVersionRequest]) (*connect.Response[v1.GetVersionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkBridgeControlService.GetVersion is not implemented"))
}

func (UnimplementedSdkBridgeControlServiceHandler) SetToolCallback(context.Context, *connect.Request[v1.SetToolCallbackRequest]) (*connect.Response[v1.SetToolCallbackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkBridgeControlService.SetToolCallback is not implemented"))
}
