// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sdk/v1/sdk_cursor_service.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/orvice/butter-box/pkg/proto/sdk/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SdkCursorServiceName is the fully-qualified name of the SdkCursorService service.
	SdkCursorServiceName = "sdk.v1.SdkCursorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SdkCursorServiceMeProcedure is the fully-qualified name of the SdkCursorService's Me RPC.
	SdkCursorServiceMeProcedure = "/sdk.v1.SdkCursorService/Me"
	// SdkCursorServiceListModelsProcedure is the fully-qualified name of the SdkCursorService's
	// ListModels RPC.
	SdkCursorServiceListModelsProcedure = "/sdk.v1.SdkCursorService/ListModels"
	// SdkCursorServiceListRepositoriesProcedure is the fully-qualified name of the SdkCursorService's
	// ListRepositories RPC.
	SdkCursorServiceListRepositoriesProcedure = "/sdk.v1.SdkCursorService/ListRepositories"
)

// SdkCursorServiceClient is a client for the sdk.v1.SdkCursorService service.
type SdkCursorServiceClient interface {
	// Authenticated account identity for the supplied API key.
	Me(context.Context, *connect.Request[v1.MeRequest]) (*connect.Response[v1.MeResponse], error)
	// Models available to the authenticated account.
	ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error)
	// Repositories the authenticated account can use with cloud agents.
	ListRepositories(context.Context, *connect.Request[v1.ListRepositoriesRequest]) (*connect.Response[v1.ListRepositoriesResponse], error)
}

// NewSdkCursorServiceClient constructs a client for the sdk.v1.SdkCursorService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSdkCursorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SdkCursorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sdkCursorServiceMethods := v1.File_sdk_v1_sdk_cursor_service_proto.Services().ByName("SdkCursorService").Methods()
	return &sdkCursorServiceClient{
		me: connect.NewClient[v1.MeRequest, v1.MeResponse](
			httpClient,
			baseURL+SdkCursorServiceMeProcedure,
			connect.WithSchema(sdkCursorServiceMethods.ByName("Me")),
			connect.WithClientOptions(opts...),
		),
		listModels: connect.NewClient[v1.ListModelsRequest, v1.ListModelsResponse](
			httpClient,
			baseURL+SdkCursorServiceListModelsProcedure,
			connect.WithSchema(sdkCursorServiceMethods.ByName("ListModels")),
			connect.WithClientOptions(opts...),
		),
		listRepositories: connect.NewClient[v1.ListRepositoriesRequest, v1.ListRepositoriesResponse](
			httpClient,
			baseURL+SdkCursorServiceListRepositoriesProcedure,
			connect.WithSchema(sdkCursorServiceMethods.ByName("ListRepositories")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sdkCursorServiceClient implements SdkCursorServiceClient.
type sdkCursorServiceClient struct {
	me               *connect.Client[v1.MeRequest, v1.MeResponse]
	listModels       *connect.Client[v1.ListModelsRequest, v1.ListModelsResponse]
	listRepositories *connect.Client[v1.ListRepositoriesRequest, v1.ListRepositoriesResponse]
}

// Me calls sdk.v1.SdkCursorService.Me.
func (c *sdkCursorServiceClient) Me(ctx context.Context, req *connect.Request[v1.MeRequest]) (*connect.Response[v1.MeResponse], error) {
	return c.me.CallUnary(ctx, req)
}

// ListModels calls sdk.v1.SdkCursorService.ListModels.
func (c *sdkCursorServiceClient) ListModels(ctx context.Context, req *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	return c.listModels.CallUnary(ctx, req)
}

// ListRepositories calls sdk.v1.SdkCursorService.ListRepositories.
func (c *sdkCursorServiceClient) ListRepositories(ctx context.Context, req *connect.Request[v1.ListRepositoriesRequest]) (*connect.Response[v1.ListRepositoriesResponse], error) {
	return c.listRepositories.CallUnary(ctx, req)
}

// SdkCursorServiceHandler is an implementation of the sdk.v1.SdkCursorService service.
type SdkCursorServiceHandler interface {
	// Authenticated account identity for the supplied API key.
	Me(context.Context, *connect.Request[v1.MeRequest]) (*connect.Response[v1.MeResponse], error)
	// Models available to the authenticated account.
	ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error)
	// Repositories the authenticated account can use with cloud agents.
	ListRepositories(context.Context, *connect.Request[v1.ListRepositoriesRequest]) (*connect.Response[v1.ListRepositoriesResponse], error)
}

// NewSdkCursorServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSdkCursorServiceHandler(svc SdkCursorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sdkCursorServiceMethods := v1.File_sdk_v1_sdk_cursor_service_proto.Services().ByName("SdkCursorService").Methods()
	sdkCursorServiceMeHandler := connect.NewUnaryHandler(
		SdkCursorServiceMeProcedure,
		svc.Me,
		connect.WithSchema(sdkCursorServiceMethods.ByName("Me")),
		connect.WithHandlerOptions(opts...),
	)
	sdkCursorServiceListModelsHandler := connect.NewUnaryHandler(
		SdkCursorServiceListModelsProcedure,
		svc.ListModels,
		connect.WithSchema(sdkCursorServiceMethods.ByName("ListModels")),
		connect.WithHandlerOptions(opts...),
	)
	sdkCursorServiceListRepositoriesHandler := connect.NewUnaryHandler(
		SdkCursorServiceListRepositoriesProcedure,
		svc.ListRepositories,
		connect.WithSchema(sdkCursorServiceMethods.ByName("ListRepositories")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sdk.v1.SdkCursorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SdkCursorServiceMeProcedure:
			sdkCursorServiceMeHandler.ServeHTTP(w, r)
		case SdkCursorServiceListModelsProcedure:
			sdkCursorServiceListModelsHandler.ServeHTTP(w, r)
		case SdkCursorServiceListRepositoriesProcedure:
			sdkCursorServiceListRepositoriesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSdkCursorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSdkCursorServiceHandler struct{}

func (UnimplementedSdkCursorServiceHandler) Me(context.Context, *connect.Request[v1.MeRequest]) (*connect.Response[v1.MeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkCursorService.Me is not implemented"))
}

func (UnimplementedSdkCursorServiceHandler) ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkCursorService.ListModels is not implemented"))
}

func (UnimplementedSdkCursorServiceHandler) ListRepositories(context.Context, *connect.Request[v1.ListRepositoriesRequest]) (*connect.Response[v1.ListRepositoriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkCursorService.ListRepositories is not implemented"))
}
