// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sdk/v1/sdk_custom_tool_callback_service.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/orvice/butter-box/pkg/proto/sdk/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SdkCustomToolCallbackServiceName is the fully-qualified name of the SdkCustomToolCallbackService
	// service.
	SdkCustomToolCallbackServiceName = "sdk.v1.SdkCustomToolCallbackService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SdkCustomToolCallbackServiceCallCustomToolProcedure is the fully-qualified name of the
	// SdkCustomToolCallbackService's CallCustomTool RPC.
	SdkCustomToolCallbackServiceCallCustomToolProcedure = "/sdk.v1.SdkCustomToolCallbackService/CallCustomTool"
)

// SdkCustomToolCallbackServiceClient is a client for the sdk.v1.SdkCustomToolCallbackService
// service.
type SdkCustomToolCallbackServiceClient interface {
	CallCustomTool(context.Context, *connect.Request[v1.CallCustomToolRequest]) (*connect.Response[v1.CallCustomToolResponse], error)
}

// NewSdkCustomToolCallbackServiceClient constructs a client for the
// sdk.v1.SdkCustomToolCallbackService service. By default, it uses the Connect protocol with the
// binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use the
// gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSdkCustomToolCallbackServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SdkCustomToolCallbackServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sdkCustomToolCallbackServiceMethods := v1.File_sdk_v1_sdk_custom_tool_callback_service_proto.Services().ByName("SdkCustomToolCallbackService").Methods()
	return &sdkCustomToolCallbackServiceClient{
		callCustomTool: connect.NewClient[v1.CallCustomToolRequest, v1.CallCustomToolResponse](
			httpClient,
			baseURL+SdkCustomToolCallbackServiceCallCustomToolProcedure,
			connect.WithSchema(sdkCustomToolCallbackServiceMethods.ByName("CallCustomTool")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sdkCustomToolCallbackServiceClient implements SdkCustomToolCallbackServiceClient.
type sdkCustomToolCallbackServiceClient struct {
	callCustomTool *connect.Client[v1.CallCustomToolRequest, v1.CallCustomToolResponse]
}

// CallCustomTool calls sdk.v1.SdkCustomToolCallbackService.CallCustomTool.
func (c *sdkCustomToolCallbackServiceClient) CallCustomTool(ctx context.Context, req *connect.Request[v1.CallCustomToolRequest]) (*connect.Response[v1.CallCustomToolResponse], error) {
	return c.callCustomTool.CallUnary(ctx, req)
}

// SdkCustomToolCallbackServiceHandler is an implementation of the
// sdk.v1.SdkCustomToolCallbackService service.
type SdkCustomToolCallbackServiceHandler interface {
	CallCustomTool(context.Context, *connect.Request[v1.CallCustomToolRequest]) (*connect.Response[v1.CallCustomToolResponse], error)
}

// NewSdkCustomToolCallbackServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSdkCustomToolCallbackServiceHandler(svc SdkCustomToolCallbackServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sdkCustomToolCallbackServiceMethods := v1.File_sdk_v1_sdk_custom_tool_callback_service_proto.Services().ByName("SdkCustomToolCallbackService").Methods()
	sdkCustomToolCallbackServiceCallCustomToolHandler := connect.NewUnaryHandler(
		SdkCustomToolCallbackServiceCallCustomToolProcedure,
		svc.CallCustomTool,
		connect.WithSchema(sdkCustomToolCallbackServiceMethods.ByName("CallCustomTool")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sdk.v1.SdkCustomToolCallbackService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SdkCustomToolCallbackServiceCallCustomToolProcedure:
			sdkCustomToolCallbackServiceCallCustomToolHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSdkCustomToolCallbackServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSdkCustomToolCallbackServiceHandler struct{}

func (UnimplementedSdkCustomToolCallbackServiceHandler) CallCustomTool(context.Context, *connect.Request[v1.CallCustomToolRequest]) (*connect.Response[v1.CallCustomToolResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkCustomToolCallbackService.CallCustomTool is not implemented"))
}
