// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sdk/v1/sdk_store_callback_service.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/orvice/butter-box/pkg/proto/sdk/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SdkStoreCallbackServiceName is the fully-qualified name of the SdkStoreCallbackService service.
	SdkStoreCallbackServiceName = "sdk.v1.SdkStoreCallbackService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SdkStoreCallbackServiceCallStoreProcedure is the fully-qualified name of the
	// SdkStoreCallbackService's CallStore RPC.
	SdkStoreCallbackServiceCallStoreProcedure = "/sdk.v1.SdkStoreCallbackService/CallStore"
)

// SdkStoreCallbackServiceClient is a client for the sdk.v1.SdkStoreCallbackService service.
type SdkStoreCallbackServiceClient interface {
	CallStore(context.Context, *connect.Request[v1.CallStoreRequest]) (*connect.Response[v1.CallStoreResponse], error)
}

// NewSdkStoreCallbackServiceClient constructs a client for the sdk.v1.SdkStoreCallbackService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSdkStoreCallbackServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SdkStoreCallbackServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sdkStoreCallbackServiceMethods := v1.File_sdk_v1_sdk_store_callback_service_proto.Services().ByName("SdkStoreCallbackService").Methods()
	return &sdkStoreCallbackServiceClient{
		callStore: connect.NewClient[v1.CallStoreRequest, v1.CallStoreResponse](
			httpClient,
			baseURL+SdkStoreCallbackServiceCallStoreProcedure,
			connect.WithSchema(sdkStoreCallbackServiceMethods.ByName("CallStore")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sdkStoreCallbackServiceClient implements SdkStoreCallbackServiceClient.
type sdkStoreCallbackServiceClient struct {
	callStore *connect.Client[v1.CallStoreRequest, v1.CallStoreResponse]
}

// CallStore calls sdk.v1.SdkStoreCallbackService.CallStore.
func (c *sdkStoreCallbackServiceClient) CallStore(ctx context.Context, req *connect.Request[v1.CallStoreRequest]) (*connect.Response[v1.CallStoreResponse], error) {
	return c.callStore.CallUnary(ctx, req)
}

// SdkStoreCallbackServiceHandler is an implementation of the sdk.v1.SdkStoreCallbackService
// service.
type SdkStoreCallbackServiceHandler interface {
	CallStore(context.Context, *connect.Request[v1.CallStoreRequest]) (*connect.Response[v1.CallStoreResponse], error)
}

// NewSdkStoreCallbackServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSdkStoreCallbackServiceHandler(svc SdkStoreCallbackServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sdkStoreCallbackServiceMethods := v1.File_sdk_v1_sdk_store_callback_service_proto.Services().ByName("SdkStoreCallbackService").Methods()
	sdkStoreCallbackServiceCallStoreHandler := connect.NewUnaryHandler(
		SdkStoreCallbackServiceCallStoreProcedure,
		svc.CallStore,
		connect.WithSchema(sdkStoreCallbackServiceMethods.ByName("CallStore")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sdk.v1.SdkStoreCallbackService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SdkStoreCallbackServiceCallStoreProcedure:
			sdkStoreCallbackServiceCallStoreHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSdkStoreCallbackServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSdkStoreCallbackServiceHandler struct{}

func (UnimplementedSdkStoreCallbackServiceHandler) CallStore(context.Context, *connect.Request[v1.CallStoreRequest]) (*connect.Response[v1.CallStoreResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkStoreCallbackService.CallStore is not implemented"))
}
