// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sdk/v1/sdk_agent_service.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/orvice/butter-box/pkg/proto/sdk/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SdkAgentServiceName is the fully-qualified name of the SdkAgentService service.
	SdkAgentServiceName = "sdk.v1.SdkAgentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SdkAgentServiceCreateAgentProcedure is the fully-qualified name of the SdkAgentService's
	// CreateAgent RPC.
	SdkAgentServiceCreateAgentProcedure = "/sdk.v1.SdkAgentService/CreateAgent"
	// SdkAgentServiceResumeAgentProcedure is the fully-qualified name of the SdkAgentService's
	// ResumeAgent RPC.
	SdkAgentServiceResumeAgentProcedure = "/sdk.v1.SdkAgentService/ResumeAgent"
	// SdkAgentServiceReloadAgentProcedure is the fully-qualified name of the SdkAgentService's
	// ReloadAgent RPC.
	SdkAgentServiceReloadAgentProcedure = "/sdk.v1.SdkAgentService/ReloadAgent"
	// SdkAgentServiceCloseAgentProcedure is the fully-qualified name of the SdkAgentService's
	// CloseAgent RPC.
	SdkAgentServiceCloseAgentProcedure = "/sdk.v1.SdkAgentService/CloseAgent"
	// SdkAgentServiceSendProcedure is the fully-qualified name of the SdkAgentService's Send RPC.
	SdkAgentServiceSendProcedure = "/sdk.v1.SdkAgentService/Send"
	// SdkAgentServiceWaitLiveRunProcedure is the fully-qualified name of the SdkAgentService's
	// WaitLiveRun RPC.
	SdkAgentServiceWaitLiveRunProcedure = "/sdk.v1.SdkAgentService/WaitLiveRun"
	// SdkAgentServiceGetRunProcedure is the fully-qualified name of the SdkAgentService's GetRun RPC.
	SdkAgentServiceGetRunProcedure = "/sdk.v1.SdkAgentService/GetRun"
	// SdkAgentServiceListRunsProcedure is the fully-qualified name of the SdkAgentService's ListRuns
	// RPC.
	SdkAgentServiceListRunsProcedure = "/sdk.v1.SdkAgentService/ListRuns"
	// SdkAgentServiceGetRunConversationProcedure is the fully-qualified name of the SdkAgentService's
	// GetRunConversation RPC.
	SdkAgentServiceGetRunConversationProcedure = "/sdk.v1.SdkAgentService/GetRunConversation"
	// SdkAgentServiceObserveRunProcedure is the fully-qualified name of the SdkAgentService's
	// ObserveRun RPC.
	SdkAgentServiceObserveRunProcedure = "/sdk.v1.SdkAgentService/ObserveRun"
	// SdkAgentServiceCancelRunProcedure is the fully-qualified name of the SdkAgentService's CancelRun
	// RPC.
	SdkAgentServiceCancelRunProcedure = "/sdk.v1.SdkAgentService/CancelRun"
	// SdkAgentServiceGetAgentProcedure is the fully-qualified name of the SdkAgentService's GetAgent
	// RPC.
	SdkAgentServiceGetAgentProcedure = "/sdk.v1.SdkAgentService/GetAgent"
	// SdkAgentServiceListAgentsProcedure is the fully-qualified name of the SdkAgentService's
	// ListAgents RPC.
	SdkAgentServiceListAgentsProcedure = "/sdk.v1.SdkAgentService/ListAgents"
	// SdkAgentServiceArchiveAgentProcedure is the fully-qualified name of the SdkAgentService's
	// ArchiveAgent RPC.
	SdkAgentServiceArchiveAgentProcedure = "/sdk.v1.SdkAgentService/ArchiveAgent"
	// SdkAgentServiceUnarchiveAgentProcedure is the fully-qualified name of the SdkAgentService's
	// UnarchiveAgent RPC.
	SdkAgentServiceUnarchiveAgentProcedure = "/sdk.v1.SdkAgentService/UnarchiveAgent"
	// SdkAgentServiceDeleteAgentProcedure is the fully-qualified name of the SdkAgentService's
	// DeleteAgent RPC.
	SdkAgentServiceDeleteAgentProcedure = "/sdk.v1.SdkAgentService/DeleteAgent"
	// SdkAgentServiceListAgentMessagesProcedure is the fully-qualified name of the SdkAgentService's
	// ListAgentMessages RPC.
	SdkAgentServiceListAgentMessagesProcedure = "/sdk.v1.SdkAgentService/ListAgentMessages"
	// SdkAgentServiceListArtifactsProcedure is the fully-qualified name of the SdkAgentService's
	// ListArtifacts RPC.
	SdkAgentServiceListArtifactsProcedure = "/sdk.v1.SdkAgentService/ListArtifacts"
	// SdkAgentServiceDownloadArtifactProcedure is the fully-qualified name of the SdkAgentService's
	// DownloadArtifact RPC.
	SdkAgentServiceDownloadArtifactProcedure = "/sdk.v1.SdkAgentService/DownloadArtifact"
	// SdkAgentServiceGetUsageProcedure is the fully-qualified name of the SdkAgentService's GetUsage
	// RPC.
	SdkAgentServiceGetUsageProcedure = "/sdk.v1.SdkAgentService/GetUsage"
)

// SdkAgentServiceClient is a client for the sdk.v1.SdkAgentService service.
type SdkAgentServiceClient interface {
	// Create a new local or cloud agent.
	CreateAgent(context.Context, *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error)
	// Re-attach to an existing agent and apply updated options.
	ResumeAgent(context.Context, *connect.Request[v1.ResumeAgentRequest]) (*connect.Response[v1.ResumeAgentResponse], error)
	// Reload an agent's durable state from its store without sending a message.
	ReloadAgent(context.Context, *connect.Request[v1.ReloadAgentRequest]) (*connect.Response[v1.ReloadAgentResponse], error)
	// Release local resources for an agent. Does not delete durable cloud state.
	CloseAgent(context.Context, *connect.Request[v1.CloseAgentRequest]) (*connect.Response[v1.CloseAgentResponse], error)
	// Send a user message and stream run events until the run completes.
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	Send(context.Context, *connect.Request[v1.SendRequest]) (*connect.ServerStreamForClient[v1.RunStreamMessage], error)
	// Block until a live run reaches a terminal status and return its result.
	WaitLiveRun(context.Context, *connect.Request[v1.WaitLiveRunRequest]) (*connect.Response[v1.WaitLiveRunResponse], error)
	// Fetch a point-in-time snapshot of a run.
	GetRun(context.Context, *connect.Request[v1.GetRunRequest]) (*connect.Response[v1.GetRunResponse], error)
	// List runs for an agent, newest first unless otherwise noted by the bridge.
	ListRuns(context.Context, *connect.Request[v1.ListRunsRequest]) (*connect.Response[v1.ListRunsResponse], error)
	// Fetch the conversation JSON associated with a run.
	GetRunConversation(context.Context, *connect.Request[v1.GetRunConversationRequest]) (*connect.Response[v1.GetRunConversationResponse], error)
	// Subscribe to durable run events, optionally resuming after a prior offset.
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	ObserveRun(context.Context, *connect.Request[v1.ObserveRunRequest]) (*connect.ServerStreamForClient[v1.RunStreamMessage], error)
	// Request cancellation of an in-flight run.
	CancelRun(context.Context, *connect.Request[v1.CancelRunRequest]) (*connect.Response[v1.CancelRunResponse], error)
	// Fetch metadata for a single agent.
	GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.GetAgentResponse], error)
	// List agents visible to the caller.
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	// Archive an agent so it no longer appears in default listings.
	ArchiveAgent(context.Context, *connect.Request[v1.ArchiveAgentRequest]) (*connect.Response[v1.ArchiveAgentResponse], error)
	// Restore an archived agent.
	UnarchiveAgent(context.Context, *connect.Request[v1.UnarchiveAgentRequest]) (*connect.Response[v1.UnarchiveAgentResponse], error)
	// Permanently delete an agent and its durable data.
	DeleteAgent(context.Context, *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[v1.DeleteAgentResponse], error)
	// List messages recorded for an agent.
	ListAgentMessages(context.Context, *connect.Request[v1.ListAgentMessagesRequest]) (*connect.Response[v1.ListAgentMessagesResponse], error)
	// List artifacts produced by a cloud agent.
	ListArtifacts(context.Context, *connect.Request[v1.ListArtifactsRequest]) (*connect.Response[v1.ListArtifactsResponse], error)
	// Download an artifact as a stream of bytes.
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	DownloadArtifact(context.Context, *connect.Request[v1.DownloadArtifactRequest]) (*connect.ServerStreamForClient[v1.DownloadArtifactChunk], error)
	// Billed token usage and dollar cost for an agent's runs.
	// Cloud agents only; local agents fail with a cloud-only / unavailable error.
	GetUsage(context.Context, *connect.Request[v1.GetUsageRequest]) (*connect.Response[v1.GetUsageResponse], error)
}

// NewSdkAgentServiceClient constructs a client for the sdk.v1.SdkAgentService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSdkAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SdkAgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sdkAgentServiceMethods := v1.File_sdk_v1_sdk_agent_service_proto.Services().ByName("SdkAgentService").Methods()
	return &sdkAgentServiceClient{
		createAgent: connect.NewClient[v1.CreateAgentRequest, v1.CreateAgentResponse](
			httpClient,
			baseURL+SdkAgentServiceCreateAgentProcedure,
			connect.WithSchema(sdkAgentServiceMethods.ByName("CreateAgent")),
			connect.WithClientOptions(opts...),
		),
		resumeAgent: connect.NewClient[v1.ResumeAgentRequest, v1.ResumeAgentResponse](
			httpClient,
			baseURL+SdkAgentServiceResumeAgentProcedure,
			connect.WithSchema(sdkAgentServiceMethods.ByName("ResumeAgent")),
			connect.WithClientOptions(opts...),
		),
		reloadAgent: connect.NewClient[v1.ReloadAgentRequest, v1.ReloadAgentResponse](
			httpClient,
			baseURL+SdkAgentServiceReloadAgentProcedure,
			connect.WithSchema(sdkAgentServiceMethods.ByName("ReloadAgent")),
			connect.WithClientOptions(opts...),
		),
		closeAgent: connect.NewClient[v1.CloseAgentRequest, v1.CloseAgentResponse](
			httpClient,
			baseURL+SdkAgentServiceCloseAgentProcedure,
			connect.WithSchema(sdkAgentServiceMethods.ByName("CloseAgent")),
			connect.WithClientOptions(opts...),
		),
		send: connect.NewClient[v1.SendRequest, v1.RunStreamMessage](
			httpClient,
			baseURL+SdkAgentServiceSendProcedure,
			connect.WithSchema(sdkAgentServiceMethods.ByName("Send")),
			connect.WithClientOptions(opts...),
		),
		waitLiveRun: connect.NewClient[v1.WaitLiveRunRequest, v1.WaitLiveRunResponse](
			httpClient,
			baseURL+SdkAgentServiceWaitLiveRunProcedure,
			connect.WithSchema(sdkAgentServiceMethods.ByName("WaitLiveRun")),
			connect.WithClientOptions(opts...),
		),
		getRun: connect.NewClient[v1.GetRunRequest, v1.GetRunResponse](
			httpClient,
			baseURL+SdkAgentServiceGetRunProcedure,
			connect.WithSchema(sdkAgentServiceMethods.ByName("GetRun")),
			connect.WithClientOptions(opts...),
		),
		listRuns: connect.NewClient[v1.ListRunsRequest, v1.ListRunsResponse](
			httpClient,
			baseURL+SdkAgentServiceListRunsProcedure,
			connect.WithSchema(sdkAgentServiceMethods.ByName("ListRuns")),
			connect.WithClientOptions(opts...),
		),
		getRunConversation: connect.NewClient[v1.GetRunConversationRequest, v1.GetRunConversationResponse](
			httpClient,
			baseURL+SdkAgentServiceGetRunConversationProcedure,
			connect.WithSchema(sdkAgentServiceMethods.ByName("GetRunConversation")),
			connect.WithClientOptions(opts...),
		),
		observeRun: connect.NewClient[v1.ObserveRunRequest, v1.RunStreamMessage](
			httpClient,
			baseURL+SdkAgentServiceObserveRunProcedure,
			connect.WithSchema(sdkAgentServiceMethods.ByName("ObserveRun")),
			connect.WithClientOptions(opts...),
		),
		cancelRun: connect.NewClient[v1.CancelRunRequest, v1.CancelRunResponse](
			httpClient,
			baseURL+SdkAgentServiceCancelRunProcedure,
			connect.WithSchema(sdkAgentServiceMethods.ByName("CancelRun")),
			connect.WithClientOptions(opts...),
		),
		getAgent: connect.NewClient[v1.GetAgentRequest, v1.GetAgentResponse](
			httpClient,
			baseURL+SdkAgentServiceGetAgentProcedure,
			connect.WithSchema(sdkAgentServiceMethods.ByName("GetAgent")),
			connect.WithClientOptions(opts...),
		),
		listAgents: connect.NewClient[v1.ListAgentsRequest, v1.ListAgentsResponse](
			httpClient,
			baseURL+SdkAgentServiceListAgentsProcedure,
			connect.WithSchema(sdkAgentServiceMethods.ByName("ListAgents")),
			connect.WithClientOptions(opts...),
		),
		archiveAgent: connect.NewClient[v1.ArchiveAgentRequest, v1.ArchiveAgentResponse](
			httpClient,
			baseURL+SdkAgentServiceArchiveAgentProcedure,
			connect.WithSchema(sdkAgentServiceMethods.ByName("ArchiveAgent")),
			connect.WithClientOptions(opts...),
		),
		unarchiveAgent: connect.NewClient[v1.UnarchiveAgentRequest, v1.UnarchiveAgentResponse](
			httpClient,
			baseURL+SdkAgentServiceUnarchiveAgentProcedure,
			connect.WithSchema(sdkAgentServiceMethods.ByName("UnarchiveAgent")),
			connect.WithClientOptions(opts...),
		),
		deleteAgent: connect.NewClient[v1.DeleteAgentRequest, v1.DeleteAgentResponse](
			httpClient,
			baseURL+SdkAgentServiceDeleteAgentProcedure,
			connect.WithSchema(sdkAgentServiceMethods.ByName("DeleteAgent")),
			connect.WithClientOptions(opts...),
		),
		listAgentMessages: connect.NewClient[v1.ListAgentMessagesRequest, v1.ListAgentMessagesResponse](
			httpClient,
			baseURL+SdkAgentServiceListAgentMessagesProcedure,
			connect.WithSchema(sdkAgentServiceMethods.ByName("ListAgentMessages")),
			connect.WithClientOptions(opts...),
		),
		listArtifacts: connect.NewClient[v1.ListArtifactsRequest, v1.ListArtifactsResponse](
			httpClient,
			baseURL+SdkAgentServiceListArtifactsProcedure,
			connect.WithSchema(sdkAgentServiceMethods.ByName("ListArtifacts")),
			connect.WithClientOptions(opts...),
		),
		downloadArtifact: connect.NewClient[v1.DownloadArtifactRequest, v1.DownloadArtifactChunk](
			httpClient,
			baseURL+SdkAgentServiceDownloadArtifactProcedure,
			connect.WithSchema(sdkAgentServiceMethods.ByName("DownloadArtifact")),
			connect.WithClientOptions(opts...),
		),
		getUsage: connect.NewClient[v1.GetUsageRequest, v1.GetUsageResponse](
			httpClient,
			baseURL+SdkAgentServiceGetUsageProcedure,
			connect.WithSchema(sdkAgentServiceMethods.ByName("GetUsage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sdkAgentServiceClient implements SdkAgentServiceClient.
type sdkAgentServiceClient struct {
	createAgent        *connect.Client[v1.CreateAgentRequest, v1.CreateAgentResponse]
	resumeAgent        *connect.Client[v1.ResumeAgentRequest, v1.ResumeAgentResponse]
	reloadAgent        *connect.Client[v1.ReloadAgentRequest, v1.ReloadAgentResponse]
	closeAgent         *connect.Client[v1.CloseAgentRequest, v1.CloseAgentResponse]
	send               *connect.Client[v1.SendRequest, v1.RunStreamMessage]
	waitLiveRun        *connect.Client[v1.WaitLiveRunRequest, v1.WaitLiveRunResponse]
	getRun             *connect.Client[v1.GetRunRequest, v1.GetRunResponse]
	listRuns           *connect.Client[v1.ListRunsRequest, v1.ListRunsResponse]
	getRunConversation *connect.Client[v1.GetRunConversationRequest, v1.GetRunConversationResponse]
	observeRun         *connect.Client[v1.ObserveRunRequest, v1.RunStreamMessage]
	cancelRun          *connect.Client[v1.CancelRunRequest, v1.CancelRunResponse]
	getAgent           *connect.Client[v1.GetAgentRequest, v1.GetAgentResponse]
	listAgents         *connect.Client[v1.ListAgentsRequest, v1.ListAgentsResponse]
	archiveAgent       *connect.Client[v1.ArchiveAgentRequest, v1.ArchiveAgentResponse]
	unarchiveAgent     *connect.Client[v1.UnarchiveAgentRequest, v1.UnarchiveAgentResponse]
	deleteAgent        *connect.Client[v1.DeleteAgentRequest, v1.DeleteAgentResponse]
	listAgentMessages  *connect.Client[v1.ListAgentMessagesRequest, v1.ListAgentMessagesResponse]
	listArtifacts      *connect.Client[v1.ListArtifactsRequest, v1.ListArtifactsResponse]
	downloadArtifact   *connect.Client[v1.DownloadArtifactRequest, v1.DownloadArtifactChunk]
	getUsage           *connect.Client[v1.GetUsageRequest, v1.GetUsageResponse]
}

// CreateAgent calls sdk.v1.SdkAgentService.CreateAgent.
func (c *sdkAgentServiceClient) CreateAgent(ctx context.Context, req *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error) {
	return c.createAgent.CallUnary(ctx, req)
}

// ResumeAgent calls sdk.v1.SdkAgentService.ResumeAgent.
func (c *sdkAgentServiceClient) ResumeAgent(ctx context.Context, req *connect.Request[v1.ResumeAgentRequest]) (*connect.Response[v1.ResumeAgentResponse], error) {
	return c.resumeAgent.CallUnary(ctx, req)
}

// ReloadAgent calls sdk.v1.SdkAgentService.ReloadAgent.
func (c *sdkAgentServiceClient) ReloadAgent(ctx context.Context, req *connect.Request[v1.ReloadAgentRequest]) (*connect.Response[v1.ReloadAgentResponse], error) {
	return c.reloadAgent.CallUnary(ctx, req)
}

// CloseAgent calls sdk.v1.SdkAgentService.CloseAgent.
func (c *sdkAgentServiceClient) CloseAgent(ctx context.Context, req *connect.Request[v1.CloseAgentRequest]) (*connect.Response[v1.CloseAgentResponse], error) {
	return c.closeAgent.CallUnary(ctx, req)
}

// Send calls sdk.v1.SdkAgentService.Send.
func (c *sdkAgentServiceClient) Send(ctx context.Context, req *connect.Request[v1.SendRequest]) (*connect.ServerStreamForClient[v1.RunStreamMessage], error) {
	return c.send.CallServerStream(ctx, req)
}

// WaitLiveRun calls sdk.v1.SdkAgentService.WaitLiveRun.
func (c *sdkAgentServiceClient) WaitLiveRun(ctx context.Context, req *connect.Request[v1.WaitLiveRunRequest]) (*connect.Response[v1.WaitLiveRunResponse], error) {
	return c.waitLiveRun.CallUnary(ctx, req)
}

// GetRun calls sdk.v1.SdkAgentService.GetRun.
func (c *sdkAgentServiceClient) GetRun(ctx context.Context, req *connect.Request[v1.GetRunRequest]) (*connect.Response[v1.GetRunResponse], error) {
	return c.getRun.CallUnary(ctx, req)
}

// ListRuns calls sdk.v1.SdkAgentService.ListRuns.
func (c *sdkAgentServiceClient) ListRuns(ctx context.Context, req *connect.Request[v1.ListRunsRequest]) (*connect.Response[v1.ListRunsResponse], error) {
	return c.listRuns.CallUnary(ctx, req)
}

// GetRunConversation calls sdk.v1.SdkAgentService.GetRunConversation.
func (c *sdkAgentServiceClient) GetRunConversation(ctx context.Context, req *connect.Request[v1.GetRunConversationRequest]) (*connect.Response[v1.GetRunConversationResponse], error) {
	return c.getRunConversation.CallUnary(ctx, req)
}

// ObserveRun calls sdk.v1.SdkAgentService.ObserveRun.
func (c *sdkAgentServiceClient) ObserveRun(ctx context.Context, req *connect.Request[v1.ObserveRunRequest]) (*connect.ServerStreamForClient[v1.RunStreamMessage], error) {
	return c.observeRun.CallServerStream(ctx, req)
}

// CancelRun calls sdk.v1.SdkAgentService.CancelRun.
func (c *sdkAgentServiceClient) CancelRun(ctx context.Context, req *connect.Request[v1.CancelRunRequest]) (*connect.Response[v1.CancelRunResponse], error) {
	return c.cancelRun.CallUnary(ctx, req)
}

// GetAgent calls sdk.v1.SdkAgentService.GetAgent.
func (c *sdkAgentServiceClient) GetAgent(ctx context.Context, req *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.GetAgentResponse], error) {
	return c.getAgent.CallUnary(ctx, req)
}

// ListAgents calls sdk.v1.SdkAgentService.ListAgents.
func (c *sdkAgentServiceClient) ListAgents(ctx context.Context, req *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return c.listAgents.CallUnary(ctx, req)
}

// ArchiveAgent calls sdk.v1.SdkAgentService.ArchiveAgent.
func (c *sdkAgentServiceClient) ArchiveAgent(ctx context.Context, req *connect.Request[v1.ArchiveAgentRequest]) (*connect.Response[v1.ArchiveAgentResponse], error) {
	return c.archiveAgent.CallUnary(ctx, req)
}

// UnarchiveAgent calls sdk.v1.SdkAgentService.UnarchiveAgent.
func (c *sdkAgentServiceClient) UnarchiveAgent(ctx context.Context, req *connect.Request[v1.UnarchiveAgentRequest]) (*connect.Response[v1.UnarchiveAgentResponse], error) {
	return c.unarchiveAgent.CallUnary(ctx, req)
}

// DeleteAgent calls sdk.v1.SdkAgentService.DeleteAgent.
func (c *sdkAgentServiceClient) DeleteAgent(ctx context.Context, req *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[v1.DeleteAgentResponse], error) {
	return c.deleteAgent.CallUnary(ctx, req)
}

// ListAgentMessages calls sdk.v1.SdkAgentService.ListAgentMessages.
func (c *sdkAgentServiceClient) ListAgentMessages(ctx context.Context, req *connect.Request[v1.ListAgentMessagesRequest]) (*connect.Response[v1.ListAgentMessagesResponse], error) {
	return c.listAgentMessages.CallUnary(ctx, req)
}

// ListArtifacts calls sdk.v1.SdkAgentService.ListArtifacts.
func (c *sdkAgentServiceClient) ListArtifacts(ctx context.Context, req *connect.Request[v1.ListArtifactsRequest]) (*connect.Response[v1.ListArtifactsResponse], error) {
	return c.listArtifacts.CallUnary(ctx, req)
}

// DownloadArtifact calls sdk.v1.SdkAgentService.DownloadArtifact.
func (c *sdkAgentServiceClient) DownloadArtifact(ctx context.Context, req *connect.Request[v1.DownloadArtifactRequest]) (*connect.ServerStreamForClient[v1.DownloadArtifactChunk], error) {
	return c.downloadArtifact.CallServerStream(ctx, req)
}

// GetUsage calls sdk.v1.SdkAgentService.GetUsage.
func (c *sdkAgentServiceClient) GetUsage(ctx context.Context, req *connect.Request[v1.GetUsageRequest]) (*connect.Response[v1.GetUsageResponse], error) {
	return c.getUsage.CallUnary(ctx, req)
}

// SdkAgentServiceHandler is an implementation of the sdk.v1.SdkAgentService service.
type SdkAgentServiceHandler interface {
	// Create a new local or cloud agent.
	CreateAgent(context.Context, *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error)
	// Re-attach to an existing agent and apply updated options.
	ResumeAgent(context.Context, *connect.Request[v1.ResumeAgentRequest]) (*connect.Response[v1.ResumeAgentResponse], error)
	// Reload an agent's durable state from its store without sending a message.
	ReloadAgent(context.Context, *connect.Request[v1.ReloadAgentRequest]) (*connect.Response[v1.ReloadAgentResponse], error)
	// Release local resources for an agent. Does not delete durable cloud state.
	CloseAgent(context.Context, *connect.Request[v1.CloseAgentRequest]) (*connect.Response[v1.CloseAgentResponse], error)
	// Send a user message and stream run events until the run completes.
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	Send(context.Context, *connect.Request[v1.SendRequest], *connect.ServerStream[v1.RunStreamMessage]) error
	// Block until a live run reaches a terminal status and return its result.
	WaitLiveRun(context.Context, *connect.Request[v1.WaitLiveRunRequest]) (*connect.Response[v1.WaitLiveRunResponse], error)
	// Fetch a point-in-time snapshot of a run.
	GetRun(context.Context, *connect.Request[v1.GetRunRequest]) (*connect.Response[v1.GetRunResponse], error)
	// List runs for an agent, newest first unless otherwise noted by the bridge.
	ListRuns(context.Context, *connect.Request[v1.ListRunsRequest]) (*connect.Response[v1.ListRunsResponse], error)
	// Fetch the conversation JSON associated with a run.
	GetRunConversation(context.Context, *connect.Request[v1.GetRunConversationRequest]) (*connect.Response[v1.GetRunConversationResponse], error)
	// Subscribe to durable run events, optionally resuming after a prior offset.
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	ObserveRun(context.Context, *connect.Request[v1.ObserveRunRequest], *connect.ServerStream[v1.RunStreamMessage]) error
	// Request cancellation of an in-flight run.
	CancelRun(context.Context, *connect.Request[v1.CancelRunRequest]) (*connect.Response[v1.CancelRunResponse], error)
	// Fetch metadata for a single agent.
	GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.GetAgentResponse], error)
	// List agents visible to the caller.
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	// Archive an agent so it no longer appears in default listings.
	ArchiveAgent(context.Context, *connect.Request[v1.ArchiveAgentRequest]) (*connect.Response[v1.ArchiveAgentResponse], error)
	// Restore an archived agent.
	UnarchiveAgent(context.Context, *connect.Request[v1.UnarchiveAgentRequest]) (*connect.Response[v1.UnarchiveAgentResponse], error)
	// Permanently delete an agent and its durable data.
	DeleteAgent(context.Context, *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[v1.DeleteAgentResponse], error)
	// List messages recorded for an agent.
	ListAgentMessages(context.Context, *connect.Request[v1.ListAgentMessagesRequest]) (*connect.Response[v1.ListAgentMessagesResponse], error)
	// List artifacts produced by a cloud agent.
	ListArtifacts(context.Context, *connect.Request[v1.ListArtifactsRequest]) (*connect.Response[v1.ListArtifactsResponse], error)
	// Download an artifact as a stream of bytes.
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	DownloadArtifact(context.Context, *connect.Request[v1.DownloadArtifactRequest], *connect.ServerStream[v1.DownloadArtifactChunk]) error
	// Billed token usage and dollar cost for an agent's runs.
	// Cloud agents only; local agents fail with a cloud-only / unavailable error.
	GetUsage(context.Context, *connect.Request[v1.GetUsageRequest]) (*connect.Response[v1.GetUsageResponse], error)
}

// NewSdkAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSdkAgentServiceHandler(svc SdkAgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sdkAgentServiceMethods := v1.File_sdk_v1_sdk_agent_service_proto.Services().ByName("SdkAgentService").Methods()
	sdkAgentServiceCreateAgentHandler := connect.NewUnaryHandler(
		SdkAgentServiceCreateAgentProcedure,
		svc.CreateAgent,
		connect.WithSchema(sdkAgentServiceMethods.ByName("CreateAgent")),
		connect.WithHandlerOptions(opts...),
	)
	sdkAgentServiceResumeAgentHandler := connect.NewUnaryHandler(
		SdkAgentServiceResumeAgentProcedure,
		svc.ResumeAgent,
		connect.WithSchema(sdkAgentServiceMethods.ByName("ResumeAgent")),
		connect.WithHandlerOptions(opts...),
	)
	sdkAgentServiceReloadAgentHandler := connect.NewUnaryHandler(
		SdkAgentServiceReloadAgentProcedure,
		svc.ReloadAgent,
		connect.WithSchema(sdkAgentServiceMethods.ByName("ReloadAgent")),
		connect.WithHandlerOptions(opts...),
	)
	sdkAgentServiceCloseAgentHandler := connect.NewUnaryHandler(
		SdkAgentServiceCloseAgentProcedure,
		svc.CloseAgent,
		connect.WithSchema(sdkAgentServiceMethods.ByName("CloseAgent")),
		connect.WithHandlerOptions(opts...),
	)
	sdkAgentServiceSendHandler := connect.NewServerStreamHandler(
		SdkAgentServiceSendProcedure,
		svc.Send,
		connect.WithSchema(sdkAgentServiceMethods.ByName("Send")),
		connect.WithHandlerOptions(opts...),
	)
	sdkAgentServiceWaitLiveRunHandler := connect.NewUnaryHandler(
		SdkAgentServiceWaitLiveRunProcedure,
		svc.WaitLiveRun,
		connect.WithSchema(sdkAgentServiceMethods.ByName("WaitLiveRun")),
		connect.WithHandlerOptions(opts...),
	)
	sdkAgentServiceGetRunHandler := connect.NewUnaryHandler(
		SdkAgentServiceGetRunProcedure,
		svc.GetRun,
		connect.WithSchema(sdkAgentServiceMethods.ByName("GetRun")),
		connect.WithHandlerOptions(opts...),
	)
	sdkAgentServiceListRunsHandler := connect.NewUnaryHandler(
		SdkAgentServiceListRunsProcedure,
		svc.ListRuns,
		connect.WithSchema(sdkAgentServiceMethods.ByName("ListRuns")),
		connect.WithHandlerOptions(opts...),
	)
	sdkAgentServiceGetRunConversationHandler := connect.NewUnaryHandler(
		SdkAgentServiceGetRunConversationProcedure,
		svc.GetRunConversation,
		connect.WithSchema(sdkAgentServiceMethods.ByName("GetRunConversation")),
		connect.WithHandlerOptions(opts...),
	)
	sdkAgentServiceObserveRunHandler := connect.NewServerStreamHandler(
		SdkAgentServiceObserveRunProcedure,
		svc.ObserveRun,
		connect.WithSchema(sdkAgentServiceMethods.ByName("ObserveRun")),
		connect.WithHandlerOptions(opts...),
	)
	sdkAgentServiceCancelRunHandler := connect.NewUnaryHandler(
		SdkAgentServiceCancelRunProcedure,
		svc.CancelRun,
		connect.WithSchema(sdkAgentServiceMethods.ByName("CancelRun")),
		connect.WithHandlerOptions(opts...),
	)
	sdkAgentServiceGetAgentHandler := connect.NewUnaryHandler(
		SdkAgentServiceGetAgentProcedure,
		svc.GetAgent,
		connect.WithSchema(sdkAgentServiceMethods.ByName("GetAgent")),
		connect.WithHandlerOptions(opts...),
	)
	sdkAgentServiceListAgentsHandler := connect.NewUnaryHandler(
		SdkAgentServiceListAgentsProcedure,
		svc.ListAgents,
		connect.WithSchema(sdkAgentServiceMethods.ByName("ListAgents")),
		connect.WithHandlerOptions(opts...),
	)
	sdkAgentServiceArchiveAgentHandler := connect.NewUnaryHandler(
		SdkAgentServiceArchiveAgentProcedure,
		svc.ArchiveAgent,
		connect.WithSchema(sdkAgentServiceMethods.ByName("ArchiveAgent")),
		connect.WithHandlerOptions(opts...),
	)
	sdkAgentServiceUnarchiveAgentHandler := connect.NewUnaryHandler(
		SdkAgentServiceUnarchiveAgentProcedure,
		svc.UnarchiveAgent,
		connect.WithSchema(sdkAgentServiceMethods.ByName("UnarchiveAgent")),
		connect.WithHandlerOptions(opts...),
	)
	sdkAgentServiceDeleteAgentHandler := connect.NewUnaryHandler(
		SdkAgentServiceDeleteAgentProcedure,
		svc.DeleteAgent,
		connect.WithSchema(sdkAgentServiceMethods.ByName("DeleteAgent")),
		connect.WithHandlerOptions(opts...),
	)
	sdkAgentServiceListAgentMessagesHandler := connect.NewUnaryHandler(
		SdkAgentServiceListAgentMessagesProcedure,
		svc.ListAgentMessages,
		connect.WithSchema(sdkAgentServiceMethods.ByName("ListAgentMessages")),
		connect.WithHandlerOptions(opts...),
	)
	sdkAgentServiceListArtifactsHandler := connect.NewUnaryHandler(
		SdkAgentServiceListArtifactsProcedure,
		svc.ListArtifacts,
		connect.WithSchema(sdkAgentServiceMethods.ByName("ListArtifacts")),
		connect.WithHandlerOptions(opts...),
	)
	sdkAgentServiceDownloadArtifactHandler := connect.NewServerStreamHandler(
		SdkAgentServiceDownloadArtifactProcedure,
		svc.DownloadArtifact,
		connect.WithSchema(sdkAgentServiceMethods.ByName("DownloadArtifact")),
		connect.WithHandlerOptions(opts...),
	)
	sdkAgentServiceGetUsageHandler := connect.NewUnaryHandler(
		SdkAgentServiceGetUsageProcedure,
		svc.GetUsage,
		connect.WithSchema(sdkAgentServiceMethods.ByName("GetUsage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sdk.v1.SdkAgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SdkAgentServiceCreateAgentProcedure:
			sdkAgentServiceCreateAgentHandler.ServeHTTP(w, r)
		case SdkAgentServiceResumeAgentProcedure:
			sdkAgentServiceResumeAgentHandler.ServeHTTP(w, r)
		case SdkAgentServiceReloadAgentProcedure:
			sdkAgentServiceReloadAgentHandler.ServeHTTP(w, r)
		case SdkAgentServiceCloseAgentProcedure:
			sdkAgentServiceCloseAgentHandler.ServeHTTP(w, r)
		case SdkAgentServiceSendProcedure:
			sdkAgentServiceSendHandler.ServeHTTP(w, r)
		case SdkAgentServiceWaitLiveRunProcedure:
			sdkAgentServiceWaitLiveRunHandler.ServeHTTP(w, r)
		case SdkAgentServiceGetRunProcedure:
			sdkAgentServiceGetRunHandler.ServeHTTP(w, r)
		case SdkAgentServiceListRunsProcedure:
			sdkAgentServiceListRunsHandler.ServeHTTP(w, r)
		case SdkAgentServiceGetRunConversationProcedure:
			sdkAgentServiceGetRunConversationHandler.ServeHTTP(w, r)
		case SdkAgentServiceObserveRunProcedure:
			sdkAgentServiceObserveRunHandler.ServeHTTP(w, r)
		case SdkAgentServiceCancelRunProcedure:
			sdkAgentServiceCancelRunHandler.ServeHTTP(w, r)
		case SdkAgentServiceGetAgentProcedure:
			sdkAgentServiceGetAgentHandler.ServeHTTP(w, r)
		case SdkAgentServiceListAgentsProcedure:
			sdkAgentServiceListAgentsHandler.ServeHTTP(w, r)
		case SdkAgentServiceArchiveAgentProcedure:
			sdkAgentServiceArchiveAgentHandler.ServeHTTP(w, r)
		case SdkAgentServiceUnarchiveAgentProcedure:
			sdkAgentServiceUnarchiveAgentHandler.ServeHTTP(w, r)
		case SdkAgentServiceDeleteAgentProcedure:
			sdkAgentServiceDeleteAgentHandler.ServeHTTP(w, r)
		case SdkAgentServiceListAgentMessagesProcedure:
			sdkAgentServiceListAgentMessagesHandler.ServeHTTP(w, r)
		case SdkAgentServiceListArtifactsProcedure:
			sdkAgentServiceListArtifactsHandler.ServeHTTP(w, r)
		case SdkAgentServiceDownloadArtifactProcedure:
			sdkAgentServiceDownloadArtifactHandler.ServeHTTP(w, r)
		case SdkAgentServiceGetUsageProcedure:
			sdkAgentServiceGetUsageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSdkAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSdkAgentServiceHandler struct{}

func (UnimplementedSdkAgentServiceHandler) CreateAgent(context.Context, *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.CreateAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkAgentService.CreateAgent is not implemented"))
}

func (UnimplementedSdkAgentServiceHandler) ResumeAgent(context.Context, *connect.Request[v1.ResumeAgentRequest]) (*connect.Response[v1.ResumeAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkAgentService.ResumeAgent is not implemented"))
}

func (UnimplementedSdkAgentServiceHandler) ReloadAgent(context.Context, *connect.Request[v1.ReloadAgentRequest]) (*connect.Response[v1.ReloadAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkAgentService.ReloadAgent is not implemented"))
}

func (UnimplementedSdkAgentServiceHandler) CloseAgent(context.Context, *connect.Request[v1.CloseAgentRequest]) (*connect.Response[v1.CloseAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkAgentService.CloseAgent is not implemented"))
}

func (UnimplementedSdkAgentServiceHandler) Send(context.Context, *connect.Request[v1.SendRequest], *connect.ServerStream[v1.RunStreamMessage]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkAgentService.Send is not implemented"))
}

func (UnimplementedSdkAgentServiceHandler) WaitLiveRun(context.Context, *connect.Request[v1.WaitLiveRunRequest]) (*connect.Response[v1.WaitLiveRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkAgentService.WaitLiveRun is not implemented"))
}

func (UnimplementedSdkAgentServiceHandler) GetRun(context.Context, *connect.Request[v1.GetRunRequest]) (*connect.Response[v1.GetRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkAgentService.GetRun is not implemented"))
}

func (UnimplementedSdkAgentServiceHandler) ListRuns(context.Context, *connect.Request[v1.ListRunsRequest]) (*connect.Response[v1.ListRunsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkAgentService.ListRuns is not implemented"))
}

func (UnimplementedSdkAgentServiceHandler) GetRunConversation(context.Context, *connect.Request[v1.GetRunConversationRequest]) (*connect.Response[v1.GetRunConversationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkAgentService.GetRunConversation is not implemented"))
}

func (UnimplementedSdkAgentServiceHandler) ObserveRun(context.Context, *connect.Request[v1.ObserveRunRequest], *connect.ServerStream[v1.RunStreamMessage]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkAgentService.ObserveRun is not implemented"))
}

func (UnimplementedSdkAgentServiceHandler) CancelRun(context.Context, *connect.Request[v1.CancelRunRequest]) (*connect.Response[v1.CancelRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkAgentService.CancelRun is not implemented"))
}

func (UnimplementedSdkAgentServiceHandler) GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.GetAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkAgentService.GetAgent is not implemented"))
}

func (UnimplementedSdkAgentServiceHandler) ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkAgentService.ListAgents is not implemented"))
}

func (UnimplementedSdkAgentServiceHandler) ArchiveAgent(context.Context, *connect.Request[v1.ArchiveAgentRequest]) (*connect.Response[v1.ArchiveAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkAgentService.ArchiveAgent is not implemented"))
}

func (UnimplementedSdkAgentServiceHandler) UnarchiveAgent(context.Context, *connect.Request[v1.UnarchiveAgentRequest]) (*connect.Response[v1.UnarchiveAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkAgentService.UnarchiveAgent is not implemented"))
}

func (UnimplementedSdkAgentServiceHandler) DeleteAgent(context.Context, *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[v1.DeleteAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkAgentService.DeleteAgent is not implemented"))
}

func (UnimplementedSdkAgentServiceHandler) ListAgentMessages(context.Context, *connect.Request[v1.ListAgentMessagesRequest]) (*connect.Response[v1.ListAgentMessagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkAgentService.ListAgentMessages is not implemented"))
}

func (UnimplementedSdkAgentServiceHandler) ListArtifacts(context.Context, *connect.Request[v1.ListArtifactsRequest]) (*connect.Response[v1.ListArtifactsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkAgentService.ListArtifacts is not implemented"))
}

func (UnimplementedSdkAgentServiceHandler) DownloadArtifact(context.Context, *connect.Request[v1.DownloadArtifactRequest], *connect.ServerStream[v1.DownloadArtifactChunk]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkAgentService.DownloadArtifact is not implemented"))
}

func (UnimplementedSdkAgentServiceHandler) GetUsage(context.Context, *connect.Request[v1.GetUsageRequest]) (*connect.Response[v1.GetUsageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sdk.v1.SdkAgentService.GetUsage is not implemented"))
}
