// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sdk/v1/sdk_custom_tool_callback_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallCustomToolRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ToolName string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Tool arguments as a JSON object.
	Args *structpb.Struct `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	// Optional ID for correlating this invocation with stream events.
	ToolCallId *string `protobuf:"bytes,3,opt,name=tool_call_id,json=toolCallId,proto3,oneof" json:"tool_call_id,omitempty"`
	// Agent that owns the tool definition (from CreateAgent / ResumeAgent
	// local.custom_tools).
	AgentId       string `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallCustomToolRequest) Reset() {
	*x = CallCustomToolRequest{}
	mi := &file_sdk_v1_sdk_custom_tool_callback_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallCustomToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallCustomToolRequest) ProtoMessage() {}

func (x *CallCustomToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_custom_tool_callback_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallCustomToolRequest.ProtoReflect.Descriptor instead.
func (*CallCustomToolRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_custom_tool_callback_service_proto_rawDescGZIP(), []int{0}
}

func (x *CallCustomToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *CallCustomToolRequest) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CallCustomToolRequest) GetToolCallId() string {
	if x != nil && x.ToolCallId != nil {
		return *x.ToolCallId
	}
	return ""
}

func (x *CallCustomToolRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type CallCustomToolResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tool result as a JSON object. Common shapes include a plain string value,
	// a structured object, or a content envelope recognized by the SDK.
	Result        *structpb.Struct `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallCustomToolResponse) Reset() {
	*x = CallCustomToolResponse{}
	mi := &file_sdk_v1_sdk_custom_tool_callback_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallCustomToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallCustomToolResponse) ProtoMessage() {}

func (x *CallCustomToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_custom_tool_callback_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallCustomToolResponse.ProtoReflect.Descriptor instead.
func (*CallCustomToolResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_custom_tool_callback_service_proto_rawDescGZIP(), []int{1}
}

func (x *CallCustomToolResponse) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_sdk_v1_sdk_custom_tool_callback_service_proto protoreflect.FileDescriptor

const file_sdk_v1_sdk_custom_tool_callback_service_proto_rawDesc = "" +
	"\n" +
	"-sdk/v1/sdk_custom_tool_callback_service.proto\x12\x06sdk.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xb4\x01\n" +
	"\x15CallCustomToolRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12+\n" +
	"\x04args\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04args\x12%\n" +
	"\ftool_call_id\x18\x03 \x01(\tH\x00R\n" +
	"toolCallId\x88\x01\x01\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentIdB\x0f\n" +
	"\r_tool_call_id\"I\n" +
	"\x16CallCustomToolResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06result2o\n" +
	"\x1cSdkCustomToolCallbackService\x12O\n" +
	"\x0eCallCustomTool\x12\x1d.sdk.v1.CallCustomToolRequest\x1a\x1e.sdk.v1.CallCustomToolResponseBt\n" +
	"\x11com.cursor.sdk.v1P\x01Z-github.com/orvice/butter-box/pkg/proto/sdk/v1\xaa\x02\rCursor.Sdk.V1\xba\x02\vCursorSdkV1\xea\x02\x0fCursor::Sdk::V1b\x06proto3"

var (
	file_sdk_v1_sdk_custom_tool_callback_service_proto_rawDescOnce sync.Once
	file_sdk_v1_sdk_custom_tool_callback_service_proto_rawDescData []byte
)

func file_sdk_v1_sdk_custom_tool_callback_service_proto_rawDescGZIP() []byte {
	file_sdk_v1_sdk_custom_tool_callback_service_proto_rawDescOnce.Do(func() {
		file_sdk_v1_sdk_custom_tool_callback_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_v1_sdk_custom_tool_callback_service_proto_rawDesc), len(file_sdk_v1_sdk_custom_tool_callback_service_proto_rawDesc)))
	})
	return file_sdk_v1_sdk_custom_tool_callback_service_proto_rawDescData
}

var file_sdk_v1_sdk_custom_tool_callback_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sdk_v1_sdk_custom_tool_callback_service_proto_goTypes = []any{
	(*CallCustomToolRequest)(nil),  // 0: sdk.v1.CallCustomToolRequest
	(*CallCustomToolResponse)(nil), // 1: sdk.v1.CallCustomToolResponse
	(*structpb.Struct)(nil),        // 2: google.protobuf.Struct
}
var file_sdk_v1_sdk_custom_tool_callback_service_proto_depIdxs = []int32{
	2, // 0: sdk.v1.CallCustomToolRequest.args:type_name -> google.protobuf.Struct
	2, // 1: sdk.v1.CallCustomToolResponse.result:type_name -> google.protobuf.Struct
	0, // 2: sdk.v1.SdkCustomToolCallbackService.CallCustomTool:input_type -> sdk.v1.CallCustomToolRequest
	1, // 3: sdk.v1.SdkCustomToolCallbackService.CallCustomTool:output_type -> sdk.v1.CallCustomToolResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sdk_v1_sdk_custom_tool_callback_service_proto_init() }
func file_sdk_v1_sdk_custom_tool_callback_service_proto_init() {
	if File_sdk_v1_sdk_custom_tool_callback_service_proto != nil {
		return
	}
	file_sdk_v1_sdk_custom_tool_callback_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_v1_sdk_custom_tool_callback_service_proto_rawDesc), len(file_sdk_v1_sdk_custom_tool_callback_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdk_v1_sdk_custom_tool_callback_service_proto_goTypes,
		DependencyIndexes: file_sdk_v1_sdk_custom_tool_callback_service_proto_depIdxs,
		MessageInfos:      file_sdk_v1_sdk_custom_tool_callback_service_proto_msgTypes,
	}.Build()
	File_sdk_v1_sdk_custom_tool_callback_service_proto = out.File
	file_sdk_v1_sdk_custom_tool_callback_service_proto_goTypes = nil
	file_sdk_v1_sdk_custom_tool_callback_service_proto_depIdxs = nil
}
