// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sdk/v1/sdk_agent_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAgentRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Options *AgentOptions          `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	// Optional key that makes CreateAgent retries safe for cloud agents.
	IdempotencyKey *string `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3,oneof" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAgentRequest) Reset() {
	*x = CreateAgentRequest{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRequest) ProtoMessage() {}

func (x *CreateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAgentRequest) GetOptions() *AgentOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CreateAgentRequest) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

type CreateAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Model         *ModelSelection        `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentResponse) Reset() {
	*x = CreateAgentResponse{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentResponse) ProtoMessage() {}

func (x *CreateAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentResponse.ProtoReflect.Descriptor instead.
func (*CreateAgentResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAgentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateAgentResponse) GetModel() *ModelSelection {
	if x != nil {
		return x.Model
	}
	return nil
}

type ResumeAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Options       *AgentOptions          `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeAgentRequest) Reset() {
	*x = ResumeAgentRequest{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeAgentRequest) ProtoMessage() {}

func (x *ResumeAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeAgentRequest.ProtoReflect.Descriptor instead.
func (*ResumeAgentRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{2}
}

func (x *ResumeAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ResumeAgentRequest) GetOptions() *AgentOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ResumeAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Model         *ModelSelection        `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeAgentResponse) Reset() {
	*x = ResumeAgentResponse{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeAgentResponse) ProtoMessage() {}

func (x *ResumeAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeAgentResponse.ProtoReflect.Descriptor instead.
func (*ResumeAgentResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{3}
}

func (x *ResumeAgentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ResumeAgentResponse) GetModel() *ModelSelection {
	if x != nil {
		return x.Model
	}
	return nil
}

type ReloadAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadAgentRequest) Reset() {
	*x = ReloadAgentRequest{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadAgentRequest) ProtoMessage() {}

func (x *ReloadAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadAgentRequest.ProtoReflect.Descriptor instead.
func (*ReloadAgentRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReloadAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ReloadAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadAgentResponse) Reset() {
	*x = ReloadAgentResponse{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadAgentResponse) ProtoMessage() {}

func (x *ReloadAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadAgentResponse.ProtoReflect.Descriptor instead.
func (*ReloadAgentResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{5}
}

type CloseAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseAgentRequest) Reset() {
	*x = CloseAgentRequest{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseAgentRequest) ProtoMessage() {}

func (x *CloseAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseAgentRequest.ProtoReflect.Descriptor instead.
func (*CloseAgentRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{6}
}

func (x *CloseAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type CloseAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseAgentResponse) Reset() {
	*x = CloseAgentResponse{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseAgentResponse) ProtoMessage() {}

func (x *CloseAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseAgentResponse.ProtoReflect.Descriptor instead.
func (*CloseAgentResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{7}
}

type SendRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Message *UserMessage           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Options *SendOptions           `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	// Optional key that makes Send retries safe for cloud agents.
	IdempotencyKey *string `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3,oneof" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{8}
}

func (x *SendRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SendRequest) GetMessage() *UserMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SendRequest) GetOptions() *SendOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SendRequest) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

type WaitLiveRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitLiveRunRequest) Reset() {
	*x = WaitLiveRunRequest{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitLiveRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitLiveRunRequest) ProtoMessage() {}

func (x *WaitLiveRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitLiveRunRequest.ProtoReflect.Descriptor instead.
func (*WaitLiveRunRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{9}
}

func (x *WaitLiveRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type WaitLiveRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *RunResult             `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitLiveRunResponse) Reset() {
	*x = WaitLiveRunResponse{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitLiveRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitLiveRunResponse) ProtoMessage() {}

func (x *WaitLiveRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitLiveRunResponse.ProtoReflect.Descriptor instead.
func (*WaitLiveRunResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{10}
}

func (x *WaitLiveRunResponse) GetResult() *RunResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Options       *GetRunOptions         `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunRequest) Reset() {
	*x = GetRunRequest{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunRequest) ProtoMessage() {}

func (x *GetRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunRequest.ProtoReflect.Descriptor instead.
func (*GetRunRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GetRunRequest) GetOptions() *GetRunOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type GetRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *RunSnapshot           `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunResponse) Reset() {
	*x = GetRunResponse{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunResponse) ProtoMessage() {}

func (x *GetRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunResponse.ProtoReflect.Descriptor instead.
func (*GetRunResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetRunResponse) GetRun() *RunSnapshot {
	if x != nil {
		return x.Run
	}
	return nil
}

type ListRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Options       *ListRunsOptions       `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsRequest) Reset() {
	*x = ListRunsRequest{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsRequest) ProtoMessage() {}

func (x *ListRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListRunsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListRunsRequest) GetOptions() *ListRunsOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListRunsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Items []*RunSnapshot         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Opaque pagination cursor. Empty when there are no further pages.
	NextCursor    string `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsResponse) Reset() {
	*x = ListRunsResponse{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsResponse) ProtoMessage() {}

func (x *ListRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListRunsResponse) GetItems() []*RunSnapshot {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListRunsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetRunConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunConversationRequest) Reset() {
	*x = GetRunConversationRequest{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunConversationRequest) ProtoMessage() {}

func (x *GetRunConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunConversationRequest.ProtoReflect.Descriptor instead.
func (*GetRunConversationRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetRunConversationRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetRunConversationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque conversation document encoded as JSON.
	ConversationJson string `protobuf:"bytes,1,opt,name=conversation_json,json=conversationJson,proto3" json:"conversation_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetRunConversationResponse) Reset() {
	*x = GetRunConversationResponse{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunConversationResponse) ProtoMessage() {}

func (x *GetRunConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunConversationResponse.ProtoReflect.Descriptor instead.
func (*GetRunConversationResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetRunConversationResponse) GetConversationJson() string {
	if x != nil {
		return x.ConversationJson
	}
	return ""
}

type ObserveRunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Resume after this exclusive offset from a prior ObserveRun / Send stream.
	// When unset, the stream starts from the beginning of durable events.
	AfterOffset   *string `protobuf:"bytes,2,opt,name=after_offset,json=afterOffset,proto3,oneof" json:"after_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveRunRequest) Reset() {
	*x = ObserveRunRequest{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveRunRequest) ProtoMessage() {}

func (x *ObserveRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveRunRequest.ProtoReflect.Descriptor instead.
func (*ObserveRunRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{17}
}

func (x *ObserveRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ObserveRunRequest) GetAfterOffset() string {
	if x != nil && x.AfterOffset != nil {
		return *x.AfterOffset
	}
	return ""
}

type CancelRunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Optional agent hint used by some bridge deployments for routing.
	AgentId       *string `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3,oneof" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunRequest) Reset() {
	*x = CancelRunRequest{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunRequest) ProtoMessage() {}

func (x *CancelRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunRequest.ProtoReflect.Descriptor instead.
func (*CancelRunRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{18}
}

func (x *CancelRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CancelRunRequest) GetAgentId() string {
	if x != nil && x.AgentId != nil {
		return *x.AgentId
	}
	return ""
}

type CancelRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunResponse) Reset() {
	*x = CancelRunResponse{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunResponse) ProtoMessage() {}

func (x *CancelRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunResponse.ProtoReflect.Descriptor instead.
func (*CancelRunResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{19}
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Options       *AgentOperationOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetAgentRequest) GetOptions() *AgentOperationOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *SdkAgentInfo          `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetAgentResponse) GetAgent() *SdkAgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *ListAgentsOptions     `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{22}
}

func (x *ListAgentsRequest) GetOptions() *ListAgentsOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListAgentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Items []*SdkAgentInfo        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Opaque pagination cursor. Empty when there are no further pages.
	NextCursor    string `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{23}
}

func (x *ListAgentsResponse) GetItems() []*SdkAgentInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListAgentsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type ArchiveAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Options       *AgentOperationOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveAgentRequest) Reset() {
	*x = ArchiveAgentRequest{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveAgentRequest) ProtoMessage() {}

func (x *ArchiveAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveAgentRequest.ProtoReflect.Descriptor instead.
func (*ArchiveAgentRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{24}
}

func (x *ArchiveAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ArchiveAgentRequest) GetOptions() *AgentOperationOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ArchiveAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveAgentResponse) Reset() {
	*x = ArchiveAgentResponse{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveAgentResponse) ProtoMessage() {}

func (x *ArchiveAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveAgentResponse.ProtoReflect.Descriptor instead.
func (*ArchiveAgentResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{25}
}

type UnarchiveAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Options       *AgentOperationOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnarchiveAgentRequest) Reset() {
	*x = UnarchiveAgentRequest{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnarchiveAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnarchiveAgentRequest) ProtoMessage() {}

func (x *UnarchiveAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnarchiveAgentRequest.ProtoReflect.Descriptor instead.
func (*UnarchiveAgentRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{26}
}

func (x *UnarchiveAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UnarchiveAgentRequest) GetOptions() *AgentOperationOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type UnarchiveAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnarchiveAgentResponse) Reset() {
	*x = UnarchiveAgentResponse{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnarchiveAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnarchiveAgentResponse) ProtoMessage() {}

func (x *UnarchiveAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnarchiveAgentResponse.ProtoReflect.Descriptor instead.
func (*UnarchiveAgentResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{27}
}

type DeleteAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Options       *AgentOperationOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentRequest) Reset() {
	*x = DeleteAgentRequest{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentRequest) ProtoMessage() {}

func (x *DeleteAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DeleteAgentRequest) GetOptions() *AgentOperationOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type DeleteAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentResponse) Reset() {
	*x = DeleteAgentResponse{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentResponse) ProtoMessage() {}

func (x *DeleteAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAgentResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{29}
}

type ListAgentMessagesRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	AgentId       string                   `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Options       *GetAgentMessagesOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentMessagesRequest) Reset() {
	*x = ListAgentMessagesRequest{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentMessagesRequest) ProtoMessage() {}

func (x *ListAgentMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListAgentMessagesRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{30}
}

func (x *ListAgentMessagesRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListAgentMessagesRequest) GetOptions() *GetAgentMessagesOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListAgentMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*AgentMessage        `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentMessagesResponse) Reset() {
	*x = ListAgentMessagesResponse{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentMessagesResponse) ProtoMessage() {}

func (x *ListAgentMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListAgentMessagesResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{31}
}

func (x *ListAgentMessagesResponse) GetMessages() []*AgentMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ListArtifactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactsRequest) Reset() {
	*x = ListArtifactsRequest{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsRequest) ProtoMessage() {}

func (x *ListArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsRequest.ProtoReflect.Descriptor instead.
func (*ListArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{32}
}

func (x *ListArtifactsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ListArtifactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifacts     []*SdkArtifact         `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactsResponse) Reset() {
	*x = ListArtifactsResponse{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsResponse) ProtoMessage() {}

func (x *ListArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsResponse.ProtoReflect.Descriptor instead.
func (*ListArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{33}
}

func (x *ListArtifactsResponse) GetArtifacts() []*SdkArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type DownloadArtifactRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Artifact path as returned by ListArtifacts.
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadArtifactRequest) Reset() {
	*x = DownloadArtifactRequest{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadArtifactRequest) ProtoMessage() {}

func (x *DownloadArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadArtifactRequest.ProtoReflect.Descriptor instead.
func (*DownloadArtifactRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{34}
}

func (x *DownloadArtifactRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DownloadArtifactRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetUsageRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Restrict the result to a single run.
	RunId         *string `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3,oneof" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageRequest) Reset() {
	*x = GetUsageRequest{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageRequest) ProtoMessage() {}

func (x *GetUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageRequest.ProtoReflect.Descriptor instead.
func (*GetUsageRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{35}
}

func (x *GetUsageRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetUsageRequest) GetRunId() string {
	if x != nil && x.RunId != nil {
		return *x.RunId
	}
	return ""
}

type GetUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usage         *AgentUsage            `protobuf:"bytes,1,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageResponse) Reset() {
	*x = GetUsageResponse{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageResponse) ProtoMessage() {}

func (x *GetUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageResponse.ProtoReflect.Descriptor instead.
func (*GetUsageResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{36}
}

func (x *GetUsageResponse) GetUsage() *AgentUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type ListAgentsOptions struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Limit   uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor  string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Runtime Runtime                `protobuf:"varint,3,opt,name=runtime,proto3,enum=sdk.v1.Runtime" json:"runtime,omitempty"`
	Cwd     string                 `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// Filter cloud agents associated with this pull-request URL.
	PrUrl           string `protobuf:"bytes,5,opt,name=pr_url,json=prUrl,proto3" json:"pr_url,omitempty"`
	IncludeArchived *bool  `protobuf:"varint,6,opt,name=include_archived,json=includeArchived,proto3,oneof" json:"include_archived,omitempty"`
	ApiKey          string `protobuf:"bytes,7,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListAgentsOptions) Reset() {
	*x = ListAgentsOptions{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsOptions) ProtoMessage() {}

func (x *ListAgentsOptions) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsOptions.ProtoReflect.Descriptor instead.
func (*ListAgentsOptions) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{37}
}

func (x *ListAgentsOptions) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAgentsOptions) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListAgentsOptions) GetRuntime() Runtime {
	if x != nil {
		return x.Runtime
	}
	return Runtime_RUNTIME_UNSPECIFIED
}

func (x *ListAgentsOptions) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ListAgentsOptions) GetPrUrl() string {
	if x != nil {
		return x.PrUrl
	}
	return ""
}

func (x *ListAgentsOptions) GetIncludeArchived() bool {
	if x != nil && x.IncludeArchived != nil {
		return *x.IncludeArchived
	}
	return false
}

func (x *ListAgentsOptions) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type ListRunsOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Runtime       Runtime                `protobuf:"varint,3,opt,name=runtime,proto3,enum=sdk.v1.Runtime" json:"runtime,omitempty"`
	Cwd           string                 `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	ApiKey        string                 `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsOptions) Reset() {
	*x = ListRunsOptions{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsOptions) ProtoMessage() {}

func (x *ListRunsOptions) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsOptions.ProtoReflect.Descriptor instead.
func (*ListRunsOptions) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{38}
}

func (x *ListRunsOptions) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRunsOptions) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListRunsOptions) GetRuntime() Runtime {
	if x != nil {
		return x.Runtime
	}
	return Runtime_RUNTIME_UNSPECIFIED
}

func (x *ListRunsOptions) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ListRunsOptions) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type GetRunOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runtime       Runtime                `protobuf:"varint,1,opt,name=runtime,proto3,enum=sdk.v1.Runtime" json:"runtime,omitempty"`
	Cwd           string                 `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ApiKey        string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunOptions) Reset() {
	*x = GetRunOptions{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunOptions) ProtoMessage() {}

func (x *GetRunOptions) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunOptions.ProtoReflect.Descriptor instead.
func (*GetRunOptions) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{39}
}

func (x *GetRunOptions) GetRuntime() Runtime {
	if x != nil {
		return x.Runtime
	}
	return Runtime_RUNTIME_UNSPECIFIED
}

func (x *GetRunOptions) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *GetRunOptions) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetRunOptions) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type AgentOperationOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cwd           string                 `protobuf:"bytes,1,opt,name=cwd,proto3" json:"cwd,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentOperationOptions) Reset() {
	*x = AgentOperationOptions{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentOperationOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentOperationOptions) ProtoMessage() {}

func (x *AgentOperationOptions) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentOperationOptions.ProtoReflect.Descriptor instead.
func (*AgentOperationOptions) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{40}
}

func (x *AgentOperationOptions) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *AgentOperationOptions) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type GetAgentMessagesOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Runtime       Runtime                `protobuf:"varint,3,opt,name=runtime,proto3,enum=sdk.v1.Runtime" json:"runtime,omitempty"`
	Cwd           string                 `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	ApiKey        string                 `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentMessagesOptions) Reset() {
	*x = GetAgentMessagesOptions{}
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentMessagesOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentMessagesOptions) ProtoMessage() {}

func (x *GetAgentMessagesOptions) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_agent_service_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentMessagesOptions.ProtoReflect.Descriptor instead.
func (*GetAgentMessagesOptions) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_agent_service_proto_rawDescGZIP(), []int{41}
}

func (x *GetAgentMessagesOptions) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAgentMessagesOptions) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetAgentMessagesOptions) GetRuntime() Runtime {
	if x != nil {
		return x.Runtime
	}
	return Runtime_RUNTIME_UNSPECIFIED
}

func (x *GetAgentMessagesOptions) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *GetAgentMessagesOptions) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

var File_sdk_v1_sdk_agent_service_proto protoreflect.FileDescriptor

const file_sdk_v1_sdk_agent_service_proto_rawDesc = "" +
	"\n" +
	"\x1esdk/v1/sdk_agent_service.proto\x12\x06sdk.v1\x1a\x19sdk/v1/sdk_messages.proto\"\x86\x01\n" +
	"\x12CreateAgentRequest\x12.\n" +
	"\aoptions\x18\x01 \x01(\v2\x14.sdk.v1.AgentOptionsR\aoptions\x12,\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tH\x00R\x0eidempotencyKey\x88\x01\x01B\x12\n" +
	"\x10_idempotency_key\"^\n" +
	"\x13CreateAgentResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12,\n" +
	"\x05model\x18\x02 \x01(\v2\x16.sdk.v1.ModelSelectionR\x05model\"_\n" +
	"\x12ResumeAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12.\n" +
	"\aoptions\x18\x02 \x01(\v2\x14.sdk.v1.AgentOptionsR\aoptions\"^\n" +
	"\x13ResumeAgentResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12,\n" +
	"\x05model\x18\x02 \x01(\v2\x16.sdk.v1.ModelSelectionR\x05model\"/\n" +
	"\x12ReloadAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x15\n" +
	"\x13ReloadAgentResponse\".\n" +
	"\x11CloseAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x14\n" +
	"\x12CloseAgentResponse\"\xc8\x01\n" +
	"\vSendRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12-\n" +
	"\amessage\x18\x02 \x01(\v2\x13.sdk.v1.UserMessageR\amessage\x12-\n" +
	"\aoptions\x18\x03 \x01(\v2\x13.sdk.v1.SendOptionsR\aoptions\x12,\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tH\x00R\x0eidempotencyKey\x88\x01\x01B\x12\n" +
	"\x10_idempotency_key\"+\n" +
	"\x12WaitLiveRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"@\n" +
	"\x13WaitLiveRunResponse\x12)\n" +
	"\x06result\x18\x01 \x01(\v2\x11.sdk.v1.RunResultR\x06result\"W\n" +
	"\rGetRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12/\n" +
	"\aoptions\x18\x02 \x01(\v2\x15.sdk.v1.GetRunOptionsR\aoptions\"7\n" +
	"\x0eGetRunResponse\x12%\n" +
	"\x03run\x18\x01 \x01(\v2\x13.sdk.v1.RunSnapshotR\x03run\"_\n" +
	"\x0fListRunsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x121\n" +
	"\aoptions\x18\x02 \x01(\v2\x17.sdk.v1.ListRunsOptionsR\aoptions\"^\n" +
	"\x10ListRunsResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.sdk.v1.RunSnapshotR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"2\n" +
	"\x19GetRunConversationRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"I\n" +
	"\x1aGetRunConversationResponse\x12+\n" +
	"\x11conversation_json\x18\x01 \x01(\tR\x10conversationJson\"c\n" +
	"\x11ObserveRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12&\n" +
	"\fafter_offset\x18\x02 \x01(\tH\x00R\vafterOffset\x88\x01\x01B\x0f\n" +
	"\r_after_offset\"V\n" +
	"\x10CancelRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1e\n" +
	"\bagent_id\x18\x02 \x01(\tH\x00R\aagentId\x88\x01\x01B\v\n" +
	"\t_agent_id\"\x13\n" +
	"\x11CancelRunResponse\"e\n" +
	"\x0fGetAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x127\n" +
	"\aoptions\x18\x02 \x01(\v2\x1d.sdk.v1.AgentOperationOptionsR\aoptions\">\n" +
	"\x10GetAgentResponse\x12*\n" +
	"\x05agent\x18\x01 \x01(\v2\x14.sdk.v1.SdkAgentInfoR\x05agent\"H\n" +
	"\x11ListAgentsRequest\x123\n" +
	"\aoptions\x18\x01 \x01(\v2\x19.sdk.v1.ListAgentsOptionsR\aoptions\"a\n" +
	"\x12ListAgentsResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.sdk.v1.SdkAgentInfoR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"i\n" +
	"\x13ArchiveAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x127\n" +
	"\aoptions\x18\x02 \x01(\v2\x1d.sdk.v1.AgentOperationOptionsR\aoptions\"\x16\n" +
	"\x14ArchiveAgentResponse\"k\n" +
	"\x15UnarchiveAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x127\n" +
	"\aoptions\x18\x02 \x01(\v2\x1d.sdk.v1.AgentOperationOptionsR\aoptions\"\x18\n" +
	"\x16UnarchiveAgentResponse\"h\n" +
	"\x12DeleteAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x127\n" +
	"\aoptions\x18\x02 \x01(\v2\x1d.sdk.v1.AgentOperationOptionsR\aoptions\"\x15\n" +
	"\x13DeleteAgentResponse\"p\n" +
	"\x18ListAgentMessagesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x129\n" +
	"\aoptions\x18\x02 \x01(\v2\x1f.sdk.v1.GetAgentMessagesOptionsR\aoptions\"M\n" +
	"\x19ListAgentMessagesResponse\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.sdk.v1.AgentMessageR\bmessages\"1\n" +
	"\x14ListArtifactsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"J\n" +
	"\x15ListArtifactsResponse\x121\n" +
	"\tartifacts\x18\x01 \x03(\v2\x13.sdk.v1.SdkArtifactR\tartifacts\"H\n" +
	"\x17DownloadArtifactRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"S\n" +
	"\x0fGetUsageRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\x06run_id\x18\x02 \x01(\tH\x00R\x05runId\x88\x01\x01B\t\n" +
	"\a_run_id\"<\n" +
	"\x10GetUsageResponse\x12(\n" +
	"\x05usage\x18\x01 \x01(\v2\x12.sdk.v1.AgentUsageR\x05usage\"\xf3\x01\n" +
	"\x11ListAgentsOptions\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12)\n" +
	"\aruntime\x18\x03 \x01(\x0e2\x0f.sdk.v1.RuntimeR\aruntime\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12\x15\n" +
	"\x06pr_url\x18\x05 \x01(\tR\x05prUrl\x12.\n" +
	"\x10include_archived\x18\x06 \x01(\bH\x00R\x0fincludeArchived\x88\x01\x01\x12\x17\n" +
	"\aapi_key\x18\a \x01(\tR\x06apiKeyB\x13\n" +
	"\x11_include_archived\"\x95\x01\n" +
	"\x0fListRunsOptions\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12)\n" +
	"\aruntime\x18\x03 \x01(\x0e2\x0f.sdk.v1.RuntimeR\aruntime\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12\x17\n" +
	"\aapi_key\x18\x05 \x01(\tR\x06apiKey\"\x80\x01\n" +
	"\rGetRunOptions\x12)\n" +
	"\aruntime\x18\x01 \x01(\x0e2\x0f.sdk.v1.RuntimeR\aruntime\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\"B\n" +
	"\x15AgentOperationOptions\x12\x10\n" +
	"\x03cwd\x18\x01 \x01(\tR\x03cwd\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"\x9d\x01\n" +
	"\x17GetAgentMessagesOptions\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12)\n" +
	"\aruntime\x18\x03 \x01(\x0e2\x0f.sdk.v1.RuntimeR\aruntime\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12\x17\n" +
	"\aapi_key\x18\x05 \x01(\tR\x06apiKey2\xb0\v\n" +
	"\x0fSdkAgentService\x12F\n" +
	"\vCreateAgent\x12\x1a.sdk.v1.CreateAgentRequest\x1a\x1b.sdk.v1.CreateAgentResponse\x12F\n" +
	"\vResumeAgent\x12\x1a.sdk.v1.ResumeAgentRequest\x1a\x1b.sdk.v1.ResumeAgentResponse\x12F\n" +
	"\vReloadAgent\x12\x1a.sdk.v1.ReloadAgentRequest\x1a\x1b.sdk.v1.ReloadAgentResponse\x12C\n" +
	"\n" +
	"CloseAgent\x12\x19.sdk.v1.CloseAgentRequest\x1a\x1a.sdk.v1.CloseAgentResponse\x127\n" +
	"\x04Send\x12\x13.sdk.v1.SendRequest\x1a\x18.sdk.v1.RunStreamMessage0\x01\x12F\n" +
	"\vWaitLiveRun\x12\x1a.sdk.v1.WaitLiveRunRequest\x1a\x1b.sdk.v1.WaitLiveRunResponse\x127\n" +
	"\x06GetRun\x12\x15.sdk.v1.GetRunRequest\x1a\x16.sdk.v1.GetRunResponse\x12=\n" +
	"\bListRuns\x12\x17.sdk.v1.ListRunsRequest\x1a\x18.sdk.v1.ListRunsResponse\x12[\n" +
	"\x12GetRunConversation\x12!.sdk.v1.GetRunConversationRequest\x1a\".sdk.v1.GetRunConversationResponse\x12C\n" +
	"\n" +
	"ObserveRun\x12\x19.sdk.v1.ObserveRunRequest\x1a\x18.sdk.v1.RunStreamMessage0\x01\x12@\n" +
	"\tCancelRun\x12\x18.sdk.v1.CancelRunRequest\x1a\x19.sdk.v1.CancelRunResponse\x12=\n" +
	"\bGetAgent\x12\x17.sdk.v1.GetAgentRequest\x1a\x18.sdk.v1.GetAgentResponse\x12C\n" +
	"\n" +
	"ListAgents\x12\x19.sdk.v1.ListAgentsRequest\x1a\x1a.sdk.v1.ListAgentsResponse\x12I\n" +
	"\fArchiveAgent\x12\x1b.sdk.v1.ArchiveAgentRequest\x1a\x1c.sdk.v1.ArchiveAgentResponse\x12O\n" +
	"\x0eUnarchiveAgent\x12\x1d.sdk.v1.UnarchiveAgentRequest\x1a\x1e.sdk.v1.UnarchiveAgentResponse\x12F\n" +
	"\vDeleteAgent\x12\x1a.sdk.v1.DeleteAgentRequest\x1a\x1b.sdk.v1.DeleteAgentResponse\x12X\n" +
	"\x11ListAgentMessages\x12 .sdk.v1.ListAgentMessagesRequest\x1a!.sdk.v1.ListAgentMessagesResponse\x12L\n" +
	"\rListArtifacts\x12\x1c.sdk.v1.ListArtifactsRequest\x1a\x1d.sdk.v1.ListArtifactsResponse\x12T\n" +
	"\x10DownloadArtifact\x12\x1f.sdk.v1.DownloadArtifactRequest\x1a\x1d.sdk.v1.DownloadArtifactChunk0\x01\x12=\n" +
	"\bGetUsage\x12\x17.sdk.v1.GetUsageRequest\x1a\x18.sdk.v1.GetUsageResponseBt\n" +
	"\x11com.cursor.sdk.v1P\x01Z-github.com/orvice/butter-box/pkg/proto/sdk/v1\xaa\x02\rCursor.Sdk.V1\xba\x02\vCursorSdkV1\xea\x02\x0fCursor::Sdk::V1b\x06proto3"

var (
	file_sdk_v1_sdk_agent_service_proto_rawDescOnce sync.Once
	file_sdk_v1_sdk_agent_service_proto_rawDescData []byte
)

func file_sdk_v1_sdk_agent_service_proto_rawDescGZIP() []byte {
	file_sdk_v1_sdk_agent_service_proto_rawDescOnce.Do(func() {
		file_sdk_v1_sdk_agent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_v1_sdk_agent_service_proto_rawDesc), len(file_sdk_v1_sdk_agent_service_proto_rawDesc)))
	})
	return file_sdk_v1_sdk_agent_service_proto_rawDescData
}

var file_sdk_v1_sdk_agent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_sdk_v1_sdk_agent_service_proto_goTypes = []any{
	(*CreateAgentRequest)(nil),         // 0: sdk.v1.CreateAgentRequest
	(*CreateAgentResponse)(nil),        // 1: sdk.v1.CreateAgentResponse
	(*ResumeAgentRequest)(nil),         // 2: sdk.v1.ResumeAgentRequest
	(*ResumeAgentResponse)(nil),        // 3: sdk.v1.ResumeAgentResponse
	(*ReloadAgentRequest)(nil),         // 4: sdk.v1.ReloadAgentRequest
	(*ReloadAgentResponse)(nil),        // 5: sdk.v1.ReloadAgentResponse
	(*CloseAgentRequest)(nil),          // 6: sdk.v1.CloseAgentRequest
	(*CloseAgentResponse)(nil),         // 7: sdk.v1.CloseAgentResponse
	(*SendRequest)(nil),                // 8: sdk.v1.SendRequest
	(*WaitLiveRunRequest)(nil),         // 9: sdk.v1.WaitLiveRunRequest
	(*WaitLiveRunResponse)(nil),        // 10: sdk.v1.WaitLiveRunResponse
	(*GetRunRequest)(nil),              // 11: sdk.v1.GetRunRequest
	(*GetRunResponse)(nil),             // 12: sdk.v1.GetRunResponse
	(*ListRunsRequest)(nil),            // 13: sdk.v1.ListRunsRequest
	(*ListRunsResponse)(nil),           // 14: sdk.v1.ListRunsResponse
	(*GetRunConversationRequest)(nil),  // 15: sdk.v1.GetRunConversationRequest
	(*GetRunConversationResponse)(nil), // 16: sdk.v1.GetRunConversationResponse
	(*ObserveRunRequest)(nil),          // 17: sdk.v1.ObserveRunRequest
	(*CancelRunRequest)(nil),           // 18: sdk.v1.CancelRunRequest
	(*CancelRunResponse)(nil),          // 19: sdk.v1.CancelRunResponse
	(*GetAgentRequest)(nil),            // 20: sdk.v1.GetAgentRequest
	(*GetAgentResponse)(nil),           // 21: sdk.v1.GetAgentResponse
	(*ListAgentsRequest)(nil),          // 22: sdk.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),         // 23: sdk.v1.ListAgentsResponse
	(*ArchiveAgentRequest)(nil),        // 24: sdk.v1.ArchiveAgentRequest
	(*ArchiveAgentResponse)(nil),       // 25: sdk.v1.ArchiveAgentResponse
	(*UnarchiveAgentRequest)(nil),      // 26: sdk.v1.UnarchiveAgentRequest
	(*UnarchiveAgentResponse)(nil),     // 27: sdk.v1.UnarchiveAgentResponse
	(*DeleteAgentRequest)(nil),         // 28: sdk.v1.DeleteAgentRequest
	(*DeleteAgentResponse)(nil),        // 29: sdk.v1.DeleteAgentResponse
	(*ListAgentMessagesRequest)(nil),   // 30: sdk.v1.ListAgentMessagesRequest
	(*ListAgentMessagesResponse)(nil),  // 31: sdk.v1.ListAgentMessagesResponse
	(*ListArtifactsRequest)(nil),       // 32: sdk.v1.ListArtifactsRequest
	(*ListArtifactsResponse)(nil),      // 33: sdk.v1.ListArtifactsResponse
	(*DownloadArtifactRequest)(nil),    // 34: sdk.v1.DownloadArtifactRequest
	(*GetUsageRequest)(nil),            // 35: sdk.v1.GetUsageRequest
	(*GetUsageResponse)(nil),           // 36: sdk.v1.GetUsageResponse
	(*ListAgentsOptions)(nil),          // 37: sdk.v1.ListAgentsOptions
	(*ListRunsOptions)(nil),            // 38: sdk.v1.ListRunsOptions
	(*GetRunOptions)(nil),              // 39: sdk.v1.GetRunOptions
	(*AgentOperationOptions)(nil),      // 40: sdk.v1.AgentOperationOptions
	(*GetAgentMessagesOptions)(nil),    // 41: sdk.v1.GetAgentMessagesOptions
	(*AgentOptions)(nil),               // 42: sdk.v1.AgentOptions
	(*ModelSelection)(nil),             // 43: sdk.v1.ModelSelection
	(*UserMessage)(nil),                // 44: sdk.v1.UserMessage
	(*SendOptions)(nil),                // 45: sdk.v1.SendOptions
	(*RunResult)(nil),                  // 46: sdk.v1.RunResult
	(*RunSnapshot)(nil),                // 47: sdk.v1.RunSnapshot
	(*SdkAgentInfo)(nil),               // 48: sdk.v1.SdkAgentInfo
	(*AgentMessage)(nil),               // 49: sdk.v1.AgentMessage
	(*SdkArtifact)(nil),                // 50: sdk.v1.SdkArtifact
	(*AgentUsage)(nil),                 // 51: sdk.v1.AgentUsage
	(Runtime)(0),                       // 52: sdk.v1.Runtime
	(*RunStreamMessage)(nil),           // 53: sdk.v1.RunStreamMessage
	(*DownloadArtifactChunk)(nil),      // 54: sdk.v1.DownloadArtifactChunk
}
var file_sdk_v1_sdk_agent_service_proto_depIdxs = []int32{
	42, // 0: sdk.v1.CreateAgentRequest.options:type_name -> sdk.v1.AgentOptions
	43, // 1: sdk.v1.CreateAgentResponse.model:type_name -> sdk.v1.ModelSelection
	42, // 2: sdk.v1.ResumeAgentRequest.options:type_name -> sdk.v1.AgentOptions
	43, // 3: sdk.v1.ResumeAgentResponse.model:type_name -> sdk.v1.ModelSelection
	44, // 4: sdk.v1.SendRequest.message:type_name -> sdk.v1.UserMessage
	45, // 5: sdk.v1.SendRequest.options:type_name -> sdk.v1.SendOptions
	46, // 6: sdk.v1.WaitLiveRunResponse.result:type_name -> sdk.v1.RunResult
	39, // 7: sdk.v1.GetRunRequest.options:type_name -> sdk.v1.GetRunOptions
	47, // 8: sdk.v1.GetRunResponse.run:type_name -> sdk.v1.RunSnapshot
	38, // 9: sdk.v1.ListRunsRequest.options:type_name -> sdk.v1.ListRunsOptions
	47, // 10: sdk.v1.ListRunsResponse.items:type_name -> sdk.v1.RunSnapshot
	40, // 11: sdk.v1.GetAgentRequest.options:type_name -> sdk.v1.AgentOperationOptions
	48, // 12: sdk.v1.GetAgentResponse.agent:type_name -> sdk.v1.SdkAgentInfo
	37, // 13: sdk.v1.ListAgentsRequest.options:type_name -> sdk.v1.ListAgentsOptions
	48, // 14: sdk.v1.ListAgentsResponse.items:type_name -> sdk.v1.SdkAgentInfo
	40, // 15: sdk.v1.ArchiveAgentRequest.options:type_name -> sdk.v1.AgentOperationOptions
	40, // 16: sdk.v1.UnarchiveAgentRequest.options:type_name -> sdk.v1.AgentOperationOptions
	40, // 17: sdk.v1.DeleteAgentRequest.options:type_name -> sdk.v1.AgentOperationOptions
	41, // 18: sdk.v1.ListAgentMessagesRequest.options:type_name -> sdk.v1.GetAgentMessagesOptions
	49, // 19: sdk.v1.ListAgentMessagesResponse.messages:type_name -> sdk.v1.AgentMessage
	50, // 20: sdk.v1.ListArtifactsResponse.artifacts:type_name -> sdk.v1.SdkArtifact
	51, // 21: sdk.v1.GetUsageResponse.usage:type_name -> sdk.v1.AgentUsage
	52, // 22: sdk.v1.ListAgentsOptions.runtime:type_name -> sdk.v1.Runtime
	52, // 23: sdk.v1.ListRunsOptions.runtime:type_name -> sdk.v1.Runtime
	52, // 24: sdk.v1.GetRunOptions.runtime:type_name -> sdk.v1.Runtime
	52, // 25: sdk.v1.GetAgentMessagesOptions.runtime:type_name -> sdk.v1.Runtime
	0,  // 26: sdk.v1.SdkAgentService.CreateAgent:input_type -> sdk.v1.CreateAgentRequest
	2,  // 27: sdk.v1.SdkAgentService.ResumeAgent:input_type -> sdk.v1.ResumeAgentRequest
	4,  // 28: sdk.v1.SdkAgentService.ReloadAgent:input_type -> sdk.v1.ReloadAgentRequest
	6,  // 29: sdk.v1.SdkAgentService.CloseAgent:input_type -> sdk.v1.CloseAgentRequest
	8,  // 30: sdk.v1.SdkAgentService.Send:input_type -> sdk.v1.SendRequest
	9,  // 31: sdk.v1.SdkAgentService.WaitLiveRun:input_type -> sdk.v1.WaitLiveRunRequest
	11, // 32: sdk.v1.SdkAgentService.GetRun:input_type -> sdk.v1.GetRunRequest
	13, // 33: sdk.v1.SdkAgentService.ListRuns:input_type -> sdk.v1.ListRunsRequest
	15, // 34: sdk.v1.SdkAgentService.GetRunConversation:input_type -> sdk.v1.GetRunConversationRequest
	17, // 35: sdk.v1.SdkAgentService.ObserveRun:input_type -> sdk.v1.ObserveRunRequest
	18, // 36: sdk.v1.SdkAgentService.CancelRun:input_type -> sdk.v1.CancelRunRequest
	20, // 37: sdk.v1.SdkAgentService.GetAgent:input_type -> sdk.v1.GetAgentRequest
	22, // 38: sdk.v1.SdkAgentService.ListAgents:input_type -> sdk.v1.ListAgentsRequest
	24, // 39: sdk.v1.SdkAgentService.ArchiveAgent:input_type -> sdk.v1.ArchiveAgentRequest
	26, // 40: sdk.v1.SdkAgentService.UnarchiveAgent:input_type -> sdk.v1.UnarchiveAgentRequest
	28, // 41: sdk.v1.SdkAgentService.DeleteAgent:input_type -> sdk.v1.DeleteAgentRequest
	30, // 42: sdk.v1.SdkAgentService.ListAgentMessages:input_type -> sdk.v1.ListAgentMessagesRequest
	32, // 43: sdk.v1.SdkAgentService.ListArtifacts:input_type -> sdk.v1.ListArtifactsRequest
	34, // 44: sdk.v1.SdkAgentService.DownloadArtifact:input_type -> sdk.v1.DownloadArtifactRequest
	35, // 45: sdk.v1.SdkAgentService.GetUsage:input_type -> sdk.v1.GetUsageRequest
	1,  // 46: sdk.v1.SdkAgentService.CreateAgent:output_type -> sdk.v1.CreateAgentResponse
	3,  // 47: sdk.v1.SdkAgentService.ResumeAgent:output_type -> sdk.v1.ResumeAgentResponse
	5,  // 48: sdk.v1.SdkAgentService.ReloadAgent:output_type -> sdk.v1.ReloadAgentResponse
	7,  // 49: sdk.v1.SdkAgentService.CloseAgent:output_type -> sdk.v1.CloseAgentResponse
	53, // 50: sdk.v1.SdkAgentService.Send:output_type -> sdk.v1.RunStreamMessage
	10, // 51: sdk.v1.SdkAgentService.WaitLiveRun:output_type -> sdk.v1.WaitLiveRunResponse
	12, // 52: sdk.v1.SdkAgentService.GetRun:output_type -> sdk.v1.GetRunResponse
	14, // 53: sdk.v1.SdkAgentService.ListRuns:output_type -> sdk.v1.ListRunsResponse
	16, // 54: sdk.v1.SdkAgentService.GetRunConversation:output_type -> sdk.v1.GetRunConversationResponse
	53, // 55: sdk.v1.SdkAgentService.ObserveRun:output_type -> sdk.v1.RunStreamMessage
	19, // 56: sdk.v1.SdkAgentService.CancelRun:output_type -> sdk.v1.CancelRunResponse
	21, // 57: sdk.v1.SdkAgentService.GetAgent:output_type -> sdk.v1.GetAgentResponse
	23, // 58: sdk.v1.SdkAgentService.ListAgents:output_type -> sdk.v1.ListAgentsResponse
	25, // 59: sdk.v1.SdkAgentService.ArchiveAgent:output_type -> sdk.v1.ArchiveAgentResponse
	27, // 60: sdk.v1.SdkAgentService.UnarchiveAgent:output_type -> sdk.v1.UnarchiveAgentResponse
	29, // 61: sdk.v1.SdkAgentService.DeleteAgent:output_type -> sdk.v1.DeleteAgentResponse
	31, // 62: sdk.v1.SdkAgentService.ListAgentMessages:output_type -> sdk.v1.ListAgentMessagesResponse
	33, // 63: sdk.v1.SdkAgentService.ListArtifacts:output_type -> sdk.v1.ListArtifactsResponse
	54, // 64: sdk.v1.SdkAgentService.DownloadArtifact:output_type -> sdk.v1.DownloadArtifactChunk
	36, // 65: sdk.v1.SdkAgentService.GetUsage:output_type -> sdk.v1.GetUsageResponse
	46, // [46:66] is the sub-list for method output_type
	26, // [26:46] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_sdk_v1_sdk_agent_service_proto_init() }
func file_sdk_v1_sdk_agent_service_proto_init() {
	if File_sdk_v1_sdk_agent_service_proto != nil {
		return
	}
	file_sdk_v1_sdk_messages_proto_init()
	file_sdk_v1_sdk_agent_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_sdk_v1_sdk_agent_service_proto_msgTypes[8].OneofWrappers = []any{}
	file_sdk_v1_sdk_agent_service_proto_msgTypes[17].OneofWrappers = []any{}
	file_sdk_v1_sdk_agent_service_proto_msgTypes[18].OneofWrappers = []any{}
	file_sdk_v1_sdk_agent_service_proto_msgTypes[35].OneofWrappers = []any{}
	file_sdk_v1_sdk_agent_service_proto_msgTypes[37].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_v1_sdk_agent_service_proto_rawDesc), len(file_sdk_v1_sdk_agent_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdk_v1_sdk_agent_service_proto_goTypes,
		DependencyIndexes: file_sdk_v1_sdk_agent_service_proto_depIdxs,
		MessageInfos:      file_sdk_v1_sdk_agent_service_proto_msgTypes,
	}.Build()
	File_sdk_v1_sdk_agent_service_proto = out.File
	file_sdk_v1_sdk_agent_service_proto_goTypes = nil
	file_sdk_v1_sdk_agent_service_proto_depIdxs = nil
}
