// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sdk/v1/sdk_store_callback_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Generic local agent-store operation forwarded to a host-owned substore.
type CallStoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Substore being addressed: "agents", "runs", "runEvents", or "checkpoints".
	Substore string `protobuf:"bytes,1,opt,name=substore,proto3" json:"substore,omitempty"`
	// Operation on the substore: "get", "create", "update", "delete", "list", or
	// "append" (runEvents only).
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// Operation input object. Checkpoint blob bytes are base64-encoded strings.
	Input         *structpb.Struct `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallStoreRequest) Reset() {
	*x = CallStoreRequest{}
	mi := &file_sdk_v1_sdk_store_callback_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallStoreRequest) ProtoMessage() {}

func (x *CallStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_store_callback_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallStoreRequest.ProtoReflect.Descriptor instead.
func (*CallStoreRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_store_callback_service_proto_rawDescGZIP(), []int{0}
}

func (x *CallStoreRequest) GetSubstore() string {
	if x != nil {
		return x.Substore
	}
	return ""
}

func (x *CallStoreRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallStoreRequest) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

type CallStoreResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation output object, or unset for a null result (for example a get
	// miss or a delete). Checkpoint blob bytes are base64-encoded strings.
	Output        *structpb.Struct `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallStoreResponse) Reset() {
	*x = CallStoreResponse{}
	mi := &file_sdk_v1_sdk_store_callback_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallStoreResponse) ProtoMessage() {}

func (x *CallStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_store_callback_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallStoreResponse.ProtoReflect.Descriptor instead.
func (*CallStoreResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_store_callback_service_proto_rawDescGZIP(), []int{1}
}

func (x *CallStoreResponse) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_sdk_v1_sdk_store_callback_service_proto protoreflect.FileDescriptor

const file_sdk_v1_sdk_store_callback_service_proto_rawDesc = "" +
	"\n" +
	"'sdk/v1/sdk_store_callback_service.proto\x12\x06sdk.v1\x1a\x1cgoogle/protobuf/struct.proto\"u\n" +
	"\x10CallStoreRequest\x12\x1a\n" +
	"\bsubstore\x18\x01 \x01(\tR\bsubstore\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12-\n" +
	"\x05input\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05input\"D\n" +
	"\x11CallStoreResponse\x12/\n" +
	"\x06output\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06output2[\n" +
	"\x17SdkStoreCallbackService\x12@\n" +
	"\tCallStore\x12\x18.sdk.v1.CallStoreRequest\x1a\x19.sdk.v1.CallStoreResponseBt\n" +
	"\x11com.cursor.sdk.v1P\x01Z-github.com/orvice/butter-box/pkg/proto/sdk/v1\xaa\x02\rCursor.Sdk.V1\xba\x02\vCursorSdkV1\xea\x02\x0fCursor::Sdk::V1b\x06proto3"

var (
	file_sdk_v1_sdk_store_callback_service_proto_rawDescOnce sync.Once
	file_sdk_v1_sdk_store_callback_service_proto_rawDescData []byte
)

func file_sdk_v1_sdk_store_callback_service_proto_rawDescGZIP() []byte {
	file_sdk_v1_sdk_store_callback_service_proto_rawDescOnce.Do(func() {
		file_sdk_v1_sdk_store_callback_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_v1_sdk_store_callback_service_proto_rawDesc), len(file_sdk_v1_sdk_store_callback_service_proto_rawDesc)))
	})
	return file_sdk_v1_sdk_store_callback_service_proto_rawDescData
}

var file_sdk_v1_sdk_store_callback_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sdk_v1_sdk_store_callback_service_proto_goTypes = []any{
	(*CallStoreRequest)(nil),  // 0: sdk.v1.CallStoreRequest
	(*CallStoreResponse)(nil), // 1: sdk.v1.CallStoreResponse
	(*structpb.Struct)(nil),   // 2: google.protobuf.Struct
}
var file_sdk_v1_sdk_store_callback_service_proto_depIdxs = []int32{
	2, // 0: sdk.v1.CallStoreRequest.input:type_name -> google.protobuf.Struct
	2, // 1: sdk.v1.CallStoreResponse.output:type_name -> google.protobuf.Struct
	0, // 2: sdk.v1.SdkStoreCallbackService.CallStore:input_type -> sdk.v1.CallStoreRequest
	1, // 3: sdk.v1.SdkStoreCallbackService.CallStore:output_type -> sdk.v1.CallStoreResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sdk_v1_sdk_store_callback_service_proto_init() }
func file_sdk_v1_sdk_store_callback_service_proto_init() {
	if File_sdk_v1_sdk_store_callback_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_v1_sdk_store_callback_service_proto_rawDesc), len(file_sdk_v1_sdk_store_callback_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdk_v1_sdk_store_callback_service_proto_goTypes,
		DependencyIndexes: file_sdk_v1_sdk_store_callback_service_proto_depIdxs,
		MessageInfos:      file_sdk_v1_sdk_store_callback_service_proto_msgTypes,
	}.Build()
	File_sdk_v1_sdk_store_callback_service_proto = out.File
	file_sdk_v1_sdk_store_callback_service_proto_goTypes = nil
	file_sdk_v1_sdk_store_callback_service_proto_depIdxs = nil
}
