// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sdk/v1/sdk_cursor_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CursorRequestOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cursor API key. When empty, the bridge may fall back to process env
	// (e.g. CURSOR_API_KEY) depending on how it was launched.
	ApiKey        string `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorRequestOptions) Reset() {
	*x = CursorRequestOptions{}
	mi := &file_sdk_v1_sdk_cursor_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorRequestOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorRequestOptions) ProtoMessage() {}

func (x *CursorRequestOptions) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_cursor_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorRequestOptions.ProtoReflect.Descriptor instead.
func (*CursorRequestOptions) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_cursor_service_proto_rawDescGZIP(), []int{0}
}

func (x *CursorRequestOptions) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type MeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *CursorRequestOptions  `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeRequest) Reset() {
	*x = MeRequest{}
	mi := &file_sdk_v1_sdk_cursor_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeRequest) ProtoMessage() {}

func (x *MeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_cursor_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeRequest.ProtoReflect.Descriptor instead.
func (*MeRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_cursor_service_proto_rawDescGZIP(), []int{1}
}

func (x *MeRequest) GetOptions() *CursorRequestOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type MeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *SdkUser               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeResponse) Reset() {
	*x = MeResponse{}
	mi := &file_sdk_v1_sdk_cursor_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeResponse) ProtoMessage() {}

func (x *MeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_cursor_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeResponse.ProtoReflect.Descriptor instead.
func (*MeResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_cursor_service_proto_rawDescGZIP(), []int{2}
}

func (x *MeResponse) GetUser() *SdkUser {
	if x != nil {
		return x.User
	}
	return nil
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *CursorRequestOptions  `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_sdk_v1_sdk_cursor_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_cursor_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_cursor_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListModelsRequest) GetOptions() *CursorRequestOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SdkModel            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_sdk_v1_sdk_cursor_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_cursor_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_cursor_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListModelsResponse) GetItems() []*SdkModel {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListRepositoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *CursorRequestOptions  `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepositoriesRequest) Reset() {
	*x = ListRepositoriesRequest{}
	mi := &file_sdk_v1_sdk_cursor_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepositoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepositoriesRequest) ProtoMessage() {}

func (x *ListRepositoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_cursor_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepositoriesRequest.ProtoReflect.Descriptor instead.
func (*ListRepositoriesRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_cursor_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListRepositoriesRequest) GetOptions() *CursorRequestOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListRepositoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SdkRepository       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRepositoriesResponse) Reset() {
	*x = ListRepositoriesResponse{}
	mi := &file_sdk_v1_sdk_cursor_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRepositoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRepositoriesResponse) ProtoMessage() {}

func (x *ListRepositoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_cursor_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRepositoriesResponse.ProtoReflect.Descriptor instead.
func (*ListRepositoriesResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_cursor_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListRepositoriesResponse) GetItems() []*SdkRepository {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_sdk_v1_sdk_cursor_service_proto protoreflect.FileDescriptor

const file_sdk_v1_sdk_cursor_service_proto_rawDesc = "" +
	"\n" +
	"\x1fsdk/v1/sdk_cursor_service.proto\x12\x06sdk.v1\x1a\x19sdk/v1/sdk_messages.proto\"/\n" +
	"\x14CursorRequestOptions\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"C\n" +
	"\tMeRequest\x126\n" +
	"\aoptions\x18\x01 \x01(\v2\x1c.sdk.v1.CursorRequestOptionsR\aoptions\"1\n" +
	"\n" +
	"MeResponse\x12#\n" +
	"\x04user\x18\x01 \x01(\v2\x0f.sdk.v1.SdkUserR\x04user\"K\n" +
	"\x11ListModelsRequest\x126\n" +
	"\aoptions\x18\x01 \x01(\v2\x1c.sdk.v1.CursorRequestOptionsR\aoptions\"<\n" +
	"\x12ListModelsResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.sdk.v1.SdkModelR\x05items\"Q\n" +
	"\x17ListRepositoriesRequest\x126\n" +
	"\aoptions\x18\x01 \x01(\v2\x1c.sdk.v1.CursorRequestOptionsR\aoptions\"G\n" +
	"\x18ListRepositoriesResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.sdk.v1.SdkRepositoryR\x05items2\xdb\x01\n" +
	"\x10SdkCursorService\x12+\n" +
	"\x02Me\x12\x11.sdk.v1.MeRequest\x1a\x12.sdk.v1.MeResponse\x12C\n" +
	"\n" +
	"ListModels\x12\x19.sdk.v1.ListModelsRequest\x1a\x1a.sdk.v1.ListModelsResponse\x12U\n" +
	"\x10ListRepositories\x12\x1f.sdk.v1.ListRepositoriesRequest\x1a .sdk.v1.ListRepositoriesResponseBt\n" +
	"\x11com.cursor.sdk.v1P\x01Z-github.com/orvice/butter-box/pkg/proto/sdk/v1\xaa\x02\rCursor.Sdk.V1\xba\x02\vCursorSdkV1\xea\x02\x0fCursor::Sdk::V1b\x06proto3"

var (
	file_sdk_v1_sdk_cursor_service_proto_rawDescOnce sync.Once
	file_sdk_v1_sdk_cursor_service_proto_rawDescData []byte
)

func file_sdk_v1_sdk_cursor_service_proto_rawDescGZIP() []byte {
	file_sdk_v1_sdk_cursor_service_proto_rawDescOnce.Do(func() {
		file_sdk_v1_sdk_cursor_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_v1_sdk_cursor_service_proto_rawDesc), len(file_sdk_v1_sdk_cursor_service_proto_rawDesc)))
	})
	return file_sdk_v1_sdk_cursor_service_proto_rawDescData
}

var file_sdk_v1_sdk_cursor_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sdk_v1_sdk_cursor_service_proto_goTypes = []any{
	(*CursorRequestOptions)(nil),     // 0: sdk.v1.CursorRequestOptions
	(*MeRequest)(nil),                // 1: sdk.v1.MeRequest
	(*MeResponse)(nil),               // 2: sdk.v1.MeResponse
	(*ListModelsRequest)(nil),        // 3: sdk.v1.ListModelsRequest
	(*ListModelsResponse)(nil),       // 4: sdk.v1.ListModelsResponse
	(*ListRepositoriesRequest)(nil),  // 5: sdk.v1.ListRepositoriesRequest
	(*ListRepositoriesResponse)(nil), // 6: sdk.v1.ListRepositoriesResponse
	(*SdkUser)(nil),                  // 7: sdk.v1.SdkUser
	(*SdkModel)(nil),                 // 8: sdk.v1.SdkModel
	(*SdkRepository)(nil),            // 9: sdk.v1.SdkRepository
}
var file_sdk_v1_sdk_cursor_service_proto_depIdxs = []int32{
	0, // 0: sdk.v1.MeRequest.options:type_name -> sdk.v1.CursorRequestOptions
	7, // 1: sdk.v1.MeResponse.user:type_name -> sdk.v1.SdkUser
	0, // 2: sdk.v1.ListModelsRequest.options:type_name -> sdk.v1.CursorRequestOptions
	8, // 3: sdk.v1.ListModelsResponse.items:type_name -> sdk.v1.SdkModel
	0, // 4: sdk.v1.ListRepositoriesRequest.options:type_name -> sdk.v1.CursorRequestOptions
	9, // 5: sdk.v1.ListRepositoriesResponse.items:type_name -> sdk.v1.SdkRepository
	1, // 6: sdk.v1.SdkCursorService.Me:input_type -> sdk.v1.MeRequest
	3, // 7: sdk.v1.SdkCursorService.ListModels:input_type -> sdk.v1.ListModelsRequest
	5, // 8: sdk.v1.SdkCursorService.ListRepositories:input_type -> sdk.v1.ListRepositoriesRequest
	2, // 9: sdk.v1.SdkCursorService.Me:output_type -> sdk.v1.MeResponse
	4, // 10: sdk.v1.SdkCursorService.ListModels:output_type -> sdk.v1.ListModelsResponse
	6, // 11: sdk.v1.SdkCursorService.ListRepositories:output_type -> sdk.v1.ListRepositoriesResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_sdk_v1_sdk_cursor_service_proto_init() }
func file_sdk_v1_sdk_cursor_service_proto_init() {
	if File_sdk_v1_sdk_cursor_service_proto != nil {
		return
	}
	file_sdk_v1_sdk_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_v1_sdk_cursor_service_proto_rawDesc), len(file_sdk_v1_sdk_cursor_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdk_v1_sdk_cursor_service_proto_goTypes,
		DependencyIndexes: file_sdk_v1_sdk_cursor_service_proto_depIdxs,
		MessageInfos:      file_sdk_v1_sdk_cursor_service_proto_msgTypes,
	}.Build()
	File_sdk_v1_sdk_cursor_service_proto = out.File
	file_sdk_v1_sdk_cursor_service_proto_goTypes = nil
	file_sdk_v1_sdk_cursor_service_proto_depIdxs = nil
}
