// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sdk/v1/sdk_errors.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stable error codes returned by the bridge on failed RPCs.
//
// Codes are attached to Connect/gRPC errors via SdkErrorDetails so language
// SDKs can branch on a stable taxonomy instead of parsing free-form messages.
type SdkErrorCode int32

const (
	SdkErrorCode_SDK_ERROR_CODE_UNSPECIFIED          SdkErrorCode = 0
	SdkErrorCode_SDK_ERROR_CODE_UNAUTHORIZED         SdkErrorCode = 1
	SdkErrorCode_SDK_ERROR_CODE_API_KEY_NOT_FOUND    SdkErrorCode = 2
	SdkErrorCode_SDK_ERROR_CODE_PLAN_REQUIRED        SdkErrorCode = 3
	SdkErrorCode_SDK_ERROR_CODE_ROLE_FORBIDDEN       SdkErrorCode = 4
	SdkErrorCode_SDK_ERROR_CODE_FEATURE_UNAVAILABLE  SdkErrorCode = 5
	SdkErrorCode_SDK_ERROR_CODE_AGENT_NOT_FOUND      SdkErrorCode = 6
	SdkErrorCode_SDK_ERROR_CODE_RUN_NOT_FOUND        SdkErrorCode = 7
	SdkErrorCode_SDK_ERROR_CODE_VALIDATION_ERROR     SdkErrorCode = 8
	SdkErrorCode_SDK_ERROR_CODE_INVALID_MODEL        SdkErrorCode = 9
	SdkErrorCode_SDK_ERROR_CODE_INVALID_BRANCH_NAME  SdkErrorCode = 10
	SdkErrorCode_SDK_ERROR_CODE_REPOSITORY_REQUIRED  SdkErrorCode = 11
	SdkErrorCode_SDK_ERROR_CODE_REPOSITORY_ACCESS    SdkErrorCode = 12
	SdkErrorCode_SDK_ERROR_CODE_PR_RESOLUTION_FAILED SdkErrorCode = 13
	SdkErrorCode_SDK_ERROR_CODE_USAGE_LIMIT_EXCEEDED SdkErrorCode = 14
	SdkErrorCode_SDK_ERROR_CODE_AGENT_BUSY           SdkErrorCode = 15
	SdkErrorCode_SDK_ERROR_CODE_AGENT_ARCHIVED       SdkErrorCode = 16
	SdkErrorCode_SDK_ERROR_CODE_RUN_NOT_CANCELLABLE  SdkErrorCode = 17
	SdkErrorCode_SDK_ERROR_CODE_RATE_LIMIT_EXCEEDED  SdkErrorCode = 18
	SdkErrorCode_SDK_ERROR_CODE_UPSTREAM_ERROR       SdkErrorCode = 19
	SdkErrorCode_SDK_ERROR_CODE_INTERNAL_ERROR       SdkErrorCode = 20
	SdkErrorCode_SDK_ERROR_CODE_CLIENT_CANCELLED     SdkErrorCode = 21
)

// Enum value maps for SdkErrorCode.
var (
	SdkErrorCode_name = map[int32]string{
		0:  "SDK_ERROR_CODE_UNSPECIFIED",
		1:  "SDK_ERROR_CODE_UNAUTHORIZED",
		2:  "SDK_ERROR_CODE_API_KEY_NOT_FOUND",
		3:  "SDK_ERROR_CODE_PLAN_REQUIRED",
		4:  "SDK_ERROR_CODE_ROLE_FORBIDDEN",
		5:  "SDK_ERROR_CODE_FEATURE_UNAVAILABLE",
		6:  "SDK_ERROR_CODE_AGENT_NOT_FOUND",
		7:  "SDK_ERROR_CODE_RUN_NOT_FOUND",
		8:  "SDK_ERROR_CODE_VALIDATION_ERROR",
		9:  "SDK_ERROR_CODE_INVALID_MODEL",
		10: "SDK_ERROR_CODE_INVALID_BRANCH_NAME",
		11: "SDK_ERROR_CODE_REPOSITORY_REQUIRED",
		12: "SDK_ERROR_CODE_REPOSITORY_ACCESS",
		13: "SDK_ERROR_CODE_PR_RESOLUTION_FAILED",
		14: "SDK_ERROR_CODE_USAGE_LIMIT_EXCEEDED",
		15: "SDK_ERROR_CODE_AGENT_BUSY",
		16: "SDK_ERROR_CODE_AGENT_ARCHIVED",
		17: "SDK_ERROR_CODE_RUN_NOT_CANCELLABLE",
		18: "SDK_ERROR_CODE_RATE_LIMIT_EXCEEDED",
		19: "SDK_ERROR_CODE_UPSTREAM_ERROR",
		20: "SDK_ERROR_CODE_INTERNAL_ERROR",
		21: "SDK_ERROR_CODE_CLIENT_CANCELLED",
	}
	SdkErrorCode_value = map[string]int32{
		"SDK_ERROR_CODE_UNSPECIFIED":          0,
		"SDK_ERROR_CODE_UNAUTHORIZED":         1,
		"SDK_ERROR_CODE_API_KEY_NOT_FOUND":    2,
		"SDK_ERROR_CODE_PLAN_REQUIRED":        3,
		"SDK_ERROR_CODE_ROLE_FORBIDDEN":       4,
		"SDK_ERROR_CODE_FEATURE_UNAVAILABLE":  5,
		"SDK_ERROR_CODE_AGENT_NOT_FOUND":      6,
		"SDK_ERROR_CODE_RUN_NOT_FOUND":        7,
		"SDK_ERROR_CODE_VALIDATION_ERROR":     8,
		"SDK_ERROR_CODE_INVALID_MODEL":        9,
		"SDK_ERROR_CODE_INVALID_BRANCH_NAME":  10,
		"SDK_ERROR_CODE_REPOSITORY_REQUIRED":  11,
		"SDK_ERROR_CODE_REPOSITORY_ACCESS":    12,
		"SDK_ERROR_CODE_PR_RESOLUTION_FAILED": 13,
		"SDK_ERROR_CODE_USAGE_LIMIT_EXCEEDED": 14,
		"SDK_ERROR_CODE_AGENT_BUSY":           15,
		"SDK_ERROR_CODE_AGENT_ARCHIVED":       16,
		"SDK_ERROR_CODE_RUN_NOT_CANCELLABLE":  17,
		"SDK_ERROR_CODE_RATE_LIMIT_EXCEEDED":  18,
		"SDK_ERROR_CODE_UPSTREAM_ERROR":       19,
		"SDK_ERROR_CODE_INTERNAL_ERROR":       20,
		"SDK_ERROR_CODE_CLIENT_CANCELLED":     21,
	}
)

func (x SdkErrorCode) Enum() *SdkErrorCode {
	p := new(SdkErrorCode)
	*p = x
	return p
}

func (x SdkErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SdkErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_v1_sdk_errors_proto_enumTypes[0].Descriptor()
}

func (SdkErrorCode) Type() protoreflect.EnumType {
	return &file_sdk_v1_sdk_errors_proto_enumTypes[0]
}

func (x SdkErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SdkErrorCode.Descriptor instead.
func (SdkErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_errors_proto_rawDescGZIP(), []int{0}
}

// Rate-limit metadata when the upstream response includes it.
type RateLimitInfo struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Limit     *uint64                `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Remaining *uint64                `protobuf:"varint,2,opt,name=remaining,proto3,oneof" json:"remaining,omitempty"`
	// Unix epoch seconds when the rate-limit window resets.
	ResetEpochSeconds *uint64 `protobuf:"varint,3,opt,name=reset_epoch_seconds,json=resetEpochSeconds,proto3,oneof" json:"reset_epoch_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RateLimitInfo) Reset() {
	*x = RateLimitInfo{}
	mi := &file_sdk_v1_sdk_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitInfo) ProtoMessage() {}

func (x *RateLimitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitInfo.ProtoReflect.Descriptor instead.
func (*RateLimitInfo) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_errors_proto_rawDescGZIP(), []int{0}
}

func (x *RateLimitInfo) GetLimit() uint64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *RateLimitInfo) GetRemaining() uint64 {
	if x != nil && x.Remaining != nil {
		return *x.Remaining
	}
	return 0
}

func (x *RateLimitInfo) GetResetEpochSeconds() uint64 {
	if x != nil && x.ResetEpochSeconds != nil {
		return *x.ResetEpochSeconds
	}
	return 0
}

// Structured error details attached to Connect/gRPC errors from the bridge.
type SdkErrorDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full request ID from Cursor Cloud, when available. Prefer logging and
	// displaying the complete value.
	RequestId    *string      `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	SdkErrorCode SdkErrorCode `protobuf:"varint,2,opt,name=sdk_error_code,json=sdkErrorCode,proto3,enum=sdk.v1.SdkErrorCode" json:"sdk_error_code,omitempty"`
	// Human-readable summary suitable for display or logs.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Optional link to docs or remediation guidance.
	HelpUrl *string `protobuf:"bytes,4,opt,name=help_url,json=helpUrl,proto3,oneof" json:"help_url,omitempty"`
	// Upstream provider name when the failure originated outside Cursor.
	Provider *string `protobuf:"bytes,5,opt,name=provider,proto3,oneof" json:"provider,omitempty"`
	// Suggested wait before retrying, when known.
	RetryAfter    *durationpb.Duration `protobuf:"bytes,6,opt,name=retry_after,json=retryAfter,proto3,oneof" json:"retry_after,omitempty"`
	RateLimit     *RateLimitInfo       `protobuf:"bytes,7,opt,name=rate_limit,json=rateLimit,proto3,oneof" json:"rate_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SdkErrorDetails) Reset() {
	*x = SdkErrorDetails{}
	mi := &file_sdk_v1_sdk_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SdkErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SdkErrorDetails) ProtoMessage() {}

func (x *SdkErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SdkErrorDetails.ProtoReflect.Descriptor instead.
func (*SdkErrorDetails) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_errors_proto_rawDescGZIP(), []int{1}
}

func (x *SdkErrorDetails) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

func (x *SdkErrorDetails) GetSdkErrorCode() SdkErrorCode {
	if x != nil {
		return x.SdkErrorCode
	}
	return SdkErrorCode_SDK_ERROR_CODE_UNSPECIFIED
}

func (x *SdkErrorDetails) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SdkErrorDetails) GetHelpUrl() string {
	if x != nil && x.HelpUrl != nil {
		return *x.HelpUrl
	}
	return ""
}

func (x *SdkErrorDetails) GetProvider() string {
	if x != nil && x.Provider != nil {
		return *x.Provider
	}
	return ""
}

func (x *SdkErrorDetails) GetRetryAfter() *durationpb.Duration {
	if x != nil {
		return x.RetryAfter
	}
	return nil
}

func (x *SdkErrorDetails) GetRateLimit() *RateLimitInfo {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

var File_sdk_v1_sdk_errors_proto protoreflect.FileDescriptor

const file_sdk_v1_sdk_errors_proto_rawDesc = "" +
	"\n" +
	"\x17sdk/v1/sdk_errors.proto\x12\x06sdk.v1\x1a\x1egoogle/protobuf/duration.proto\"\xb2\x01\n" +
	"\rRateLimitInfo\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x04H\x00R\x05limit\x88\x01\x01\x12!\n" +
	"\tremaining\x18\x02 \x01(\x04H\x01R\tremaining\x88\x01\x01\x123\n" +
	"\x13reset_epoch_seconds\x18\x03 \x01(\x04H\x02R\x11resetEpochSeconds\x88\x01\x01B\b\n" +
	"\x06_limitB\f\n" +
	"\n" +
	"_remainingB\x16\n" +
	"\x14_reset_epoch_seconds\"\x90\x03\n" +
	"\x0fSdkErrorDetails\x12\"\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tH\x00R\trequestId\x88\x01\x01\x12:\n" +
	"\x0esdk_error_code\x18\x02 \x01(\x0e2\x14.sdk.v1.SdkErrorCodeR\fsdkErrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1e\n" +
	"\bhelp_url\x18\x04 \x01(\tH\x01R\ahelpUrl\x88\x01\x01\x12\x1f\n" +
	"\bprovider\x18\x05 \x01(\tH\x02R\bprovider\x88\x01\x01\x12?\n" +
	"\vretry_after\x18\x06 \x01(\v2\x19.google.protobuf.DurationH\x03R\n" +
	"retryAfter\x88\x01\x01\x129\n" +
	"\n" +
	"rate_limit\x18\a \x01(\v2\x15.sdk.v1.RateLimitInfoH\x04R\trateLimit\x88\x01\x01B\r\n" +
	"\v_request_idB\v\n" +
	"\t_help_urlB\v\n" +
	"\t_providerB\x0e\n" +
	"\f_retry_afterB\r\n" +
	"\v_rate_limit*\xb4\x06\n" +
	"\fSdkErrorCode\x12\x1e\n" +
	"\x1aSDK_ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bSDK_ERROR_CODE_UNAUTHORIZED\x10\x01\x12$\n" +
	" SDK_ERROR_CODE_API_KEY_NOT_FOUND\x10\x02\x12 \n" +
	"\x1cSDK_ERROR_CODE_PLAN_REQUIRED\x10\x03\x12!\n" +
	"\x1dSDK_ERROR_CODE_ROLE_FORBIDDEN\x10\x04\x12&\n" +
	"\"SDK_ERROR_CODE_FEATURE_UNAVAILABLE\x10\x05\x12\"\n" +
	"\x1eSDK_ERROR_CODE_AGENT_NOT_FOUND\x10\x06\x12 \n" +
	"\x1cSDK_ERROR_CODE_RUN_NOT_FOUND\x10\a\x12#\n" +
	"\x1fSDK_ERROR_CODE_VALIDATION_ERROR\x10\b\x12 \n" +
	"\x1cSDK_ERROR_CODE_INVALID_MODEL\x10\t\x12&\n" +
	"\"SDK_ERROR_CODE_INVALID_BRANCH_NAME\x10\n" +
	"\x12&\n" +
	"\"SDK_ERROR_CODE_REPOSITORY_REQUIRED\x10\v\x12$\n" +
	" SDK_ERROR_CODE_REPOSITORY_ACCESS\x10\f\x12'\n" +
	"#SDK_ERROR_CODE_PR_RESOLUTION_FAILED\x10\r\x12'\n" +
	"#SDK_ERROR_CODE_USAGE_LIMIT_EXCEEDED\x10\x0e\x12\x1d\n" +
	"\x19SDK_ERROR_CODE_AGENT_BUSY\x10\x0f\x12!\n" +
	"\x1dSDK_ERROR_CODE_AGENT_ARCHIVED\x10\x10\x12&\n" +
	"\"SDK_ERROR_CODE_RUN_NOT_CANCELLABLE\x10\x11\x12&\n" +
	"\"SDK_ERROR_CODE_RATE_LIMIT_EXCEEDED\x10\x12\x12!\n" +
	"\x1dSDK_ERROR_CODE_UPSTREAM_ERROR\x10\x13\x12!\n" +
	"\x1dSDK_ERROR_CODE_INTERNAL_ERROR\x10\x14\x12#\n" +
	"\x1fSDK_ERROR_CODE_CLIENT_CANCELLED\x10\x15Bt\n" +
	"\x11com.cursor.sdk.v1P\x01Z-github.com/orvice/butter-box/pkg/proto/sdk/v1\xaa\x02\rCursor.Sdk.V1\xba\x02\vCursorSdkV1\xea\x02\x0fCursor::Sdk::V1b\x06proto3"

var (
	file_sdk_v1_sdk_errors_proto_rawDescOnce sync.Once
	file_sdk_v1_sdk_errors_proto_rawDescData []byte
)

func file_sdk_v1_sdk_errors_proto_rawDescGZIP() []byte {
	file_sdk_v1_sdk_errors_proto_rawDescOnce.Do(func() {
		file_sdk_v1_sdk_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_v1_sdk_errors_proto_rawDesc), len(file_sdk_v1_sdk_errors_proto_rawDesc)))
	})
	return file_sdk_v1_sdk_errors_proto_rawDescData
}

var file_sdk_v1_sdk_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_v1_sdk_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sdk_v1_sdk_errors_proto_goTypes = []any{
	(SdkErrorCode)(0),           // 0: sdk.v1.SdkErrorCode
	(*RateLimitInfo)(nil),       // 1: sdk.v1.RateLimitInfo
	(*SdkErrorDetails)(nil),     // 2: sdk.v1.SdkErrorDetails
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
}
var file_sdk_v1_sdk_errors_proto_depIdxs = []int32{
	0, // 0: sdk.v1.SdkErrorDetails.sdk_error_code:type_name -> sdk.v1.SdkErrorCode
	3, // 1: sdk.v1.SdkErrorDetails.retry_after:type_name -> google.protobuf.Duration
	1, // 2: sdk.v1.SdkErrorDetails.rate_limit:type_name -> sdk.v1.RateLimitInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sdk_v1_sdk_errors_proto_init() }
func file_sdk_v1_sdk_errors_proto_init() {
	if File_sdk_v1_sdk_errors_proto != nil {
		return
	}
	file_sdk_v1_sdk_errors_proto_msgTypes[0].OneofWrappers = []any{}
	file_sdk_v1_sdk_errors_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_v1_sdk_errors_proto_rawDesc), len(file_sdk_v1_sdk_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_v1_sdk_errors_proto_goTypes,
		DependencyIndexes: file_sdk_v1_sdk_errors_proto_depIdxs,
		EnumInfos:         file_sdk_v1_sdk_errors_proto_enumTypes,
		MessageInfos:      file_sdk_v1_sdk_errors_proto_msgTypes,
	}.Build()
	File_sdk_v1_sdk_errors_proto = out.File
	file_sdk_v1_sdk_errors_proto_goTypes = nil
	file_sdk_v1_sdk_errors_proto_depIdxs = nil
}
