// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sdk/v1/sdk_bridge_control_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_sdk_v1_sdk_bridge_control_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_bridge_control_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_bridge_control_service_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_sdk_v1_sdk_bridge_control_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_bridge_control_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_bridge_control_service_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ShutdownRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Seconds to wait for in-flight RPCs before forcing exit. Zero means
	// immediate shutdown.
	GraceSeconds  uint32 `protobuf:"varint,1,opt,name=grace_seconds,json=graceSeconds,proto3" json:"grace_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_sdk_v1_sdk_bridge_control_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_bridge_control_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_bridge_control_service_proto_rawDescGZIP(), []int{2}
}

func (x *ShutdownRequest) GetGraceSeconds() uint32 {
	if x != nil {
		return x.GraceSeconds
	}
	return 0
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_sdk_v1_sdk_bridge_control_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_bridge_control_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_bridge_control_service_proto_rawDescGZIP(), []int{3}
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_sdk_v1_sdk_bridge_control_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_bridge_control_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_bridge_control_service_proto_rawDescGZIP(), []int{4}
}

type GetVersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Semver (or equivalent) of the bridge binary.
	BridgeVersion string `protobuf:"bytes,1,opt,name=bridge_version,json=bridgeVersion,proto3" json:"bridge_version,omitempty"`
	// Version of this sdk.v1 protocol contract the bridge implements.
	ProtocolVersion string `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Feature strings the bridge supports (for client capability negotiation).
	Capabilities  []string `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_sdk_v1_sdk_bridge_control_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_bridge_control_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_bridge_control_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetVersionResponse) GetBridgeVersion() string {
	if x != nil {
		return x.BridgeVersion
	}
	return ""
}

func (x *GetVersionResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *GetVersionResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type SetToolCallbackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Connect base URL of the host custom-tool callback server. Empty clears the
	// currently configured callback.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Bearer token the bridge presents on CallCustomTool RPCs.
	AuthToken     string `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetToolCallbackRequest) Reset() {
	*x = SetToolCallbackRequest{}
	mi := &file_sdk_v1_sdk_bridge_control_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetToolCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetToolCallbackRequest) ProtoMessage() {}

func (x *SetToolCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_bridge_control_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetToolCallbackRequest.ProtoReflect.Descriptor instead.
func (*SetToolCallbackRequest) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_bridge_control_service_proto_rawDescGZIP(), []int{6}
}

func (x *SetToolCallbackRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SetToolCallbackRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type SetToolCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetToolCallbackResponse) Reset() {
	*x = SetToolCallbackResponse{}
	mi := &file_sdk_v1_sdk_bridge_control_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetToolCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetToolCallbackResponse) ProtoMessage() {}

func (x *SetToolCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_v1_sdk_bridge_control_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetToolCallbackResponse.ProtoReflect.Descriptor instead.
func (*SetToolCallbackResponse) Descriptor() ([]byte, []int) {
	return file_sdk_v1_sdk_bridge_control_service_proto_rawDescGZIP(), []int{7}
}

var File_sdk_v1_sdk_bridge_control_service_proto protoreflect.FileDescriptor

const file_sdk_v1_sdk_bridge_control_service_proto_rawDesc = "" +
	"\n" +
	"'sdk/v1/sdk_bridge_control_service.proto\x12\x06sdk.v1\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"6\n" +
	"\x0fShutdownRequest\x12#\n" +
	"\rgrace_seconds\x18\x01 \x01(\rR\fgraceSeconds\"\x12\n" +
	"\x10ShutdownResponse\"\x13\n" +
	"\x11GetVersionRequest\"\x8a\x01\n" +
	"\x12GetVersionResponse\x12%\n" +
	"\x0ebridge_version\x18\x01 \x01(\tR\rbridgeVersion\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"I\n" +
	"\x16SetToolCallbackRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\"\x19\n" +
	"\x17SetToolCallbackResponse2\xa4\x02\n" +
	"\x17SdkBridgeControlService\x121\n" +
	"\x04Ping\x12\x13.sdk.v1.PingRequest\x1a\x14.sdk.v1.PingResponse\x12=\n" +
	"\bShutdown\x12\x17.sdk.v1.ShutdownRequest\x1a\x18.sdk.v1.ShutdownResponse\x12C\n" +
	"\n" +
	"GetVersion\x12\x19.sdk.v1.GetVersionRequest\x1a\x1a.sdk.v1.GetVersionResponse\x12R\n" +
	"\x0fSetToolCallback\x12\x1e.sdk.v1.SetToolCallbackRequest\x1a\x1f.sdk.v1.SetToolCallbackResponseBt\n" +
	"\x11com.cursor.sdk.v1P\x01Z-github.com/orvice/butter-box/pkg/proto/sdk/v1\xaa\x02\rCursor.Sdk.V1\xba\x02\vCursorSdkV1\xea\x02\x0fCursor::Sdk::V1b\x06proto3"

var (
	file_sdk_v1_sdk_bridge_control_service_proto_rawDescOnce sync.Once
	file_sdk_v1_sdk_bridge_control_service_proto_rawDescData []byte
)

func file_sdk_v1_sdk_bridge_control_service_proto_rawDescGZIP() []byte {
	file_sdk_v1_sdk_bridge_control_service_proto_rawDescOnce.Do(func() {
		file_sdk_v1_sdk_bridge_control_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_v1_sdk_bridge_control_service_proto_rawDesc), len(file_sdk_v1_sdk_bridge_control_service_proto_rawDesc)))
	})
	return file_sdk_v1_sdk_bridge_control_service_proto_rawDescData
}

var file_sdk_v1_sdk_bridge_control_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sdk_v1_sdk_bridge_control_service_proto_goTypes = []any{
	(*PingRequest)(nil),             // 0: sdk.v1.PingRequest
	(*PingResponse)(nil),            // 1: sdk.v1.PingResponse
	(*ShutdownRequest)(nil),         // 2: sdk.v1.ShutdownRequest
	(*ShutdownResponse)(nil),        // 3: sdk.v1.ShutdownResponse
	(*GetVersionRequest)(nil),       // 4: sdk.v1.GetVersionRequest
	(*GetVersionResponse)(nil),      // 5: sdk.v1.GetVersionResponse
	(*SetToolCallbackRequest)(nil),  // 6: sdk.v1.SetToolCallbackRequest
	(*SetToolCallbackResponse)(nil), // 7: sdk.v1.SetToolCallbackResponse
}
var file_sdk_v1_sdk_bridge_control_service_proto_depIdxs = []int32{
	0, // 0: sdk.v1.SdkBridgeControlService.Ping:input_type -> sdk.v1.PingRequest
	2, // 1: sdk.v1.SdkBridgeControlService.Shutdown:input_type -> sdk.v1.ShutdownRequest
	4, // 2: sdk.v1.SdkBridgeControlService.GetVersion:input_type -> sdk.v1.GetVersionRequest
	6, // 3: sdk.v1.SdkBridgeControlService.SetToolCallback:input_type -> sdk.v1.SetToolCallbackRequest
	1, // 4: sdk.v1.SdkBridgeControlService.Ping:output_type -> sdk.v1.PingResponse
	3, // 5: sdk.v1.SdkBridgeControlService.Shutdown:output_type -> sdk.v1.ShutdownResponse
	5, // 6: sdk.v1.SdkBridgeControlService.GetVersion:output_type -> sdk.v1.GetVersionResponse
	7, // 7: sdk.v1.SdkBridgeControlService.SetToolCallback:output_type -> sdk.v1.SetToolCallbackResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdk_v1_sdk_bridge_control_service_proto_init() }
func file_sdk_v1_sdk_bridge_control_service_proto_init() {
	if File_sdk_v1_sdk_bridge_control_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_v1_sdk_bridge_control_service_proto_rawDesc), len(file_sdk_v1_sdk_bridge_control_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdk_v1_sdk_bridge_control_service_proto_goTypes,
		DependencyIndexes: file_sdk_v1_sdk_bridge_control_service_proto_depIdxs,
		MessageInfos:      file_sdk_v1_sdk_bridge_control_service_proto_msgTypes,
	}.Build()
	File_sdk_v1_sdk_bridge_control_service_proto = out.File
	file_sdk_v1_sdk_bridge_control_service_proto_goTypes = nil
	file_sdk_v1_sdk_bridge_control_service_proto_depIdxs = nil
}
