// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: butterbox/cursor/v1/cursor.proto

// The ButterBox CursorService contract. Keep field names and numbers stable;
// the Butter client consumes this surface over ConnectRPC.
package cursorv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/orvice/butter-box/pkg/proto/butterbox/cursor/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CursorServiceName is the fully-qualified name of the CursorService service.
	CursorServiceName = "butterbox.cursor.v1.CursorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CursorServiceCreateSessionProcedure is the fully-qualified name of the CursorService's
	// CreateSession RPC.
	CursorServiceCreateSessionProcedure = "/butterbox.cursor.v1.CursorService/CreateSession"
	// CursorServiceSendMessageProcedure is the fully-qualified name of the CursorService's SendMessage
	// RPC.
	CursorServiceSendMessageProcedure = "/butterbox.cursor.v1.CursorService/SendMessage"
	// CursorServiceAbortSessionProcedure is the fully-qualified name of the CursorService's
	// AbortSession RPC.
	CursorServiceAbortSessionProcedure = "/butterbox.cursor.v1.CursorService/AbortSession"
	// CursorServiceListModelsProcedure is the fully-qualified name of the CursorService's ListModels
	// RPC.
	CursorServiceListModelsProcedure = "/butterbox.cursor.v1.CursorService/ListModels"
)

// CursorServiceClient is a client for the butterbox.cursor.v1.CursorService service.
type CursorServiceClient interface {
	// CreateSession spawns a bridge process for one Cursor agent session and
	// returns its session ID.
	CreateSession(context.Context, *connect.Request[v1.CreateSessionRequest]) (*connect.Response[v1.CreateSessionResponse], error)
	// SendMessage sends one prompt and returns after the Cursor agent finishes
	// its turn. A box restart mid-run returns an error, never a stale answer.
	SendMessage(context.Context, *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.SendMessageResponse], error)
	// AbortSession cancels the in-flight run, if any, and stops the bridge
	// process. Session files stay on disk.
	AbortSession(context.Context, *connect.Request[v1.AbortSessionRequest]) (*connect.Response[v1.AbortSessionResponse], error)
	// ListModels reports the Cursor model catalog. It is session-less: a
	// transient bridge is started and stopped without consuming a session slot.
	ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error)
}

// NewCursorServiceClient constructs a client for the butterbox.cursor.v1.CursorService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCursorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CursorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	cursorServiceMethods := v1.File_butterbox_cursor_v1_cursor_proto.Services().ByName("CursorService").Methods()
	return &cursorServiceClient{
		createSession: connect.NewClient[v1.CreateSessionRequest, v1.CreateSessionResponse](
			httpClient,
			baseURL+CursorServiceCreateSessionProcedure,
			connect.WithSchema(cursorServiceMethods.ByName("CreateSession")),
			connect.WithClientOptions(opts...),
		),
		sendMessage: connect.NewClient[v1.SendMessageRequest, v1.SendMessageResponse](
			httpClient,
			baseURL+CursorServiceSendMessageProcedure,
			connect.WithSchema(cursorServiceMethods.ByName("SendMessage")),
			connect.WithClientOptions(opts...),
		),
		abortSession: connect.NewClient[v1.AbortSessionRequest, v1.AbortSessionResponse](
			httpClient,
			baseURL+CursorServiceAbortSessionProcedure,
			connect.WithSchema(cursorServiceMethods.ByName("AbortSession")),
			connect.WithClientOptions(opts...),
		),
		listModels: connect.NewClient[v1.ListModelsRequest, v1.ListModelsResponse](
			httpClient,
			baseURL+CursorServiceListModelsProcedure,
			connect.WithSchema(cursorServiceMethods.ByName("ListModels")),
			connect.WithClientOptions(opts...),
		),
	}
}

// cursorServiceClient implements CursorServiceClient.
type cursorServiceClient struct {
	createSession *connect.Client[v1.CreateSessionRequest, v1.CreateSessionResponse]
	sendMessage   *connect.Client[v1.SendMessageRequest, v1.SendMessageResponse]
	abortSession  *connect.Client[v1.AbortSessionRequest, v1.AbortSessionResponse]
	listModels    *connect.Client[v1.ListModelsRequest, v1.ListModelsResponse]
}

// CreateSession calls butterbox.cursor.v1.CursorService.CreateSession.
func (c *cursorServiceClient) CreateSession(ctx context.Context, req *connect.Request[v1.CreateSessionRequest]) (*connect.Response[v1.CreateSessionResponse], error) {
	return c.createSession.CallUnary(ctx, req)
}

// SendMessage calls butterbox.cursor.v1.CursorService.SendMessage.
func (c *cursorServiceClient) SendMessage(ctx context.Context, req *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.SendMessageResponse], error) {
	return c.sendMessage.CallUnary(ctx, req)
}

// AbortSession calls butterbox.cursor.v1.CursorService.AbortSession.
func (c *cursorServiceClient) AbortSession(ctx context.Context, req *connect.Request[v1.AbortSessionRequest]) (*connect.Response[v1.AbortSessionResponse], error) {
	return c.abortSession.CallUnary(ctx, req)
}

// ListModels calls butterbox.cursor.v1.CursorService.ListModels.
func (c *cursorServiceClient) ListModels(ctx context.Context, req *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	return c.listModels.CallUnary(ctx, req)
}

// CursorServiceHandler is an implementation of the butterbox.cursor.v1.CursorService service.
type CursorServiceHandler interface {
	// CreateSession spawns a bridge process for one Cursor agent session and
	// returns its session ID.
	CreateSession(context.Context, *connect.Request[v1.CreateSessionRequest]) (*connect.Response[v1.CreateSessionResponse], error)
	// SendMessage sends one prompt and returns after the Cursor agent finishes
	// its turn. A box restart mid-run returns an error, never a stale answer.
	SendMessage(context.Context, *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.SendMessageResponse], error)
	// AbortSession cancels the in-flight run, if any, and stops the bridge
	// process. Session files stay on disk.
	AbortSession(context.Context, *connect.Request[v1.AbortSessionRequest]) (*connect.Response[v1.AbortSessionResponse], error)
	// ListModels reports the Cursor model catalog. It is session-less: a
	// transient bridge is started and stopped without consuming a session slot.
	ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error)
}

// NewCursorServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCursorServiceHandler(svc CursorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	cursorServiceMethods := v1.File_butterbox_cursor_v1_cursor_proto.Services().ByName("CursorService").Methods()
	cursorServiceCreateSessionHandler := connect.NewUnaryHandler(
		CursorServiceCreateSessionProcedure,
		svc.CreateSession,
		connect.WithSchema(cursorServiceMethods.ByName("CreateSession")),
		connect.WithHandlerOptions(opts...),
	)
	cursorServiceSendMessageHandler := connect.NewUnaryHandler(
		CursorServiceSendMessageProcedure,
		svc.SendMessage,
		connect.WithSchema(cursorServiceMethods.ByName("SendMessage")),
		connect.WithHandlerOptions(opts...),
	)
	cursorServiceAbortSessionHandler := connect.NewUnaryHandler(
		CursorServiceAbortSessionProcedure,
		svc.AbortSession,
		connect.WithSchema(cursorServiceMethods.ByName("AbortSession")),
		connect.WithHandlerOptions(opts...),
	)
	cursorServiceListModelsHandler := connect.NewUnaryHandler(
		CursorServiceListModelsProcedure,
		svc.ListModels,
		connect.WithSchema(cursorServiceMethods.ByName("ListModels")),
		connect.WithHandlerOptions(opts...),
	)
	return "/butterbox.cursor.v1.CursorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CursorServiceCreateSessionProcedure:
			cursorServiceCreateSessionHandler.ServeHTTP(w, r)
		case CursorServiceSendMessageProcedure:
			cursorServiceSendMessageHandler.ServeHTTP(w, r)
		case CursorServiceAbortSessionProcedure:
			cursorServiceAbortSessionHandler.ServeHTTP(w, r)
		case CursorServiceListModelsProcedure:
			cursorServiceListModelsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCursorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCursorServiceHandler struct{}

func (UnimplementedCursorServiceHandler) CreateSession(context.Context, *connect.Request[v1.CreateSessionRequest]) (*connect.Response[v1.CreateSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("butterbox.cursor.v1.CursorService.CreateSession is not implemented"))
}

func (UnimplementedCursorServiceHandler) SendMessage(context.Context, *connect.Request[v1.SendMessageRequest]) (*connect.Response[v1.SendMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("butterbox.cursor.v1.CursorService.SendMessage is not implemented"))
}

func (UnimplementedCursorServiceHandler) AbortSession(context.Context, *connect.Request[v1.AbortSessionRequest]) (*connect.Response[v1.AbortSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("butterbox.cursor.v1.CursorService.AbortSession is not implemented"))
}

func (UnimplementedCursorServiceHandler) ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("butterbox.cursor.v1.CursorService.ListModels is not implemented"))
}
