// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: butterbox/pi/v1/pi.proto

package piv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional display name (pi session name, shown in pi-web listings).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional model provider (e.g. "anthropic"). Empty uses pi's default.
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	// Optional model pattern or ID as accepted by pi's --model flag.
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	// Optional thinking level: off, minimal, low, medium, high, xhigh, max.
	ThinkingLevel string `protobuf:"bytes,4,opt,name=thinking_level,json=thinkingLevel,proto3" json:"thinking_level,omitempty"`
	// Optional working directory for the session's pi process, absolute or
	// relative to the box's sandbox root. Must resolve inside the sandbox root
	// and exist. Empty keeps the server process working directory.
	Cwd           string `protobuf:"bytes,5,opt,name=cwd,proto3" json:"cwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSessionRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreateSessionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateSessionRequest) GetThinkingLevel() string {
	if x != nil {
		return x.ThinkingLevel
	}
	return ""
}

func (x *CreateSessionRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{2}
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{3}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{4}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Stats         *SessionStats          `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{5}
}

func (x *GetSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *GetSessionResponse) GetStats() *SessionStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Images        []*ImageContent        `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{6}
}

func (x *SendMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendMessageRequest) GetImages() []*ImageContent {
	if x != nil {
		return x.Images
	}
	return nil
}

type SendMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Text of the last assistant message after the run settled.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Stop reason of the last assistant message: stop, length, toolUse,
	// error, aborted. Empty when no assistant message was produced.
	StopReason string `protobuf:"bytes,2,opt,name=stop_reason,json=stopReason,proto3" json:"stop_reason,omitempty"`
	// Cumulative session statistics after the run.
	Stats         *SessionStats `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{7}
}

func (x *SendMessageResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendMessageResponse) GetStopReason() string {
	if x != nil {
		return x.StopReason
	}
	return ""
}

func (x *SendMessageResponse) GetStats() *SessionStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type StreamMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Images        []*ImageContent        `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessageRequest) Reset() {
	*x = StreamMessageRequest{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessageRequest) ProtoMessage() {}

func (x *StreamMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessageRequest.ProtoReflect.Descriptor instead.
func (*StreamMessageRequest) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{8}
}

func (x *StreamMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamMessageRequest) GetImages() []*ImageContent {
	if x != nil {
		return x.Images
	}
	return nil
}

type StreamMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pi event type (message_update, tool_execution_start, agent_settled, ...).
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Full pi event as JSON, passed through verbatim.
	PayloadJson   string `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessageResponse) Reset() {
	*x = StreamMessageResponse{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessageResponse) ProtoMessage() {}

func (x *StreamMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessageResponse.ProtoReflect.Descriptor instead.
func (*StreamMessageResponse) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{9}
}

func (x *StreamMessageResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StreamMessageResponse) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type SubmitMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Images        []*ImageContent        `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitMessageRequest) Reset() {
	*x = SubmitMessageRequest{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMessageRequest) ProtoMessage() {}

func (x *SubmitMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMessageRequest.ProtoReflect.Descriptor instead.
func (*SubmitMessageRequest) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{10}
}

func (x *SubmitMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubmitMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitMessageRequest) GetImages() []*ImageContent {
	if x != nil {
		return x.Images
	}
	return nil
}

type SubmitMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pi's entries cursor at submit time: the session's leaf entry id, "" for
	// a session with no entries yet. Stable across process restarts — pass it
	// to GetTurn to await or recover this turn's result.
	TurnCursor    string `protobuf:"bytes,1,opt,name=turn_cursor,json=turnCursor,proto3" json:"turn_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitMessageResponse) Reset() {
	*x = SubmitMessageResponse{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMessageResponse) ProtoMessage() {}

func (x *SubmitMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMessageResponse.ProtoReflect.Descriptor instead.
func (*SubmitMessageResponse) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitMessageResponse) GetTurnCursor() string {
	if x != nil {
		return x.TurnCursor
	}
	return ""
}

type GetTurnRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Cursor returned by SubmitMessage.
	TurnCursor string `protobuf:"bytes,2,opt,name=turn_cursor,json=turnCursor,proto3" json:"turn_cursor,omitempty"`
	// 0 answers immediately (pure poll); >0 waits up to this many seconds
	// (capped at 30) for the run to settle before answering.
	WaitSeconds   int32 `protobuf:"varint,3,opt,name=wait_seconds,json=waitSeconds,proto3" json:"wait_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTurnRequest) Reset() {
	*x = GetTurnRequest{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTurnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTurnRequest) ProtoMessage() {}

func (x *GetTurnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTurnRequest.ProtoReflect.Descriptor instead.
func (*GetTurnRequest) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{12}
}

func (x *GetTurnRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetTurnRequest) GetTurnCursor() string {
	if x != nil {
		return x.TurnCursor
	}
	return ""
}

func (x *GetTurnRequest) GetWaitSeconds() int32 {
	if x != nil {
		return x.WaitSeconds
	}
	return 0
}

type GetTurnResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True while a run is still in flight on the session.
	Running bool `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	// Set when entries past turn_cursor contain an assistant message. Unset
	// with running=false means the turn did not finish (e.g. the process was
	// restarted mid-run or the turn was aborted before any assistant reply).
	Result        *TurnResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTurnResponse) Reset() {
	*x = GetTurnResponse{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTurnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTurnResponse) ProtoMessage() {}

func (x *GetTurnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTurnResponse.ProtoReflect.Descriptor instead.
func (*GetTurnResponse) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{13}
}

func (x *GetTurnResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *GetTurnResponse) GetResult() *TurnResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type TurnResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Text of the last assistant message produced after the turn cursor.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Stop reason of that assistant message: stop, length, toolUse, error,
	// aborted.
	StopReason string `protobuf:"bytes,2,opt,name=stop_reason,json=stopReason,proto3" json:"stop_reason,omitempty"`
	// Cumulative session statistics.
	Stats         *SessionStats `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnResult) Reset() {
	*x = TurnResult{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnResult) ProtoMessage() {}

func (x *TurnResult) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnResult.ProtoReflect.Descriptor instead.
func (*TurnResult) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{14}
}

func (x *TurnResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TurnResult) GetStopReason() string {
	if x != nil {
		return x.StopReason
	}
	return ""
}

func (x *TurnResult) GetStats() *SessionStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type ListEntriesRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Entry id to list from, exclusive: a turn_cursor from SubmitMessage or
	// the id of the last entry already seen. Empty lists the full transcript.
	AfterCursor   string `protobuf:"bytes,2,opt,name=after_cursor,json=afterCursor,proto3" json:"after_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesRequest) Reset() {
	*x = ListEntriesRequest{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesRequest) ProtoMessage() {}

func (x *ListEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListEntriesRequest) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{15}
}

func (x *ListEntriesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListEntriesRequest) GetAfterCursor() string {
	if x != nil {
		return x.AfterCursor
	}
	return ""
}

type ListEntriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entries past after_cursor, oldest first.
	Entries []*Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// The session's current leaf entry id ("" for a session with no entries).
	// Pass it as after_cursor to poll for what comes next.
	LeafId string `protobuf:"bytes,2,opt,name=leaf_id,json=leafId,proto3" json:"leaf_id,omitempty"`
	// True while a run is in flight; more entries will appear.
	Running       bool `protobuf:"varint,3,opt,name=running,proto3" json:"running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesResponse) Reset() {
	*x = ListEntriesResponse{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesResponse) ProtoMessage() {}

func (x *ListEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListEntriesResponse) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{16}
}

func (x *ListEntriesResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListEntriesResponse) GetLeafId() string {
	if x != nil {
		return x.LeafId
	}
	return ""
}

func (x *ListEntriesResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pi's entry id, usable as an after_cursor.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// pi entry type (message, model_change, thinking_level_change, ...).
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Full pi entry as JSON, passed through verbatim.
	PayloadJson   string `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{17}
}

func (x *Entry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entry) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type GetAvailableModelsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional session whose pi process answers — its scoped model config may
	// differ. Empty answers from the box: a short-lived pi process reads the
	// catalog, and the result is cached for a few minutes.
	SessionId     string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableModelsRequest) Reset() {
	*x = GetAvailableModelsRequest{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableModelsRequest) ProtoMessage() {}

func (x *GetAvailableModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableModelsRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableModelsRequest) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{18}
}

func (x *GetAvailableModelsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetAvailableModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableModelsResponse) Reset() {
	*x = GetAvailableModelsResponse{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableModelsResponse) ProtoMessage() {}

func (x *GetAvailableModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableModelsResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableModelsResponse) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{19}
}

func (x *GetAvailableModelsResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

type Model struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model ID as accepted by pi's --model flag and set_model (e.g.
	// "claude-fable-5").
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Provider ID (e.g. "anthropic").
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	// Human-readable model name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Wire API the model speaks (e.g. "anthropic-messages",
	// "openai-responses").
	Api string `protobuf:"bytes,4,opt,name=api,proto3" json:"api,omitempty"`
	// True when the model supports reasoning/thinking.
	Reasoning bool `protobuf:"varint,5,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	// Supported input modalities: "text", "image".
	Input         []string `protobuf:"bytes,6,rep,name=input,proto3" json:"input,omitempty"`
	ContextWindow int64    `protobuf:"varint,7,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	MaxTokens     int64    `protobuf:"varint,8,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	// Cost in USD per million tokens.
	Cost          *ModelCost `protobuf:"bytes,9,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{20}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *Model) GetReasoning() bool {
	if x != nil {
		return x.Reasoning
	}
	return false
}

func (x *Model) GetInput() []string {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Model) GetContextWindow() int64 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *Model) GetMaxTokens() int64 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *Model) GetCost() *ModelCost {
	if x != nil {
		return x.Cost
	}
	return nil
}

type ModelCost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         float64                `protobuf:"fixed64,1,opt,name=input,proto3" json:"input,omitempty"`
	Output        float64                `protobuf:"fixed64,2,opt,name=output,proto3" json:"output,omitempty"`
	CacheRead     float64                `protobuf:"fixed64,3,opt,name=cache_read,json=cacheRead,proto3" json:"cache_read,omitempty"`
	CacheWrite    float64                `protobuf:"fixed64,4,opt,name=cache_write,json=cacheWrite,proto3" json:"cache_write,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelCost) Reset() {
	*x = ModelCost{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelCost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelCost) ProtoMessage() {}

func (x *ModelCost) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelCost.ProtoReflect.Descriptor instead.
func (*ModelCost) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{21}
}

func (x *ModelCost) GetInput() float64 {
	if x != nil {
		return x.Input
	}
	return 0
}

func (x *ModelCost) GetOutput() float64 {
	if x != nil {
		return x.Output
	}
	return 0
}

func (x *ModelCost) GetCacheRead() float64 {
	if x != nil {
		return x.CacheRead
	}
	return 0
}

func (x *ModelCost) GetCacheWrite() float64 {
	if x != nil {
		return x.CacheWrite
	}
	return 0
}

type ListDirectoriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Directory to list, absolute or relative to the box's sandbox root. Empty
	// lists the sandbox root itself. Must resolve inside the sandbox root and
	// be an existing directory.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Include entries whose name starts with "." (skipped by default).
	IncludeHidden bool `protobuf:"varint,2,opt,name=include_hidden,json=includeHidden,proto3" json:"include_hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoriesRequest) Reset() {
	*x = ListDirectoriesRequest{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoriesRequest) ProtoMessage() {}

func (x *ListDirectoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoriesRequest.ProtoReflect.Descriptor instead.
func (*ListDirectoriesRequest) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{22}
}

func (x *ListDirectoriesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListDirectoriesRequest) GetIncludeHidden() bool {
	if x != nil {
		return x.IncludeHidden
	}
	return false
}

type ListDirectoriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute path of the listed directory.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Immediate subdirectories, sorted by name. Symlinked directories are not
	// reported, so walking these listings never leaves the sandbox root.
	Directories []*Directory `protobuf:"bytes,2,rep,name=directories,proto3" json:"directories,omitempty"`
	// True when the listing hit the server cap and is incomplete.
	Truncated     bool `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoriesResponse) Reset() {
	*x = ListDirectoriesResponse{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoriesResponse) ProtoMessage() {}

func (x *ListDirectoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoriesResponse.ProtoReflect.Descriptor instead.
func (*ListDirectoriesResponse) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{23}
}

func (x *ListDirectoriesResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListDirectoriesResponse) GetDirectories() []*Directory {
	if x != nil {
		return x.Directories
	}
	return nil
}

func (x *ListDirectoriesResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type Directory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base name of the directory.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Absolute path, usable as CreateSession.cwd or a further ListDirectories
	// path.
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Directory) Reset() {
	*x = Directory{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Directory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Directory) ProtoMessage() {}

func (x *Directory) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Directory.ProtoReflect.Descriptor instead.
func (*Directory) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{24}
}

func (x *Directory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Directory) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type AbortSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortSessionRequest) Reset() {
	*x = AbortSessionRequest{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortSessionRequest) ProtoMessage() {}

func (x *AbortSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortSessionRequest.ProtoReflect.Descriptor instead.
func (*AbortSessionRequest) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{25}
}

func (x *AbortSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AbortSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortSessionResponse) Reset() {
	*x = AbortSessionResponse{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortSessionResponse) ProtoMessage() {}

func (x *AbortSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortSessionResponse.ProtoReflect.Descriptor instead.
func (*AbortSessionResponse) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{26}
}

type DeleteSessionRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Also delete the session file from pi's session directory.
	Purge         bool `protobuf:"varint,2,opt,name=purge,proto3" json:"purge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DeleteSessionRequest) GetPurge() bool {
	if x != nil {
		return x.Purge
	}
	return false
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{28}
}

type Session struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pi's session ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Display name, if set.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Absolute path of the session JSONL file ("" for ephemeral sessions).
	SessionFile string `protobuf:"bytes,3,opt,name=session_file,json=sessionFile,proto3" json:"session_file,omitempty"`
	// Selected model as "provider/id" ("" when pi reports none).
	Model string `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	// True while a run is in flight.
	Streaming bool `protobuf:"varint,5,opt,name=streaming,proto3" json:"streaming,omitempty"`
	// Number of messages in the session (0 for inactive sessions, which are
	// reported from disk without being attached).
	MessageCount int32 `protobuf:"varint,6,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	// Effective working directory of the session process ("" when unknown).
	Cwd string `protobuf:"bytes,7,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// True when a pi process currently hosts this session on the box. Inactive
	// sessions re-attach transparently on first use.
	Active bool `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	// Unix seconds of the session file's last modification (0 when unknown).
	UpdatedAtUnix int64 `protobuf:"varint,9,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{29}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetSessionFile() string {
	if x != nil {
		return x.SessionFile
	}
	return ""
}

func (x *Session) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Session) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *Session) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *Session) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *Session) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Session) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type SessionStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InputTokens      int64                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens     int64                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CacheReadTokens  int64                  `protobuf:"varint,3,opt,name=cache_read_tokens,json=cacheReadTokens,proto3" json:"cache_read_tokens,omitempty"`
	CacheWriteTokens int64                  `protobuf:"varint,4,opt,name=cache_write_tokens,json=cacheWriteTokens,proto3" json:"cache_write_tokens,omitempty"`
	// Total session cost in USD.
	Cost float64 `protobuf:"fixed64,5,opt,name=cost,proto3" json:"cost,omitempty"`
	// Current context window usage percentage (0 when unknown).
	ContextPercent int32 `protobuf:"varint,6,opt,name=context_percent,json=contextPercent,proto3" json:"context_percent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionStats) Reset() {
	*x = SessionStats{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStats) ProtoMessage() {}

func (x *SessionStats) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStats.ProtoReflect.Descriptor instead.
func (*SessionStats) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{30}
}

func (x *SessionStats) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *SessionStats) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *SessionStats) GetCacheReadTokens() int64 {
	if x != nil {
		return x.CacheReadTokens
	}
	return 0
}

func (x *SessionStats) GetCacheWriteTokens() int64 {
	if x != nil {
		return x.CacheWriteTokens
	}
	return 0
}

func (x *SessionStats) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *SessionStats) GetContextPercent() int32 {
	if x != nil {
		return x.ContextPercent
	}
	return 0
}

type ImageContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g. "image/png".
	MimeType string `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Raw image bytes.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageContent) Reset() {
	*x = ImageContent{}
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageContent) ProtoMessage() {}

func (x *ImageContent) ProtoReflect() protoreflect.Message {
	mi := &file_butterbox_pi_v1_pi_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageContent.ProtoReflect.Descriptor instead.
func (*ImageContent) Descriptor() ([]byte, []int) {
	return file_butterbox_pi_v1_pi_proto_rawDescGZIP(), []int{31}
}

func (x *ImageContent) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ImageContent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_butterbox_pi_v1_pi_proto protoreflect.FileDescriptor

const file_butterbox_pi_v1_pi_proto_rawDesc = "" +
	"\n" +
	"\x18butterbox/pi/v1/pi.proto\x12\x0fbutterbox.pi.v1\"\x95\x01\n" +
	"\x14CreateSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12%\n" +
	"\x0ethinking_level\x18\x04 \x01(\tR\rthinkingLevel\x12\x10\n" +
	"\x03cwd\x18\x05 \x01(\tR\x03cwd\"K\n" +
	"\x15CreateSessionResponse\x122\n" +
	"\asession\x18\x01 \x01(\v2\x18.butterbox.pi.v1.SessionR\asession\"\x15\n" +
	"\x13ListSessionsRequest\"L\n" +
	"\x14ListSessionsResponse\x124\n" +
	"\bsessions\x18\x01 \x03(\v2\x18.butterbox.pi.v1.SessionR\bsessions\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"}\n" +
	"\x12GetSessionResponse\x122\n" +
	"\asession\x18\x01 \x01(\v2\x18.butterbox.pi.v1.SessionR\asession\x123\n" +
	"\x05stats\x18\x02 \x01(\v2\x1d.butterbox.pi.v1.SessionStatsR\x05stats\"\x84\x01\n" +
	"\x12SendMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\x06images\x18\x03 \x03(\v2\x1d.butterbox.pi.v1.ImageContentR\x06images\"\x7f\n" +
	"\x13SendMessageResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1f\n" +
	"\vstop_reason\x18\x02 \x01(\tR\n" +
	"stopReason\x123\n" +
	"\x05stats\x18\x03 \x01(\v2\x1d.butterbox.pi.v1.SessionStatsR\x05stats\"\x86\x01\n" +
	"\x14StreamMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\x06images\x18\x03 \x03(\v2\x1d.butterbox.pi.v1.ImageContentR\x06images\"N\n" +
	"\x15StreamMessageResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\tR\vpayloadJson\"\x86\x01\n" +
	"\x14SubmitMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\x06images\x18\x03 \x03(\v2\x1d.butterbox.pi.v1.ImageContentR\x06images\"8\n" +
	"\x15SubmitMessageResponse\x12\x1f\n" +
	"\vturn_cursor\x18\x01 \x01(\tR\n" +
	"turnCursor\"s\n" +
	"\x0eGetTurnRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vturn_cursor\x18\x02 \x01(\tR\n" +
	"turnCursor\x12!\n" +
	"\fwait_seconds\x18\x03 \x01(\x05R\vwaitSeconds\"`\n" +
	"\x0fGetTurnResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x123\n" +
	"\x06result\x18\x02 \x01(\v2\x1b.butterbox.pi.v1.TurnResultR\x06result\"v\n" +
	"\n" +
	"TurnResult\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1f\n" +
	"\vstop_reason\x18\x02 \x01(\tR\n" +
	"stopReason\x123\n" +
	"\x05stats\x18\x03 \x01(\v2\x1d.butterbox.pi.v1.SessionStatsR\x05stats\"V\n" +
	"\x12ListEntriesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fafter_cursor\x18\x02 \x01(\tR\vafterCursor\"z\n" +
	"\x13ListEntriesResponse\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.butterbox.pi.v1.EntryR\aentries\x12\x17\n" +
	"\aleaf_id\x18\x02 \x01(\tR\x06leafId\x12\x18\n" +
	"\arunning\x18\x03 \x01(\bR\arunning\"N\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\tR\vpayloadJson\":\n" +
	"\x19GetAvailableModelsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"L\n" +
	"\x1aGetAvailableModelsResponse\x12.\n" +
	"\x06models\x18\x01 \x03(\v2\x16.butterbox.pi.v1.ModelR\x06models\"\x83\x02\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03api\x18\x04 \x01(\tR\x03api\x12\x1c\n" +
	"\treasoning\x18\x05 \x01(\bR\treasoning\x12\x14\n" +
	"\x05input\x18\x06 \x03(\tR\x05input\x12%\n" +
	"\x0econtext_window\x18\a \x01(\x03R\rcontextWindow\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\b \x01(\x03R\tmaxTokens\x12.\n" +
	"\x04cost\x18\t \x01(\v2\x1a.butterbox.pi.v1.ModelCostR\x04cost\"y\n" +
	"\tModelCost\x12\x14\n" +
	"\x05input\x18\x01 \x01(\x01R\x05input\x12\x16\n" +
	"\x06output\x18\x02 \x01(\x01R\x06output\x12\x1d\n" +
	"\n" +
	"cache_read\x18\x03 \x01(\x01R\tcacheRead\x12\x1f\n" +
	"\vcache_write\x18\x04 \x01(\x01R\n" +
	"cacheWrite\"S\n" +
	"\x16ListDirectoriesRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12%\n" +
	"\x0einclude_hidden\x18\x02 \x01(\bR\rincludeHidden\"\x89\x01\n" +
	"\x17ListDirectoriesResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12<\n" +
	"\vdirectories\x18\x02 \x03(\v2\x1a.butterbox.pi.v1.DirectoryR\vdirectories\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\"3\n" +
	"\tDirectory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"4\n" +
	"\x13AbortSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x16\n" +
	"\x14AbortSessionResponse\"K\n" +
	"\x14DeleteSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05purge\x18\x02 \x01(\bR\x05purge\"\x17\n" +
	"\x15DeleteSessionResponse\"\xfb\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fsession_file\x18\x03 \x01(\tR\vsessionFile\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x1c\n" +
	"\tstreaming\x18\x05 \x01(\bR\tstreaming\x12#\n" +
	"\rmessage_count\x18\x06 \x01(\x05R\fmessageCount\x12\x10\n" +
	"\x03cwd\x18\a \x01(\tR\x03cwd\x12\x16\n" +
	"\x06active\x18\b \x01(\bR\x06active\x12&\n" +
	"\x0fupdated_at_unix\x18\t \x01(\x03R\rupdatedAtUnix\"\xed\x01\n" +
	"\fSessionStats\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x03R\foutputTokens\x12*\n" +
	"\x11cache_read_tokens\x18\x03 \x01(\x03R\x0fcacheReadTokens\x12,\n" +
	"\x12cache_write_tokens\x18\x04 \x01(\x03R\x10cacheWriteTokens\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x01R\x04cost\x12'\n" +
	"\x0fcontext_percent\x18\x06 \x01(\x05R\x0econtextPercent\"?\n" +
	"\fImageContent\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data2\xf5\b\n" +
	"\tPiService\x12^\n" +
	"\rCreateSession\x12%.butterbox.pi.v1.CreateSessionRequest\x1a&.butterbox.pi.v1.CreateSessionResponse\x12[\n" +
	"\fListSessions\x12$.butterbox.pi.v1.ListSessionsRequest\x1a%.butterbox.pi.v1.ListSessionsResponse\x12X\n" +
	"\vListEntries\x12#.butterbox.pi.v1.ListEntriesRequest\x1a$.butterbox.pi.v1.ListEntriesResponse\x12U\n" +
	"\n" +
	"GetSession\x12\".butterbox.pi.v1.GetSessionRequest\x1a#.butterbox.pi.v1.GetSessionResponse\x12X\n" +
	"\vSendMessage\x12#.butterbox.pi.v1.SendMessageRequest\x1a$.butterbox.pi.v1.SendMessageResponse\x12`\n" +
	"\rStreamMessage\x12%.butterbox.pi.v1.StreamMessageRequest\x1a&.butterbox.pi.v1.StreamMessageResponse0\x01\x12^\n" +
	"\rSubmitMessage\x12%.butterbox.pi.v1.SubmitMessageRequest\x1a&.butterbox.pi.v1.SubmitMessageResponse\x12L\n" +
	"\aGetTurn\x12\x1f.butterbox.pi.v1.GetTurnRequest\x1a .butterbox.pi.v1.GetTurnResponse\x12m\n" +
	"\x12GetAvailableModels\x12*.butterbox.pi.v1.GetAvailableModelsRequest\x1a+.butterbox.pi.v1.GetAvailableModelsResponse\x12d\n" +
	"\x0fListDirectories\x12'.butterbox.pi.v1.ListDirectoriesRequest\x1a(.butterbox.pi.v1.ListDirectoriesResponse\x12[\n" +
	"\fAbortSession\x12$.butterbox.pi.v1.AbortSessionRequest\x1a%.butterbox.pi.v1.AbortSessionResponse\x12^\n" +
	"\rDeleteSession\x12%.butterbox.pi.v1.DeleteSessionRequest\x1a&.butterbox.pi.v1.DeleteSessionResponseB=Z;github.com/orvice/butter-box/pkg/proto/butterbox/pi/v1;piv1b\x06proto3"

var (
	file_butterbox_pi_v1_pi_proto_rawDescOnce sync.Once
	file_butterbox_pi_v1_pi_proto_rawDescData []byte
)

func file_butterbox_pi_v1_pi_proto_rawDescGZIP() []byte {
	file_butterbox_pi_v1_pi_proto_rawDescOnce.Do(func() {
		file_butterbox_pi_v1_pi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_butterbox_pi_v1_pi_proto_rawDesc), len(file_butterbox_pi_v1_pi_proto_rawDesc)))
	})
	return file_butterbox_pi_v1_pi_proto_rawDescData
}

var file_butterbox_pi_v1_pi_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_butterbox_pi_v1_pi_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),       // 0: butterbox.pi.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),      // 1: butterbox.pi.v1.CreateSessionResponse
	(*ListSessionsRequest)(nil),        // 2: butterbox.pi.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),       // 3: butterbox.pi.v1.ListSessionsResponse
	(*GetSessionRequest)(nil),          // 4: butterbox.pi.v1.GetSessionRequest
	(*GetSessionResponse)(nil),         // 5: butterbox.pi.v1.GetSessionResponse
	(*SendMessageRequest)(nil),         // 6: butterbox.pi.v1.SendMessageRequest
	(*SendMessageResponse)(nil),        // 7: butterbox.pi.v1.SendMessageResponse
	(*StreamMessageRequest)(nil),       // 8: butterbox.pi.v1.StreamMessageRequest
	(*StreamMessageResponse)(nil),      // 9: butterbox.pi.v1.StreamMessageResponse
	(*SubmitMessageRequest)(nil),       // 10: butterbox.pi.v1.SubmitMessageRequest
	(*SubmitMessageResponse)(nil),      // 11: butterbox.pi.v1.SubmitMessageResponse
	(*GetTurnRequest)(nil),             // 12: butterbox.pi.v1.GetTurnRequest
	(*GetTurnResponse)(nil),            // 13: butterbox.pi.v1.GetTurnResponse
	(*TurnResult)(nil),                 // 14: butterbox.pi.v1.TurnResult
	(*ListEntriesRequest)(nil),         // 15: butterbox.pi.v1.ListEntriesRequest
	(*ListEntriesResponse)(nil),        // 16: butterbox.pi.v1.ListEntriesResponse
	(*Entry)(nil),                      // 17: butterbox.pi.v1.Entry
	(*GetAvailableModelsRequest)(nil),  // 18: butterbox.pi.v1.GetAvailableModelsRequest
	(*GetAvailableModelsResponse)(nil), // 19: butterbox.pi.v1.GetAvailableModelsResponse
	(*Model)(nil),                      // 20: butterbox.pi.v1.Model
	(*ModelCost)(nil),                  // 21: butterbox.pi.v1.ModelCost
	(*ListDirectoriesRequest)(nil),     // 22: butterbox.pi.v1.ListDirectoriesRequest
	(*ListDirectoriesResponse)(nil),    // 23: butterbox.pi.v1.ListDirectoriesResponse
	(*Directory)(nil),                  // 24: butterbox.pi.v1.Directory
	(*AbortSessionRequest)(nil),        // 25: butterbox.pi.v1.AbortSessionRequest
	(*AbortSessionResponse)(nil),       // 26: butterbox.pi.v1.AbortSessionResponse
	(*DeleteSessionRequest)(nil),       // 27: butterbox.pi.v1.DeleteSessionRequest
	(*DeleteSessionResponse)(nil),      // 28: butterbox.pi.v1.DeleteSessionResponse
	(*Session)(nil),                    // 29: butterbox.pi.v1.Session
	(*SessionStats)(nil),               // 30: butterbox.pi.v1.SessionStats
	(*ImageContent)(nil),               // 31: butterbox.pi.v1.ImageContent
}
var file_butterbox_pi_v1_pi_proto_depIdxs = []int32{
	29, // 0: butterbox.pi.v1.CreateSessionResponse.session:type_name -> butterbox.pi.v1.Session
	29, // 1: butterbox.pi.v1.ListSessionsResponse.sessions:type_name -> butterbox.pi.v1.Session
	29, // 2: butterbox.pi.v1.GetSessionResponse.session:type_name -> butterbox.pi.v1.Session
	30, // 3: butterbox.pi.v1.GetSessionResponse.stats:type_name -> butterbox.pi.v1.SessionStats
	31, // 4: butterbox.pi.v1.SendMessageRequest.images:type_name -> butterbox.pi.v1.ImageContent
	30, // 5: butterbox.pi.v1.SendMessageResponse.stats:type_name -> butterbox.pi.v1.SessionStats
	31, // 6: butterbox.pi.v1.StreamMessageRequest.images:type_name -> butterbox.pi.v1.ImageContent
	31, // 7: butterbox.pi.v1.SubmitMessageRequest.images:type_name -> butterbox.pi.v1.ImageContent
	14, // 8: butterbox.pi.v1.GetTurnResponse.result:type_name -> butterbox.pi.v1.TurnResult
	30, // 9: butterbox.pi.v1.TurnResult.stats:type_name -> butterbox.pi.v1.SessionStats
	17, // 10: butterbox.pi.v1.ListEntriesResponse.entries:type_name -> butterbox.pi.v1.Entry
	20, // 11: butterbox.pi.v1.GetAvailableModelsResponse.models:type_name -> butterbox.pi.v1.Model
	21, // 12: butterbox.pi.v1.Model.cost:type_name -> butterbox.pi.v1.ModelCost
	24, // 13: butterbox.pi.v1.ListDirectoriesResponse.directories:type_name -> butterbox.pi.v1.Directory
	0,  // 14: butterbox.pi.v1.PiService.CreateSession:input_type -> butterbox.pi.v1.CreateSessionRequest
	2,  // 15: butterbox.pi.v1.PiService.ListSessions:input_type -> butterbox.pi.v1.ListSessionsRequest
	15, // 16: butterbox.pi.v1.PiService.ListEntries:input_type -> butterbox.pi.v1.ListEntriesRequest
	4,  // 17: butterbox.pi.v1.PiService.GetSession:input_type -> butterbox.pi.v1.GetSessionRequest
	6,  // 18: butterbox.pi.v1.PiService.SendMessage:input_type -> butterbox.pi.v1.SendMessageRequest
	8,  // 19: butterbox.pi.v1.PiService.StreamMessage:input_type -> butterbox.pi.v1.StreamMessageRequest
	10, // 20: butterbox.pi.v1.PiService.SubmitMessage:input_type -> butterbox.pi.v1.SubmitMessageRequest
	12, // 21: butterbox.pi.v1.PiService.GetTurn:input_type -> butterbox.pi.v1.GetTurnRequest
	18, // 22: butterbox.pi.v1.PiService.GetAvailableModels:input_type -> butterbox.pi.v1.GetAvailableModelsRequest
	22, // 23: butterbox.pi.v1.PiService.ListDirectories:input_type -> butterbox.pi.v1.ListDirectoriesRequest
	25, // 24: butterbox.pi.v1.PiService.AbortSession:input_type -> butterbox.pi.v1.AbortSessionRequest
	27, // 25: butterbox.pi.v1.PiService.DeleteSession:input_type -> butterbox.pi.v1.DeleteSessionRequest
	1,  // 26: butterbox.pi.v1.PiService.CreateSession:output_type -> butterbox.pi.v1.CreateSessionResponse
	3,  // 27: butterbox.pi.v1.PiService.ListSessions:output_type -> butterbox.pi.v1.ListSessionsResponse
	16, // 28: butterbox.pi.v1.PiService.ListEntries:output_type -> butterbox.pi.v1.ListEntriesResponse
	5,  // 29: butterbox.pi.v1.PiService.GetSession:output_type -> butterbox.pi.v1.GetSessionResponse
	7,  // 30: butterbox.pi.v1.PiService.SendMessage:output_type -> butterbox.pi.v1.SendMessageResponse
	9,  // 31: butterbox.pi.v1.PiService.StreamMessage:output_type -> butterbox.pi.v1.StreamMessageResponse
	11, // 32: butterbox.pi.v1.PiService.SubmitMessage:output_type -> butterbox.pi.v1.SubmitMessageResponse
	13, // 33: butterbox.pi.v1.PiService.GetTurn:output_type -> butterbox.pi.v1.GetTurnResponse
	19, // 34: butterbox.pi.v1.PiService.GetAvailableModels:output_type -> butterbox.pi.v1.GetAvailableModelsResponse
	23, // 35: butterbox.pi.v1.PiService.ListDirectories:output_type -> butterbox.pi.v1.ListDirectoriesResponse
	26, // 36: butterbox.pi.v1.PiService.AbortSession:output_type -> butterbox.pi.v1.AbortSessionResponse
	28, // 37: butterbox.pi.v1.PiService.DeleteSession:output_type -> butterbox.pi.v1.DeleteSessionResponse
	26, // [26:38] is the sub-list for method output_type
	14, // [14:26] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_butterbox_pi_v1_pi_proto_init() }
func file_butterbox_pi_v1_pi_proto_init() {
	if File_butterbox_pi_v1_pi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_butterbox_pi_v1_pi_proto_rawDesc), len(file_butterbox_pi_v1_pi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_butterbox_pi_v1_pi_proto_goTypes,
		DependencyIndexes: file_butterbox_pi_v1_pi_proto_depIdxs,
		MessageInfos:      file_butterbox_pi_v1_pi_proto_msgTypes,
	}.Build()
	File_butterbox_pi_v1_pi_proto = out.File
	file_butterbox_pi_v1_pi_proto_goTypes = nil
	file_butterbox_pi_v1_pi_proto_depIdxs = nil
}
